### ISSUE TITLE
Deprecated function: Return type

### ISSUE THREAD

**Issue by rakeshf** [thephpleague/oauth2-client#1010]
League\OAuth2\Client\Token\AccessToken::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed

**Comment by sanghamitra2704** [comment]
Patch to fix this issue in 9.5.9 -
[jsonserialize_deprecation_notice.patch](https://github.com/thephpleague/oauth2-client/files/12573082/jsonserialize_deprecation_notice.patch)
