### ISSUE TITLE
PHP Combability issue

### ISSUE THREAD

**Issue by DevStrefa** [thephpleague/oauth2-client#1013]
In the doc I found that library is supporting PHP from 5.6 to 8.2 but in reality due to Guzzle requirements package is working only with PHP 8.1+ versions.

**Comment by gnovaro** [comment]
Guzzle docs says version 6 support old php version >5.5
https://github.com/guzzle/guzzle/tree/6.5

6.x 	Security fixes 	guzzlehttp/guzzle 	GuzzleHttp 	[v6](https://github.com/guzzle/guzzle/tree/6.5) 	[v6](https://docs.guzzlephp.org/en/6.5/) 	Yes 	>=5.5,<8.0

**Comment by ramsey** [comment]
There should not have been a problem using this package at version 2.7.0 with Guzzle v6.5.8 (the version with the security fixes) on PHP 5.6.

In the latest version (2.8.0), we have updated the minimum required version of PHP to 7.1.
