### ISSUE TITLE
Allow any psr-18 http client (instead of requiring guzzle)

### ISSUE THREAD

**Issue by tacman** [thephpleague/oauth2-client#1019]
```bash
composer why guzzlehttp/guzzle
league/oauth2-client 2.7.0 requires guzzlehttp/guzzle (^6.0 || ^7.0) 
```

I prefer to use the Symfony HttpClient, but this package requires guzzle.  Any chance it could be more generic, that is, require any PSR-18 client to operate, then the user can install guzzle or whatever they want.

Thanks for your consideration.  Not urgent, but it'd be nice to have one less dependency.

**Comment by cyraid** [comment]
This has been getting me too, as I have to use full out guzzle now since Payum checks if classes exist, and Guzzle is high up there, so it'll of course use that.
