### ISSUE TITLE
Receive invalid_request while getAccessToken

### ISSUE THREAD

**Issue by szkruk** [thephpleague/oauth2-client#1035]
I'm trying to integrate with the Okta using oauth2-client. When i try to log in, I get error:
invalid_request#0 /var/www/html/app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628)

`
$accessToken = $oauthClient->getAccessToken('authorization_code', [
                'code' => $code,
            ]);
`

I assume $code is valid, because it's returned from Okta.

error trace:

invalid_request#0 /var/www/html/app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(GuzzleHttp\Psr7\Response, Array) #1 /var/www/html/app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(GuzzleHttp\Psr7\Request) #2 /var/www/html/app/src/Service/Auth/OktaAuthenticator.php(133): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(League\OAuth2\Client\Grant\AuthorizationCode, Array)
--

invalid_request#0 /var/www/html/app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628)](http://app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628)): League\OAuth2\Client\Provider\GenericProvider->checkResponse(GuzzleHttp\Psr7\Response, Array)
#1 /var/www/html/[app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537)](http://app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537)): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(GuzzleHttp\Psr7\Request)
#2 /var/www/html/[app/src/Service/Auth/OktaAuthenticator.php(133)](http://lapp./src/Service/Auth/OktaAuthenticator.php(133)): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(League\OAuth2\Client\Grant\AuthorizationCode, Array)

**Comment by plierschpl** [comment]
Maybe is your OpenID Provider hosted with https and your OpenID with http
This was my fail... the client and the server must be running with HTTPS or all with HTTP without redirects to HTTPS

**Comment by szkruk** [comment]
@Curadise It turned out that It was not problem of my code. I just didnt have access to Okta application and something was changed there without my knowledge
