### ISSUE TITLE
PHP 8.4 compatibility

### ISSUE THREAD

**Issue by Bilge** [thephpleague/oauth2-client#1040]
>Deprecated: League\OAuth2\Client\Provider\AbstractProvider::authorize(): Implicitly marking parameter $redirectHandler as nullable is deprecated, the explicit nullable type must be used instead

**Comment by danepowell** [comment]
https://github.com/thephpleague/oauth2-client/pull/1039

**Comment by ramsey** [comment]
I've just released version 2.8.0, which supports PHP 8.4. Thanks!
