### ISSUE TITLE
Make error_description and error_uri accessible

### ISSUE THREAD

**Issue by aripringle** [thephpleague/oauth2-client#106]
The OAuth2 spec allows for error_description and error_uri parameters in the error response (http://tools.ietf.org/html/rfc6749#section-5.2). The current implementation of IDPException doesn't expose these at all.

These details could arguably be added to the exception message, but I could see a use case for keeping the message with just the "error" key so it can be easily parsed. Would it make sense to add getErrorDescription and getErrorUri methods? Or perhaps just a getResult method that provides access to the $result property?

**Comment by ramsey** [comment]
Implemented in #229.
