### ISSUE TITLE
Handling invalid authorization code

### ISSUE THREAD

**Issue by ojhaujjwal** [thephpleague/oauth2-client#132]
The use case is: I use this library in a restful application. So, the authorization code is provided by javascript client(Angularjs app). Currently with invalid authorization code, `InvalidArgumentException` is thrown at `src/Token/AccessToken.php:38` with message:

```
Required option not passed: access_token
Array
(
    [{"error":{"message":"Invalid_verification_code_format_","type":"OAuthException","code":100}}] => 
)
```

**Comment by tyuwan** [comment]
Hi, I'm having the same error with 0.11.0 for Facebook.
