### ISSUE TITLE
Call to undefined method GuzzleHttp\Message\Response::getInfo() 

### ISSUE THREAD

**Issue by shameerc** [thephpleague/oauth2-client#190]
I'm getting the following error when trying to use Facebook auth provider.

Fatal error:  Call to undefined method `GuzzleHttp\Message\Response::getInfo()` in vendor/league/oauth2-client/src/Provider/Facebook.php on line 33

Apparently this method has been removed from Guzzle Response in version 4.

**Comment by ramsey** [comment]
The Facebook provider has been moved out of the 1.0 branch and is now maintained separately here: https://github.com/thephpleague/oauth2-facebook
