### ISSUE TITLE
PHP errors on /oauth2callback for Google sign-in

### ISSUE THREAD

**Issue by sylouuu** [thephpleague/oauth2-client#193]
Hi,

I'm using Codeigniter.

I'm sign-in from `/auth/google` and I added your code to the controller, I just updated the provider array:

```php
$provider = new League\OAuth2\Client\Provider\Google(array(
    'clientId'  =>  '...',
    'clientSecret'  =>  '...',
    'redirectUri'   =>  '..',
    'scopes' => array('email')
));

if (!isset($_GET['code'])) {

    // If we don't have an authorization code then get one
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->state;
    header('Location: '.$authUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

    unset($_SESSION['oauth2state']);
    exit('Invalid state');

} else {

    // Try to get an access token (using the authorization code grant)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);

    // If you are using Eventbrite you will need to add the grant_type parameter (see below)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code'],
        'grant_type' => 'authorization_code'
    ]);

    // Optional: Now you have a token you can look up a users profile data
    try {

        // We got an access token, let's now get the user's details
        $userDetails = $provider->getUserDetails($token);

        // Use these details to create a new profile
        printf('Hello %s!', $userDetails->firstName);

    } catch (Exception $e) {

        // Failed to get user details
        exit('Oh dear...');
    }

    // Use this to interact with an API on the users behalf
    echo $token->accessToken;

    // Use this to get a new access token if the old one expires
    echo $token->refreshToken;

    // Number of seconds until the access token will expire, and need refreshing
    echo $token->expires;
}
```

I have the confirm box, I accept. I'm redirected to `/oauth2callback` as expected. I've added the same code (just for testing) in that controller. `$_GET['state']` and `$_GET['code']` are filled.

Error is:

```
A PHP Error was encountered

Severity: 4096

Message: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::setResultUid() must be of the type array, null given, called in /path/to/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 221 and defined

Filename: Provider/AbstractProvider.php

Line Number: 231
```

In the mentioned file, I've done some `var_dump()`. Line 175 after:

```php
$requestParams = $grant->prepRequestParams($defaultParams, $params);
```

It's OK.

It bugs in `case 'POST':`.

I can print something after this line, but `var_dump($request);` or `var_dump($response);` doesn't show anything.

I'm using the latest version 0.7.0. I've well configured the project on the developer console (that's not the first time).

Any help appreciated.

Bests

**Comment by ramsey** [comment]
I just pushed out 0.7.1 with the fix from #194. Does this fix your issue?

**Comment by sylouuu** [comment]
I've switched to https://github.com/google/google-api-php-client

**Comment by ramsey** [comment]
Reopening so I can try to track down the following error and fix it:

```
Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::setResultUid() must be of the type array, null given
```

**Comment by dolfelt** [comment]
@ramsey I think the pull request #218 should fix the issue.

**Comment by ramsey** [comment]
Can someone reproduce this issue and then switch to the 0.8.0 release to see if it fixes it?

**Comment by jeteon** [comment]
I used to have the issue when I was using 0.7.2 even after enabling the Google + API in the developer console.

After upgrading to 0.8.0 I now get a fatal error:
`PHP Fatal error:  Uncaught invalid_client: invalid_client\n  thrown in {...}/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 214`.

As far as I can tell Google redirects me with `code` and `state` GET parameters to my redirect URL. I can't quite see where it is picking up an error in the chain.

**Comment by ramsey** [comment]
@dolfelt Can you reproduce this issue with 0.8.0?

**Comment by dolfelt** [comment]
@ramsey @jeteon It appears that the error isn't related to this fix, or even the code. The exception is being thrown because an `invalid_client` error is coming back from Google. This means the error is being properly parsed and handled.

https://github.com/thephpleague/oauth2-client/blob/0.8.0/src/Provider/AbstractProvider.php#L214

It could be a number of reasons why it is returning `invalid_client`. Usually it's a misconfiguration like [here](http://stackoverflow.com/questions/17166848/invalid-client-in-google-oauth2). I've also had issues if my code is old/used or the redirect URI doesn't match.

@jeteon What does your flow look like? Are you using a mobile SDK or JS library, or full server side OAuth?

**Comment by jeteon** [comment]
@dolfelt I am using it for full server side OAuth. I didn't really change anything but it suddenly works fine now even though I was getting the same error a few minutes ago. Maybe they changed something on the Google back end.

**Comment by dolfelt** [comment]
@jeteon I guess I'm not sure. Either way, this is a much better approach than exploding the raw error response by line breaks.
