### ISSUE TITLE
Is it possible to extend a supported provider?

### ISSUE THREAD

**Issue by codecowboy** [thephpleague/oauth2-client#195]
Is there a recommended way to add additional calls to a supported provider? For example if I want to make a LinkedIn API call to retrieve a person's skills :

https://developer.linkedin.com/documents/profile-fields#skills

Should I just create my own provider based on :

https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/LinkedIn.php

Or can I extend that provider somehow?

**Comment by codecowboy** [comment]
Thanks for this :) Can you expand on what you mean by create a LinkedIn composer package? I am aware of and use composer but have not created my own packages. Thanks!

**Comment by tpavlek** [comment]
You sure can!

But I wouldn't advise that - you can read more on the composer documentation page of course but the gist is: the vendor folder is volatile, stuff in there can be deleted at any point if composer determines it's an out of date or conflicting dependency. But you can use composer's autoloader no matter what the directory!

Say you created a composer package in a folder "src/LinkedIn" then in your `composer.json` you could have:

```json
"autoload": {
    "psr-4": {
        "MyVendor\\LinkedIn\\": "src/LinkedIn"
    }
}
```

composer would then load into the namespace MyVendor\LinkedIn everything in your src/LinkedIn folder. All that's required is that you have a composer.json file in your src/LinkedIn folder describing the package you've created.

For some less abstract examples you can check out the package I created to enable Battle.net authentication with the oauth2-client: https://github.com/tpavlek/oauth2-bnet.

Again, this stuff is probably out of scope for an issue on oauth2-client, if you're looking to learn more, the composer documentation is pretty good, and there's also #composer and #phpmentoring on freenode :)

**Comment by codecowboy** [comment]
@tpavlek thanks very much for that - really useful and helpful :)
