### ISSUE TITLE
Authorization Bearer Header

### ISSUE THREAD

**Issue by zot24** [thephpleague/oauth2-client#200]
Hi there!

I'm trying to integrate [Freeagent](https://dev.freeagent.com/docs) as a provider to your OAuth2 library however they send the token on each request in the headers, so my idea was override your method [fetchProviderData](https://github.com/thephpleague/oauth2-client/blob/374c3d41db38d1d2d4071c58fa5515f58ea4566e/src/Provider/AbstractProvider.php#L317) to be able to receive the token in that method and add it to the `header` as below:

```
protected function fetchProviderData($url, \League\OAuth2\Client\Token\AccessToken $token)
    {
        try {
            $client = $this->getHttpClient();
            $client->setBaseUrl($url);

            $client->setDefaultOption('headers', ['Authorization' => 'Bearer ' . $token]);

            $request = $client->get()->send();
```

Do you think it will be a good idea send a PR to change your [fetchProviderData](https://github.com/thephpleague/oauth2-client/blob/374c3d41db38d1d2d4071c58fa5515f58ea4566e/src/Provider/AbstractProvider.php#L317) method? for something like this:

```
protected function fetchProviderData($url, \League\OAuth2\Client\Token\AccessToken $token = null)
``` 

So we will be able to pass if we need it in our implementation the token.

Let me know your thoughts!

Cheers

**Comment by zot24** [comment]
You'll find and example of what I was talking about on our [FreeAgent provider](https://github.com/CloudManaged/oauth2-freeagent) is exactly in this [bit](https://github.com/CloudManaged/oauth2-freeagent/blob/master/src/Provider/Freeagent.php#L53) where I injected the `Authorization Bearer header` for each call that the provider does.

**Comment by zot24** [comment]
Just to keep this update I decided to revert the changes I made in the PR and use the following approach instead which I reckon is more cleaner and don't need to change the actual code of [oauth2-client](https://github.com/thephpleague/oauth2-client/)

```
$freeAgent = new FreeAgent(array(
    'sandbox' => true,
    'clientId'  =>  $config->freeagent->apiId,
    'clientSecret'  =>  $config->freeagent->apiKey
));
$token = $freeAgent->getAccessToken();
$freeAgent->headers = ['Authorization' => 'Bearer'.$token];

$contact = $freeAgent->createContact([
    'first_name' => 'test',
    'last_name' => 'test'
]);
```

So we inject the needed details just after create the object and get the token.

**Comment by ramsey** [comment]
Your solution looks good. Should I close the PR, then?

**Comment by zot24** [comment]
@ramsey I changed the PR and now is just and update for the README file pointing to our FreeAgent third party provider.

**Comment by zot24** [comment]
@ramsey Any update on this? The PR is just a modification for the documentation, let me know if you want me to change something. #201

**Comment by ramsey** [comment]
Sorry for the delay. I've just merged it in. Thanks!
