### ISSUE TITLE
Graph API v2.x

### ISSUE THREAD

**Issue by rbongerswux** [thephpleague/oauth2-client#202]
Facebook requires Graph API v2 by April 30. 
Wil this be changed? 

"You must upgrade this app to Graph API v2.x 
v1.0 will be deprecated on April 30, 2015"

**Comment by rbongerswux** [comment]
Composer can't find any update

**Comment by philsturgeon** [comment]
Click Subscribe on #210 and you'll be alerted when it's merged. Then you can request master from Composer **temporarily** or watch out for a new tagged version.

Either way, this will be resolved long before April. Don't worry!
