### ISSUE TITLE
No support for servers without curl

### ISSUE THREAD

**Issue by Jleagle** [thephpleague/oauth2-client#204]
I was unable to get oauth2-client to work on app engine without cURL. I presume this is down to using Guzzle v3 which is two major versions behind. I think v4+ is able to use other handlers to send requests.

**Comment by ramsey** [comment]
Version 1.0 will use https://github.com/egeloen/ivory-http-adapter, which allows you to use any number of HTTP adapters, as you like, including Guzzle 5.
