### ISSUE TITLE
User authentication with Password credentials grant fail with '@' in data

### ISSUE THREAD

**Issue by kevindierkx** [thephpleague/oauth2-client#206]
User authentication with usernames or passwords starting with an '@' fail on Guzzle level.
This is because Guzzle expects strings starting with an '@' to be files.

``` PHP
// Located in Guzzle\Http\Message::create()

...
// Normalize PHP style cURL uploads with a leading '@' symbol
foreach ($body as $key => $value) {
    if (is_string($value) && substr($value, 0, 1) == '@') {
        $request->addPostFile($key, $value);
        unset($body[$key]);
    }
}
...
```

Haven't tested it with newer versions of Guzzle but the above logic has been changed in newer versions.
I suggest updating to a Guzzle version that doesn't 'assume' things like this.

**Comment by kevindierkx** [comment]
The above results in the following exception.

```PHP
// Located in Guzzle\Http\Message\PostFile::setFilename()

...
if (!is_readable($filename)) {
    throw new InvalidArgumentException("Unable to open {$filename} for reading");
}
...
```

**Comment by ramsey** [comment]
Version 1.0 will use https://github.com/egeloen/ivory-http-adapter as a generic HTTP adapter, through which you may use Guzzle 5 or any other HTTP adapter it supports. Does this resolve this issue?

**Comment by kevindierkx** [comment]
Yeah, it should be resolved. The problem mentioned is purely the result of an outdated Guzzle dependency.

**Comment by ramsey** [comment]
Great. Thanks!
