### ISSUE TITLE
[Proposal] Add CSPRNG's to generate CSRF value

### ISSUE THREAD

**Issue by SammyK** [thephpleague/oauth2-client#212]
Hey guys!

The [code that generates the CSRF value](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L123) makes use of `uniqid()` and `rand()` which do not generate **cryptographically secure** pseudo-random values. Since the CSRF (`state`) value is a security feature to guard against [forgery attacks](http://en.wikipedia.org/wiki/Cross-site_request_forgery), it is paramount that the CSRF value is not forgeable (and it currently is.) In order to make this value forge-proof, we need to generate a pseudo-random value that is [cryptographically secure](http://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).

PHP particularly sucks at providing CSPRNG's, but there are a few options like [`openssl_random_pseudo_bytes()`](http://php.net/openssl_random_pseudo_bytes) and [`mcrypt_create_iv()`](http://php.net/mcrypt_create_iv). Unfortunately system support for these functions varies.

We recently added [injectable CSPRNG's](https://github.com/facebook/facebook-php-sdk-v4/tree/master/src/Facebook/PseudoRandomString) into the Facebook PHP SDK v4.1. Would you like to implement CSPRNG's using a similar method? Or perhaps we could make use of [Anthony Ferrara](https://twitter.com/ircmaxell)'s excellent [RandomLib](https://github.com/ircmaxell/RandomLib) package?

What do you guys think? :)

**Comment by vimishor** [comment]
I'm not in a position to decide the future of this library, but I like the solution used in Facebook SDK.

**Comment by ramsey** [comment]
It would be nice if the user could inject whatever CSPRNG they like into the library, so that we're not dependent on a single one. This would involve providing an interface and possibly a bundled implementation of an external library using that interface.

**Comment by ramsey** [comment]
So, my answer to @SammyK's question is: "Yes, I would like to implement CSPRINGs similar to how Facebook does it."

**Comment by SammyK** [comment]
:+1: Adding this to my "TODO" list. :)

**Comment by ramsey** [comment]
@SammyK, I may start working on some of this in the 1.0 branch. Keep your eyes on it. Also, if you make any commits to your fork that are related to this, let me know. I'd prefer not to duplicate work. :-)

**Comment by SammyK** [comment]
Sounds good! :)

**Comment by shadowhand** [comment]
@ramsey @SammyK I don't see the point in duplicating the work done by @ircmaxwell. Unlike other packages, security-related stuff should not be hot swappable, they should be well known and audited.

**Comment by ramsey** [comment]
From my perspective, we would standardize on @ircmaxell's library, but we use interfaces so that others may be injected, if desired. Perhaps we simply use RandomLib's `\RandomLib\Source` interface as our primary interface to do this.

**Comment by ircmaxell** [comment]
@ramsey I would suggest against using the `Source` interface. It's meant to be an internal implementation detail used for internal development.

Instead, the implementation that's meant to be used is `Generator`. I can extract a simple interface from that if you'd like:

    interface PRNG {
        const CHAR_* /* the char constants */
        public function generate($size);
        public function generateInt($min = 0, $max = PHP_INT_MAX);
        public function generateString($length, $characters = '');
    }

**Comment by ramsey** [comment]
Sounds great, @ircmaxell. Thanks for the feedback.

**Comment by shadowhand** [comment]
@ramsey this is done. :)
