### ISSUE TITLE
Move Providers to their own Repositories

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/oauth2-client#213]
- Eventbrite
	- [x] Find a maintainer 
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
- Facebook
	- [x] Make a new GitHub repo
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
	- [x] Document any custom params
- Github
	- [x] Make a new GitHub repo
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
	- [x] Document any custom params
- Google
	- [x] Make a new GitHub repo
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
	- [x] Document any custom params
- Instagram
	- [x] Make a new GitHub repo
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
	- [x] Document any custom params
- LinkedIn
	- [x] Make a new GitHub repo
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
	- [x] Document any custom params
- Microsoft
	- [x] Find a maintainer 
	- [x] Link in the README
	- [x] Remove from league/oauth2-client
- Vkontakte
	- [x] Find a maintainer 
	- [x] Remove from league/oauth2-client
	- [x] Link in the README

You might notice Eventbrite, Microsoft and Vkontakte have been bumped off to their own repos. That's just some advice, but maybe @ramsey you want them to stick around and be official.

**Comment by SammyK** [comment]
If #214 gets approved, this we might want to add, "Create a custom certificate bundle for peer verification," to all the providers in this list. :)

**Comment by philsturgeon** [comment]
Forgot Vkontakte is already done: https://packagist.org/packages/j4k/oauth2-vkontakte

**Comment by SammyK** [comment]
Boom! [Facebook Provider](https://github.com/thephpleague/oauth2-facebook) ready. Not sure how you want to transition removing it from this repo.

**Comment by philsturgeon** [comment]
@SammyK nice! Just whip it out of the 1.0 branch and link it in the README.

**Comment by SammyK** [comment]
I whipped it out...

**Comment by shadowhand** [comment]
I volunteer for Google, but would want it to be under the League's account.

**Comment by stevenmaguire** [comment]
If #242 is merged, we can cross Eventbrite off this punch list.

**Comment by stevenmaguire** [comment]
If #243  is merged, we can cross Microsoft off this punch list.

**Comment by philsturgeon** [comment]
@shadowhand I've made https://github.com/thephpleague/oauth2-google and you've got admin access for that along with @ramsey of course.

Consider yourself the maintainer for Google.

If you want to take up any others then let me know!

**Comment by shadowhand** [comment]
@philsturgeon :joy_cat:

**Comment by philsturgeon** [comment]
@shadowhand would you take Github, Instagram and LinkedIn? I know LI isn't the most exciting thing in the world but it would be great to get these last ones moved out.

I'll make any repos for providers you claim.

**Comment by stevenmaguire** [comment]
I am happy to help.

**Comment by philsturgeon** [comment]
Lay claim!

**Comment by stevenmaguire** [comment]
I will take LinkedIn, since it isn't as exciting. If @shadowhand does not take the others, I don't mind. These projects are not highly complicated to maintain. 

Will LinkedIn need a League repo? If so, please set it up and let me know. I will happily take care of this.

**Comment by philsturgeon** [comment]
@stevenmaguire here you go! https://github.com/thephpleague/oauth2-linkedin

**Comment by philsturgeon** [comment]
keep the others as third party, but linked in can be an official one.

**Comment by stevenmaguire** [comment]
Sweet. I am on it.

**Comment by stevenmaguire** [comment]
LinkedIn custom params documentation should be taken care of now. 

https://github.com/thephpleague/oauth2-linkedin

I only focused on the `scopes` param, as they are definitely a corner case for typical usage. The `fields` param is accessible, but appears to only support hydrating the generic user object, so encouraging usage that is different from the default may not be needed in the documentation right now.

**Comment by shadowhand** [comment]
@stevenmaguire thanks for taking Instagram and LinkedIn... I wasn't keen on taking ownership of providers that I don't actively use.

**Comment by stevenmaguire** [comment]
I haven't taken Instagram; only LinkedIn. I accept your nomination however, intentional or not ;)

@philsturgeon could you create a repo for Instagram and set me up as an admin? I will maintain that package as well.

**Comment by shadowhand** [comment]
@stevenmaguire oops, I thought I could create it for you, but I don't have permissions to set up the team properly. https://github.com/thephpleague/oauth2-instagram @philsturgeon can you fix the permissions please?

**Comment by philsturgeon** [comment]
@stevenmaguire you have access now.

**Comment by philsturgeon** [comment]
@shadowhand @stevenmaguire could you two look into updating the oauth2-client documentation to match what Omnipay has done?

http://omnipay.thephpleague.com/gateways/official/
http://omnipay.thephpleague.com/gateways/third-party/
http://omnipay.thephpleague.com/gateways/build-your-own/

**Comment by stevenmaguire** [comment]
I still only have read access to https://github.com/thephpleague/oauth2-instagram

**Comment by shadowhand** [comment]
@philsturgeon can you update the task description so that we know where we're at?

**Comment by shadowhand** [comment]
@philsturgeon where would I update the documentation for oauth2-client? I did a quick search and couldn't find any matching repos...

**Comment by stevenmaguire** [comment]
@shadowhand PR #248 includes some updates to the documentation that includes the tabular format for official and third party providers. This PR will merge into the 1.0 branch. It was discovered that the oauth2-client does not have a website on the League website. There is now an issue for that.

**Comment by philsturgeon** [comment]
@shadowhand I don't know what you lot have done so let me or @ramsey know what to update. 

Documentation will go in a gh-pages branch when @ramsey gets around to it, as part of 1.0.

**Comment by stevenmaguire** [comment]
@philsturgeon 

LinkedIn -> `Document any custom params` is complete.
Instagram -> Code is ready to commit to new repo then `Remove from league/oauth2-client` can be done. I need admin/write access to repo.

**Comment by philsturgeon** [comment]
@stevenmaguire can you PR instagram removal from oauth2-client?

**Comment by stevenmaguire** [comment]
@philsturgeon I sure can. I'd like to be sure that the code exists in its new home also.

**Comment by stevenmaguire** [comment]
#251 is in!

**Comment by stevenmaguire** [comment]
@philsturgeon could you please promote me to an admin for the oauth2-instagram repository? I have code for that project; it's currently empty!

**Comment by philsturgeon** [comment]
Done!

**Comment by stevenmaguire** [comment]
Moved!

**Comment by stevenmaguire** [comment]
Would you like me to take care of Github to close out the punch list?

**Comment by ramsey** [comment]
@stevenmaguire That would be great!

**Comment by stevenmaguire** [comment]
It appears to be a League sanctioned repo. Can you create the repo and set me up with permissions?

**Comment by ramsey** [comment]
@stevenmaguire I think @philsturgeon will need to create the repo.

**Comment by philsturgeon** [comment]
Done! https://github.com/thephpleague/oauth2-github

**Comment by stevenmaguire** [comment]
PR is in for Github #261

**Comment by ramsey** [comment]
There are no longer any third-party providers in the 1.0 branch. Woooo!

**Comment by stevenmaguire** [comment]
![party](http://axisofstevil.s3.amazonaws.com/stuff/burgerdown.gif)
