### ISSUE TITLE
Guzzle version

### ISSUE THREAD

**Issue by msimkunas** [thephpleague/oauth2-client#215]
Are there any plans to update this package to a newer version of Guzzle?

**Comment by philsturgeon** [comment]
Yes indeed! Already done in the 1.0 branch.

https://github.com/thephpleague/oauth2-client/blob/1.0/composer.json#L7

**Comment by msimkunas** [comment]
Thanks for the quick response. I had _mistakenly_ concluded to myself that the 1.0 branch was an older version of this package.

**Comment by msimkunas** [comment]
I have a question though. How do I install the 1.0 branch using composer? The branch alias seems to be the same in both branches.

**Comment by ramsey** [comment]
Please don't use the 1.0 branch yet in production. We will be making breaking changes to it, and I don't want to cause you headaches. :-)

**Comment by msimkunas** [comment]
Would you recommend installing the Guzzle 5.0 package separately? I don't really like the idea of having two different versions of it, but if that's the only way to go for the time being, so be it.

**Comment by philsturgeon** [comment]
Just let the packages use whichever versions of Guzzle they want to use. It's much safer to have two packages using two different versions of Guzzle than it is to deploy a non-released development version. :)

**Comment by ramsey** [comment]
Guzzle changed their namespace between versions to accommodate this use case. Just let Composer install what it installs, as Phil said. :-)

**Comment by msimkunas** [comment]
Alright, thanks for clarifying. I was hoping there was a way to use a single package version, but the way you put it seems to be the way to go.
My only issue with this is that I may have to rewrite my custom OAuth 2 provider in the future. Will there be an upgrade process available?

**Comment by ramsey** [comment]
We have quite a few third-party providers, and we're splitting out all the providers into individual packages for v1. So, yes, we'll need to provide an upgrade path to ensure things do not break the providers.

**Comment by msimkunas** [comment]
Thank you for the quick response.
