### ISSUE TITLE
How do I request other API endpoints

### ISSUE THREAD

**Issue by jenssegers** [thephpleague/oauth2-client#222]
I don't know if I am missing something, but I can't seem to find out how to request other API endpoints than the user information.

**Comment by philsturgeon** [comment]
The OAuth 2 client is just for oauth 2 clienting. It happens to hit their API, but other than that you're on your own.

All you need to do is grab the OAuth 2 token and put it in the header when you're making your Guzzle requests.

**Comment by jenssegers** [comment]
Doesn't this kind of defeat the purpose of being an "oauth2 client"?

**Comment by tpavlek** [comment]
OAuth2 is an authentication schema, not an API. If we were hitting the API
lots we'd call it an "API client".

**Comment by jenssegers** [comment]
Alright, I rest my case :)

**Comment by philsturgeon** [comment]
Use the OAuth2 Client for your OAuth 2 interactions (get token, refresh token, etc) then use a HTTP Client for your HTTP interactions. 

You just need to slap ?access_token in the query string, or Authorization: Bearer <token> in the header.

You don’t want us to make another HTTP Client, because Guzzle is already extremely good.

**Comment by philsturgeon** [comment]
Sorry, my email client was busted and I didn't see you say "I rest my case" when I replied.

**Comment by shadowhand** [comment]
I think that #232 will go a long way towards addressing this issue. I propose this be reopened and resolved through documentation. For instance, here is a snippet of code I was able to use with my pull request applied:

```php
public function get($url)
{
    $headers  = $this->client->getHeaders($this->getToken());
    $request  = $this->client->getHttpClient()->get($url, $headers)->send();
    $response = $request->getBody();

    return json_decode($response);
}
```

This code exists inside of a trait that I can use with any oauth2-client provider, reusing the internal clients, headers, etc. I have similar methods for `POST`, `PUT`, etc.

**Comment by jenssegers** [comment]
For a project of mine I did something similar. I created a trait that added a `request` method, but because none of the providers have a base api url, I had to extend every provider and add it.

My method looked something like:

	public function request($endpoint, $method = 'GET', $body = null, array $headers = null)
	{
		try
		{
			$accessToken = $this->retreiveAccessToken();

			$uri = $this->urlApi(ltrim($endpoint, '/'), $accessToken);

			$client = $this->getHttpClient();

			if ($this->headers)
			{
				$headers = array_merge($this->headers, $headers ?: []);
			}

			$request = $client->createRequest($method, $uri, $headers, $body);

			$response = $client->send($request)->getBody();
		}
		catch (BadResponseException $e)
		{
			// TODO
		}

		return $response;
	}
