### ISSUE TITLE
Invalid server response crashes client.

### ISSUE THREAD

**Issue by reenl** [thephpleague/oauth2-client#230]
Hi,

If the client connects to a server that gives an invalid response, the client crashes.

```
Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResult() must be of the type array, null given, called in .../oauth2/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 218 and defined in .../oauth2/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 230
```

If you consider this a bug I would be happy to create a pull request.

**Comment by ramsey** [comment]
What are you proposing as a fix for this?

**Comment by ramsey** [comment]
Ping, @reenl.

**Comment by vimishor** [comment]
@ramsey I proposed a solution in PR #236 .

**Comment by reenl** [comment]
Hi sorry for not responding, somehow I did not get notifications for this, I'll check my settings. Thanks @vimishor
