### ISSUE TITLE
User Entity cannot be set

### ISSUE THREAD

**Issue by marcojanssen** [thephpleague/oauth2-client#237]
The User Entity for all the providers are tightly coupled and have no way to be injected or set when retrieving the user details. The only way now is to inherit the provider in our own concrete and override the method, which is not something i prefer.

```
public function userDetails($response, AccessToken $token)
    {
        $user = new User();

        $email = (isset($response->emailAddress)) ? $response->emailAddress : null;
        $location = (isset($response->location->name)) ? $response->location->name : null;
        $description = (isset($response->headline)) ? $response->headline : null;
        $pictureUrl = (isset($response->pictureUrl)) ? $response->pictureUrl : null;

        $user->exchangeArray([
            'uid' => $response->id,
            'name' => $response->firstName.' '.$response->lastName,
            'firstname' => $response->firstName,
            'lastname' => $response->lastName,
            'email' => $email,
            'location' => $location,
            'description' => $description,
            'imageurl' => $pictureUrl,
            'urls' => $response->publicProfileUrl,
        ]);

        return $user;
    }
```

In case of LinkedIn there are more user details we can extract when a r_fullprofile scope is provided.  Are there plans to implement this and if not what are your thoughts about how to implement it? We could add it in the abstract provider but i prefer a seperate object for it.

Will free up some time, if needed, to implement it.

**Comment by marcojanssen** [comment]
As an alternative we can also allow the response or the extra fields to be set in the User entity.

**Comment by ramsey** [comment]
Good recommendation about the User. I'll add this to the 1.0 milestone. If you do submit a pull request for it, be sure to do it against the 1.0 branch.

Thanks!

**Comment by kevindierkx** [comment]
May a suggest the way illuminate/database handles it's [model](https://github.com/illuminate/database/blob/master/Eloquent/Model.php) attributes, it's using a clean way to access dynamic attributes in both an array and object manner. Give me a heads up if you would like me to implement something like it.

**Comment by ramsey** [comment]
How does illuminate/database handle it's model attributes?

**Comment by kevindierkx** [comment]
In a nutshell. During creation of the model using the ```__construct``` or after a query call it utilises the ```fill()``` method provided in the model to fill the ```$attributes``` property. This in turn is used with the ```__get()``` and ```__set()``` methods.

**Comment by marcojanssen** [comment]
Might be worth a try, was thinking of setting a dynamic path and then map the objetc towards that

**Comment by kevindierkx** [comment]
I'll make a fork this evening (GMT+0001). ;)

**Comment by marcojanssen** [comment]
@kevindierkx If you need some help, give me a ping

**Comment by kevindierkx** [comment]
Just a heads up, I was working on this last night but I stumbled against some authorization issues accessing the user details. Most likely a small issue with the request, I have it working with an older version of this package. The current implementation of the HttpAdapters makes it a bit of a pain to get the raw request. @marcojanssen Any tips on getting the raw request?

**Comment by marcojanssen** [comment]
@kevindierkx not sure what you mean, could you give me a better example of your problem?

**Comment by kevindierkx** [comment]
@marcojanssen  I'm having problems with the Authorization headers, my testing backend won't recognise the Authorization header. Older installations of the oauth2-client don't have this problem. I'm still trying to pinpoint the exact problem and cause.

**Comment by GawainLynch** [comment]
@kevindierkx I was looking at this over the weekend and ran out of time. One thing I did notice was that the `grant_type` that gets set in `AbstractProvider::getAccessToken()` doesn't seem to get cast to a string somewhere in the provider resulting (for me at least) in an invalid Authorization header.

That's about where I stopped looking.

**Comment by kevindierkx** [comment]
@GawainLynch Well that could explain why the authorization server can't authenticate. Will take a look, thanks!

**Comment by kevindierkx** [comment]
@marcojanssen @GawainLynch After some debugging using the default curl adapter I've noticed the headers are set in a 'headers' header.

Does anyone know why this could happen?
```
[2015-04-09 19:51:47] local.DEBUG: array (
  'AUTHORIZATION' => '',
  'HOST' => 'api-pcx.dev',
  'ACCEPT' => '*/*',
  'HEADERS' => 'application/vnd.pcextreme.v1+json, Bearer WrdB4mtYIfge9Us4Z1wcyCkwYuuERUFy8LKBBdvL',
  'CONNECTION' => 'close',
  'USER_AGENT' => 'Ivory Http Adapter 0.6.0',
) [] []
```

**Comment by kevindierkx** [comment]
@marcojanssen @GawainLynch Got it! The ```fetchProviderData()``` method in the ```AbstractProvider```  class is using the ```get()``` method from http adapter client. This is fine but the second parameter expects an array of headers. The ```AbstractProvider``` provides an associative array adding all headers under a ```headers``` key. This breaks authentication with my testing backend. Making a pull request as we speak.

**Comment by GawainLynch** [comment]
Awesome stuff @kevindierkx

**Comment by marcojanssen** [comment]
@kevindierkx ah that was the problem, nice

**Comment by ramsey** [comment]
Please take a look at #265 and offer any feedback, questions, etc. Thanks!

**Comment by ramsey** [comment]
I removed the User entity in #267 (see also discussion in #265). There is now a `Provider\UserInterface` for providers to use.
