### ISSUE TITLE
AbstractProvider::getAccessToken has no default response type

### ISSUE THREAD

**Issue by mastermike14** [thephpleague/oauth2-client#249]
this can cause an issue when the response type isnt equal to 'json' or 'string'. For example ive been using this for the Trakt.tv API and the response doesn't match either of the two which causes a NULL response to be returned.

**Comment by ramsey** [comment]
Can you provide an example of how Trakt.tv responds?

This seems related to my thoughts on #256 about providers not following the OAuth2 spec.

**Comment by ramsey** [comment]
@mastermike14, ping. Can you provide an example, please?

**Comment by parsnick** [comment]
I think this is the same issue - FreeAgent API is returning an uppercase "JSON" responseType, leading to "result is not defined" error.

Could this check be made case insensitive and/or default to something?

**Comment by ramsey** [comment]
@parsnick Can you please show an example of the full response? Thanks!

**Comment by parsnick** [comment]
Apologies, looking into this further I've found the provider was configured (on our end) with responseType JSON, when it should have been lowercase.

I was initially confused by the case sensitivity in [Provider/AbstractProvider.php:L229](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L229), thinking the API must be responding with `Content-Type: application/JSON`, but not the case. Please disregard.

**Comment by ramsey** [comment]
Thanks for letting me know.
