### ISSUE TITLE
Official oauth2-client website

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-client#250]
We need one.

**Comment by ramsey** [comment]
@philsturgeon, is there a standard format or template for League gh-pages websites?

**Comment by philsturgeon** [comment]
I completely forget how it works, but @reinink is the man to ask. 

Lets get something up on the wiki.

**Comment by reinink** [comment]
> is there a standard format or template for League gh-pages websites?

Yep, you can find the instructions [here](https://github.com/thephpleague/theme.thephpleague.com).

> Lets get something up on the wiki.

Good call, will do!

**Comment by ramsey** [comment]
I've got the basic stub up in the `gh-pages` branch now. http://thephpleague.com/oauth2-client/

**Comment by reinink** [comment]
Nice. Easy enough?

**Comment by tpavlek** [comment]
Why is this site a subdirectory of thephpleague where all other projects
are subdomains?

On Tue, Mar 24, 2015 at 1:49 PM, Jonathan Reinink <notifications@github.com>
wrote:

> Nice. Easy enough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-client/issues/250#issuecomment-85665974>
> .
>



-- 
Troy Pavlek.
Crayon Connisseur and Respected Gentleman.

**Comment by reinink** [comment]
That's just the default GitHub Pages behaviour. We'll get the subdomain setup later.

**Comment by ramsey** [comment]
It was easy enough.

**Comment by tpavlek** [comment]
Has anyone begun tackling this yet? I have some open source cycles coming up, and if no one's already working on this I'd love to make us some docs :)

**Comment by rtheunissen** [comment]
I think we're just waiting for the API to be finalised. See [timeline](https://github.com/thephpleague/oauth2-client/wiki/v1.0.0-Release-Time-Table)

**Comment by x-merlin-x** [comment]
A documentation would be very helpful. I am now struggling with the package for a few hours and can't find out how to start. The readme.md usage section does not help and I am close to giving up.

**Comment by shadowhand** [comment]
@x-merlin-x having chatted with you on Gitter, I feel like you don't understand what you want to do. The current documentation isn't great, but it is enough to get most people started without too much trouble.

**Comment by x-merlin-x** [comment]
@shadowhand thank you for your reply. I am sorry but I do know what I want: 1. Get the example running in readme.md with facebook, 2nd connect to my own Oauth2 server. The first point already failes as the only documentation I can find is readme.md and to implement my own provider for step 2 readme.provider-guide.md. The example in readme.md for facebook seems to be incomplete as there are no includes or requires that load the library. Therefore I receive a Fatal error: Class 'League\OAuth2\Client\Provider\Facebook' not found

**Comment by ramsey** [comment]
You should take a look at the Facebook provider.

There is a link to a list of providers in the README. The list is here: https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md

**Comment by shadowhand** [comment]
@x-merlin-x I'm not sure what you mean by "connect my own OAuth2 server". You can either use an OAuth client to connect to a 3rd party (like Facebook) /or/ you can have your own OAuth server and use an client to connect it.

**Comment by tpavlek** [comment]
I submitted a pull containing a starting point in #404
