### ISSUE TITLE
Cleaner way to throw InvalidArgumentException

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [thephpleague/oauth2-client#253]
I think it's a bad idea to use print_r() directly to append the exception message. In my application, I have to use explode and extract the error message such as **This_authorization_code_has_expired_** rather than directly getting it.
https://github.com/thephpleague/oauth2-client/blob/6930258/src/Token/AccessToken.php#L38-L41

**Comment by ramsey** [comment]
That is indeed odd. Adding it to the 1.0.0 list. Thanks for reporting this!

**Comment by shadowhand** [comment]
@ramsey this can be closed.
