### ISSUE TITLE
Move to guzzle 5

### ISSUE THREAD

**Issue by jelkevdh** [thephpleague/oauth2-client#260]
Installing this client I get the message that Guzzle 3 is deprecated.
Is it an idea to see if an up-to-date version of Guzzle can be supported?
<code><pre>composer require league/oauth2-client
Using version 0.10.* for league/oauth2-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzle/guzzle (v3.9.3)
    Downloading: 100%         

  - Installing league/oauth2-client (0.10.1)
    Downloading: 100%         

guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
</pre></code>

**Comment by ramsey** [comment]
We are moving to Guzzle 5 for the 1.0 release. The 0.x releases will remain on Guzzle 3.

Thanks!
