### ISSUE TITLE
[RFC] Provider User Entity Interface/Abstract

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-client#265]
OAuth 2.0 does not define a User entity. However, we're providing an `Entity\User` class in this library. As a result of how various providers handle users and user data, we've had to modify this class numerous times to support each provider. Now that there are no more providers in version 1.0, it no longer makes sense to support a User entity that works for all the providers.

My recommendation is to remove `Entity\User` in v1.0. In its place, we should provide a basic `Provider\UserInterface` and possibly an abstract `Provider\User` with bare-bones functionality. Each provider will need to upgrade to use at least the interface by the v1.0 release. The management of user entities will now be the responsibility of each provider.

We should get feedback from each of the third-party providers for what the `Provider\UserInterface` should include.

Refer to #237 and #264 for more discussion on this topic.

**Comment by kevindierkx** [comment]
I would suggest only supplying the bare minimum being: user_id, nickname, email, name (combination of first_name and last_name) and maybe an avatar.

**Comment by marcojanssen** [comment]
@kevindierkx Bare minimum is in some cases not sufficient. If o authorized against a provider and i know and need the data that they provide, why wouldn't we provide acces to it?

https://github.com/hwi/HWIOAuthBundle
Uses paths for each different provider to get the required info

**Comment by ramsey** [comment]
Please think of the "bare minimum" as the minimum needed for an interface that fits all providers. If there are outliers, these may be used in the provider-specific user entities themselves, even if the interface does not support them.

**Comment by kevindierkx** [comment]
@marcojanssen I was talking about the UserInterface provided in the base package, the specific providers can add whatever they want in my opinion. They could even create a separate interface for those situations.
I don't think the base package should include a primaryContacts getter and setter in the UserInterface just because my API supplies one.

**Comment by ramsey** [comment]
Sorry for the spam, but I'd like feedback from all the third-party provider maintainers, so I'm going to mention you all here. :-)

@SammyK @stevenmaguire @shadowhand @tpavlek @jasonvarga @zot24 @JC5 @rakeev @howlowck @deminoth @j4k

**Comment by SammyK** [comment]
Bare minimum: `user_id`. I don't think we can make any more assumptions other than that. :)

For example, Facebook provides [anonymous login](https://developers.facebook.com/products/anonymous-login/) which only gives you a token that ID's a user until they choose to use normal login.

**Comment by ramsey** [comment]
So, we're looking at an interface that looks a bit like this right now:

``` php
namespace League\OAuth2\Client\Provider;

interface UserInterface
{
    public function setUserId($id);
    public function getUserId();
}
```

I won't try to enforce what the constructor looks like. That may be left up to the individual implementations. This just needs to be the bare minimum that should be expected on any provider user object.

Anything else?

**Comment by SammyK** [comment]
I'd say the User entity needs to be immutable since there is no save functionality on the entity (as in update the user entity on the origin site). So I'd kill `setUserId()` and just have all the user data injected into the constructor.

**Comment by ramsey** [comment]
That sounds reasonable. I agree.

**Comment by tpavlek** [comment]
Sorry I haven't been too active in this discussion, since it does actively affect me.

All of my use-cases require a toArray function on the Entity object, and to that end, I would like to see it on the interface. I think if we're providing a default Abstract implementation of this interface (we should) it could simply `get_object_vars` and be done with it. Makes it easier to reason about what fields you *actually* have if you're dealing with dynamically switching out Entities in providers.

**Comment by SammyK** [comment]
> All of my use-cases require a toArray function on the Entity object

A `toArray()` method doesn't have any relation to a user entity so to keep things "single responsibility" is shouldn't be on the `UserInterface`.

If you need `toArray()` it should be on a `Collection` class or something that manages data in a very general way. Then you could do this on your user entity:

```php
class User extends Collection implements UserInterface
{
    public function getUserId() {}
}
```

Perhaps we could provide a base `Collection` class (or trait even) in the OAuth 2.0 Client for this case?

**Comment by ramsey** [comment]
I'd rather not get too complicated in providing a base `Collection` class. Again, that's out of scope of OAuth2. :-)

I think perhaps `UserInterface` could extend `IteratorAggregate`, though. This would force everyone implementing `UserInterface` to also implement the `getIterator()` method. But, like @SammyK mentioned, would all the providers need this functionality?

**Comment by tpavlek** [comment]
@sammy Eeeeeeh, I don't want to start an internet argument here, but that
just seems a bit pedantic to me. Whether we acknowledge it or not,
pragmatically this class is going to be used as a data blob. People are
going to be setting properties in the constructor and then using public
getters to get it. Functionally the class is just an array by another name.

I'm not necessarily opposed to inheritance but it adds a lot of complexity
for no real gain other than a check mark for purity.

**Comment by ramsey** [comment]
@tpavlek How do you feel about `getIterator()`. You could even have it return `new ArrayIterator($this)` to iterate over all the public properties, and you can call `getArrayCopy()` on that object to accomplish your `toArray()`.

The only problem I have with this is that I don't necessarily think every provider will want to treat their User model as an array, so that's why I want to hear from everyone on how they intend to use it.

**Comment by SammyK** [comment]
> I'd rather not get too complicated in providing a base Collection class. Again, that's out of scope of OAuth2. :-)

So if offering a `UserInterface` and `User` entity. :) If you want to be really basic, just return a plain-old PHP array and let the user dump it into their framework's `Collection` object. That's not a bad idea actually... :)

> perhaps UserInterface could extend IteratorAggregate

I'm :+1: for this if we still want to go down the `User` entity support.

> I don't want to start an internet argument here

Too late! :) Just kidding.

> Functionally the class is just an array by another name

I totally agree. That's why I think `getUserId()` is all we need and leave it up to the providers to add getter methods galore if they want to. But then again, a plain old PHP array is sounding a lot better for this lib.

**Comment by ramsey** [comment]
Are the providers the only things using this User object? Is there any need to use it internally in the base oauth2-client? Will end-users integrating with each provider need the ability to easily swap back-and-forth between User objects from various providers?

If so, then we do need to enforce some sort of contract. If not, removing it entirely from oauth2-client is preferred, and we let each provider handle it separately.

**Comment by shadowhand** [comment]
I agree that this should be the complete interface:

```php
interface UserInterface
{
    public function getUserId();
}
```

Regarding the `toArray` method, I've mentioned before that I would like to see a `league/common` package that provides a number of common reusable traits, but I don't think this needs to be addressed within the scope of this issue.

**Comment by SammyK** [comment]
> Is there any need to use it internally in the base oauth2-client?

Facebook for example doesn't return a user ID with the access token so having a `UserInterface` with just `getUserId()` is still useless at that point in the OAuth flow.

> Will end-users integrating with each provider need the ability to easily swap back-and-forth between User objects from various providers?

Maybe, but that sounds like a "Open ID login" edge case. The more I think about it the more I like just having it poop out an array and letting the user do what they wish with it. Otherwise we could be putting up barriers trying to accommodate the edge cases and power users.

**Comment by tpavlek** [comment]
I accept that I'm in the minority here, and I'll just add toArray to my objects downstream :).

Re: Removing the object altogether, that sounds like a very **bad idea** to me. `getUserId()` is important because different providers return different things as the "id", and it's important to be able to specify that. If we don't allow users to specify it here, we'll need to make some method on the Provider to handle setting User "array" id field, which also seems like a separation of concerns issue, and definitely sounds like the greater evil compared to including this interface.

**Comment by SammyK** [comment]
> different providers return different things as the "id"

Indeed!

> If we don't allow users to specify it here, we'll need to make some method on the Provider to handle setting User "array" id field

Why does the library need to know the user's ID? It shouldn't care about user data & just mindlessly return an access token, correct? At that point the developer can use `file_get_contents()` or their fav HTTP client to grab info using the access token.

A lot of times the developer might not even need any info on the user. I've had many cases where a user would authenticate their account just so the app could grab the user's events they are going to for example.

Or what if I only want to grab the user's "relationship status"? Right now the OAuth 2.0 Client will make a request to gather basic info on the user and then not even give me what I want so I have to make another request to get the desired data.

I'd say rip out all that stuff and leave it up to the developer to get what they want once they obtain an access token. That's what OAuth 2.0 is all about anyways. But if enough people think it should be left in, that's cool too - I'm easy to please. :)

**Comment by shadowhand** [comment]
@SammyK I have to agree with @tpavlek on this one, having the `getUserId` method is very useful for token storage, because it provides a consistent __interface__ for storage of tokens before moving out to a layer where we are making calls. It just helps with separation of concerns and that is a Good Thing™.

**Comment by tpavlek** [comment]
@SammyK  That's a slippery slope argument - why doesn't the user just use guzzle and craft the OAuth 2 flow themselves? Obviously an exaggeration, but the point stands.

Meanwhile we get people dropping issues in here and on provider packages saying "Why doesn't this implement calling the API". I don't think end users of this package are looking for features to be stripped away in the name of "single-responsibility". My vote is for keeping the UserInterface, and its single method.

**Comment by SammyK** [comment]
> having the getUserId method is very useful for token storage

Indeed! But only if you care about the user node. As I alluded to earlier, not all OAuth flows focus on the user who is authenticating (although probably most are). :)

> Obviously an exaggeration, but the point stands. [...] I don't think end users of this package are looking for features to be stripped away in the name of "single-responsibility".

My point about dropping the User entity isn't about single-responsibility. It's more about @ramsey's concern of keeping the lib focused on OAuth 2.0 Client flow only. There's nothing in the OAuth 2.0 flow that says you have to grab x, y & z info for a user once you obtain an access token. So if we're being struct about OAuth 2.0, then User entity should be removed. No slippery slope argument there. :)

But if the idea behind OAuth 2.0 Client is to provide OAuth 2.0 flow + some handy helpers to make things easier for 80% of all cases, then we certainly need to keep the User entity. :) We just need to be explicit in the lib's goals.

**Comment by ramsey** [comment]
I don't plan to "go all Stalin" on anyone. I'm just working on shepherding a good package, and I want something that makes it easy for anyone to build a provider against. :-)

**Comment by stevenmaguire** [comment]
As a philosophy, I am in favor of reducing the responsibility of this package to its essential needs. The important question that I see here has been most recently articulated by @SammyK. 

- Does the package include, beyond authentication and token management, an essential need to support a select list of additional data access helpers? 
 - If so, does the select list need to be amended to include more ore less?

Honestly, I could go either way; I see value in both positions. My vote on implementation will hinge directly on clarifying the goals of the package (if they are even in question)?

**Comment by ramsey** [comment]
IMO, the goal of the library should be to provide a full-fledged RFC 6749 compliant OAuth 2.0 client.

This includes supporting the following authorization types:

* Authorization Code Grant
* Implicit Grant
* Resource Owner Password Credentials Grant
* Client Credentials Grant
* Extension Grants (through extension of this library—not internal to the library)

The library should provide an out-of-the-box provider that may be used with any OAuth 2.0 server that adheres to RFC 6749. This provider may be configured upon instantiation by passing all necessary endpoint URLs, etc. into the provider, and then calls for authorization and access tokens may be made to it. (see also #179)

Third-party provider libraries may base themselves on this out-of-the-box default provider, or if they drift too far from the OAuth 2.0 spec, they may adhere to a provider interface. As each provider supports varying degrees of the OAuth 2.0 specification (for example: supporting only one or two authorization types, varying authentication schemes, disparate error responses, etc.), the library must provide easy extension to allow third party provider libraries the flexibility needed to target a variety of OAuth 2.0 servers, handling their responses however varied they may be.

Since OAuth 2.0 does not define access token types (i.e. Bearer, MAC), this library must also be flexible enough to be extended to provide support for different access token types.

How's that for a manifesto?

If all providers will always need some sort of User object, then providing an interface for that User object makes sense to me. If the User, however, is an API implementation detail for some providers but not for others, then maybe we need to leave it up to the individual providers.

This is why I'm asking here. I'm not strongly in favor of ditching the `UserInterface`; I could go either way.

**Comment by SammyK** [comment]
> How's that for a manifesto?

Nice! :)

Just a few more thoughts to consider regarding simple & easy (inspired by @weaverryan's talk at SunshinePHP a few months ago).

From a strategic standpoint, the current docs show how to obtain data on the authenticated user:

```php
// Get the user node as a User entity
$userDetails = $provider->getUserDetails($token);
```

It's easy. You don't need to know what goes on behind the scenes for that to work. But it's not simple. There's a lot of grunt work going on to make that one-liner work.

By contrast, this is simple, but not necessarily easy:

```php
// Get the user node as a JSON string
$response = get_file_contents('https://graph.facebook.com/v2.3/me?fields=id,name,email&access_token='.$token);

$userDetails = json_decode($response, true);
```

The second option explains to the user right out of the box how to make requests to this specific provider's API. In this simple example we learn:

1. The Facebook API lives at https://graph.facebook.com
2. The API is versioned in the URL (v2.3)
3. Access tokens are appended to the URL with the `access_token` param.
4. Responses from the Graph API are JSON strings.

And the developer can take that knowledge further and do more complicated things that aren't even user-profile specific:

```php
// Get a list of events
$response = get_file_contents('https://graph.facebook.com/v2.3/me/events?access_token='.$token);
```

The problem with the User entity is that it's got a great 5-min experience but doesn't give you any cues as to how to take your needs to the next level with that specific provider.

**Comment by shadowhand** [comment]
@SammyK you bring up a really good point here, and I'd like to take it a step further:

One of the things that always bothered me about this library (and am moving towards solving with #232) is that it doesn't do very much to make **using** the provider APIs easier, it only gets us to the point of having an authenticated token.

I'll be very clear here and say that **the goal is not to create API wrappers** with providers. However, I think a very valuable part of this package is that it makes it **easier to use provider APIs** and so any changes we are proposing here should keep that in mind.

To this end, what are valuable things this package can do to make API usage easier?

1. Ensure that providers contain a method to fetch an API base URL. This is not very useful by itself, but it makes writing multiple API calls much DRYer.
2. Ensure that providers contain a method to add authentication to a request. This is what #232 did (see also league/oauth1-client#18) and it immediately improved the code I was working on that made API calls.
3. Provide ways to integrate more cleanly with dependent packages. The client already uses Guzzle, so it should expose methods that work with those classes. For instance, having a method like this would save a lot of repeated code:

```php
/**
 * Create an authenticated client to access an API URL.
 *
 * @param  string $method
 * @parma  string $path
 * @param  AccessToken $token
 * @return Guzzle\Http\Client
 */
public function getAuthenticatedClient($method, $path, AccessToken $token);
```

This would allow us to write code like:

```php
$response = $client->getAuthenticatedClient('GET', 'me', $token)
    ->setDefaultOption('query/fields', 'id,name,email')
    ->getResponse();
$me = $response->json();
```

Personally I would find this to be a *very* useful and complete example of how to build upon what the package provides and represents best practice.

**Comment by stevenmaguire** [comment]
+1 @shadowhand 

I like the idea of an authenticated client. It is a mixture of education and helpfulness, while removing the need to assert our entity expectations on the possible use cases the consuming vendor specific providers may encounter.

**Comment by tpavlek** [comment]
+1 @shadowhand 

Though that should definitely return a `ClientInterface` ;)

**Comment by shadowhand** [comment]
@tpavlek fixed. ;)

**Comment by ramsey** [comment]
It sounds like `getAuthenticatedClient()` would just return a Guzzle client with the authentication headers/token already injected, right? So, I'm not sure we would need our own `ClientInterface`, unless we want to provide the ability for others to inject their own HTTP clients (that aren't Guzzle), but as I recall, that's what #224 did for us.

**Comment by tpavlek** [comment]
@ramsey Guzzle has a ClientInterface. I meant to return that.

**Comment by ramsey** [comment]
We're technically not using Guzzle. We're using https://github.com/egeloen/ivory-http-adapter.

**Comment by shadowhand** [comment]
@ramsey ah yes, I forgot about that. In which case, we'd be using `RequestInterface`. I'll update my example.

**Comment by stevenmaguire** [comment]
With @shadowhand solution in mind, would this package still support the following by requiring implementation of abstract method, then encourage implementers to use the `getAuthenticatedClient` method and return any payload they like for their vendor?

```php
// Get the user node as a User entity
$userDetails = $provider->getUserDetails($token);
``` 

Is it any of our business to have an opinion about that?

**Comment by tpavlek** [comment]
Frankly, I think we're getting off topic. I like the authenticated client idea, but I do **not** think it's mutually exclusive with the UserInterface, and I still think we should keep that.

I move we make a new RFC for returning authenticated clients.

**Comment by ramsey** [comment]
@shadowhand If you want to go ahead and do a PR for the authenticated clients, we can use that as our "RFC" for discussion, or you can just open an issue. Your call. :-)

**Comment by shadowhand** [comment]
> Frankly, I think we're getting off topic. I like the authenticated client idea, but I do not think it's mutually exclusive with the UserInterface, and I still think we should keep that.

Agreed. :) I plan on doing a PR for this in the near future, just haven't had time.

**Comment by SammyK** [comment]
:+1: For authenticated client! :)

The authenticated client will remove the need for a User entity altogether unless you guys have a really good use case where it's needed. :)

**Comment by ramsey** [comment]
@shadowhand I went ahead and opened an issue, so that I don't forget to nag you about that PR. ;-)

**Comment by shadowhand** [comment]
@ramsey thanks!

**Comment by ramsey** [comment]
Should I keep this open much longer for feedback from others, or are we all content with the interface as it's defined in #267?

**Comment by shadowhand** [comment]
:+1: from me.

**Comment by stevenmaguire** [comment]
:+1:

**Comment by tpavlek** [comment]
One more thing I'd like to ask is if we're all collectively content with the `UserInterface` name. Since I typehint interfaces, not concretions, I'd prefer to have the interface actually named `User`. Anyone else have thoughts?

**Comment by shadowhand** [comment]
@tpavlek I completely understand this request, but it doesn't match up with the rest of the interfaces defined within this package. I would suggest that we keep `UserInterface` for consistency. You can always alias it locally:

```php
use League\OAuth2\Client\Provider\UserInterface as User;
```

**Comment by ramsey** [comment]
As this isn't something that PSR-1 or PSR-2 cover, I've been trying to adhere to the Symfony coding standards, since they are well-defined in this respect:

http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

**Comment by tpavlek** [comment]
I was unaware there was a standard being followed.

Since this is consistent with that it gets the :+1:  from me :)

**Comment by ramsey** [comment]
Excellent. Merging in!

**Comment by stevenmaguire** [comment]
![haters](http://axisofstevil.s3.amazonaws.com/stuff/haters.gif)
