### ISSUE TITLE
[RFC] ProviderInterface::getAuthenticatedRequest() method

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-client#268]
This would give users of Providers a method that returns an already-authenticated HTTP client, using the token retrieved in the OAuth 2.0 flow. They may then use this client object to make authenticated requests of whatever provider API they are using, without the OAuth 2.0 Provider classes becoming API wrappers.

From @shadowhand in the comments on https://github.com/thephpleague/oauth2-client/issues/265#issuecomment-94943566:

> One of the things that always bothered me about this library (and am moving towards solving with #232) is that it doesn't do very much to make **using** the provider APIs easier, it only gets us to the point of having an authenticated token.
> 
> I'll be very clear here and say that **the goal is not to create API wrappers** with providers. However, I think a very valuable part of this package is that it makes it **easier to use provider APIs** and so any changes we are proposing here should keep that in mind.
> 
> To this end, what are valuable things this package can do to make API usage easier?
> 
> 1. Ensure that providers contain a method to fetch an API base URL. This is not very useful by itself, but it makes writing multiple API calls much DRYer.
> 2. Ensure that providers contain a method to add authentication to a request. This is what #232 did (see also thephpleague/oauth1-client#18) and it immediately improved the code I was working on that made API calls.
> 3. Provide ways to integrate more cleanly with dependent packages. The client already uses Guzzle, so it should expose methods that work with those classes. For instance, having a method like this would save a lot of repeated code:
> 
> ```php
> /**
>  * Create an authenticated client to access an API URL.
>  *
>  * @param  string $method
>  * @param  string $path
>  * @param  AccessToken $token
>  * @return Psr\Http\Message\RequestInterface
>  */
> public function getAuthenticatedRequest($method, $path, AccessToken $token);
> ```
> 
> This would allow us to write code like:
> 
> ```php
> $httpRequest = $oauthProvider->getAuthenticatedRequest('GET', 'me?fields=id,name,email', $token);
> $httpResponse = $httpClient->send($httpRequest);
> $me = json_decode($httpResponse->getBody());
> ```
> 
> Personally I would find this to be a *very* useful and complete example of how to build upon what the package provides and represents best practice.

**Comment by SammyK** [comment]
One possible tweak? :)

```php
$authClient = $client->getAuthenticatedRequest($token);

$request = $authClient->request('GET', '/me', ['fields' => 'id,name,email']);
$response = $authClient->send($request);
```

Then you'd also have the same function signature for POST, DELETE, etc. :)

**Comment by shadowhand** [comment]
@SammyK the signature of my example is also consistent for every method. What makes yours more consistent?

**Comment by ramsey** [comment]
I think @SammyK is advocating for just returning the HTTP client object rather than actually making the request, which is what it appears `getAuthenticatedRequest()` is designed to do.

I'm in favor of returning the HTTP client with all authentication details set on it and letting the user make any subsequent request they like.

**Comment by ramsey** [comment]
So, maybe the method should be `getAuthenticatedClient()`?

**Comment by shadowhand** [comment]
@ramsey that would be a misinterpretation... the PSR-7 `RequestInterface` is only a container, it would never actually generate a response until it is passed into a client with `send($request)`.

**Comment by shadowhand** [comment]
I think I understand what the suggestion is, but I would prefer that the object coming out of `getAuthenticatedRequest` be a standard PSR-7 Request object with a pre-filled header or query parameter, depending on the provider's requirements.

**Comment by ramsey** [comment]
Okay. I think I see where you are going, as well. Where does the `getResponse()` method come from? I don't see that on the `RequestInterface`.

**Comment by shadowhand** [comment]
Oh that's just bad editing on my part. The `getResponse` shouldn't be there
at all.

**Comment by ramsey** [comment]
Oops! I've edited the example and removed it. :-)

**Comment by ramsey** [comment]
I've made a couple of more changes to the variable names on the example that I think make it clearer (I hope). Let me know if my assumptions were correct.

**Comment by shadowhand** [comment]
@ramsey was trying to get to this today but stalled out doing some other cleanup work. Will start on it soon!

**Comment by shadowhand** [comment]
PR created in my local fork, blocked until #274 is merged.

**Comment by shadowhand** [comment]
@ramsey this can be closed, not sure why my PR didn't automatically close it out.

**Comment by ramsey** [comment]
No worries. I think it has to be merged into `master` before it fully closes issues on GitHub.
