### ISSUE TITLE
Question: Have offline access 

### ISSUE THREAD

**Issue by koxon** [thephpleague/oauth2-client#270]
Hello,

When I connect with Google, Google keeps requesting "Have offline access".
The scopes are the default ones. I even tried to enforce the "accessType" to "online" and the "approval_prompt" to "auto".

No luck so far on my three gmail accounts :( what am I missing?

If you guys have any ideas I'd greatly appreciate.
Thanks for this great library.

Nick

**Comment by ramsey** [comment]
Looping in @shadowhand, who maintains the [oauth2-google](https://github.com/thephpleague/oauth2-google) provider, to see if he can help with this issue.

**Comment by shadowhand** [comment]
I'm not able to reproduce this. When I run the example code contained in the README, it says nothing about offline access:

![screen shot 2015-04-25 at 1 27 55 pm](https://cloud.githubusercontent.com/assets/38203/7334126/fa778f24-eb4e-11e4-9b4c-9e8bd4a3d3bd.png)

**Comment by koxon** [comment]
Thanks for your help.

Looking at the FAQ, I see this:
https://developers.google.com/+/sign-in-faq#what_is_the_meaning_of_a_consent_screen_that_always_displays_have_offline_access

I don't think it's relevant for my problem though, but if you'll think of
something.

I will try to run the code from the README on my account and see.

Thank you
Nick

On Sat, Apr 25, 2015 at 2:28 PM, Woody Gilk <notifications@github.com>
wrote:

> I'm not able to reproduce this. When I run the example code contained in
> the README, it says nothing about offline access:
>
> [image: screen shot 2015-04-25 at 1 27 55 pm]
> <https://cloud.githubusercontent.com/assets/38203/7334126/fa778f24-eb4e-11e4-9b4c-9e8bd4a3d3bd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-client/issues/270#issuecomment-96257241>
> .
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.

**Comment by koxon** [comment]
I just tested with the exact code from the readme and I get the same issue for my existing accounts.

However, I just created a new Gmail account and it works for this one.
I believe that because I accepted the "Have offline access" authorization level in the past, it keeps prompting me for it. Even though the scope has changed. 

So I think it's an issue on the Google side. Maybe it's wanted on their end to keep prompting for the highest level you've accepted in the past. But it is certainly confusing...

Thank you for your help.
I close this question.

Cheers
Nick

**Comment by koxon** [comment]
To revoke access for a specific app on your google account visit:
https://accounts.google.com/b/0/IssuedAuthSubTokens

Revoke the app. Then you will be prompted correctly based on the scope you've selected.
They should definitely advertise this URL on the authorization popup ...

cheers
