### ISSUE TITLE
Copy examples from Google

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-client#272]
Do we want to copy [the examples](https://github.com/thephpleague/oauth2-google/tree/master/examples) from the Google provider into the main repo? Everything except the `provider.php` is generic and could be copied over.

**Comment by shadowhand** [comment]
I could go either way with this... I'm not sure how useful it is to have actual code vs the README examples. I just had to set up the code for a live test and decided to commit it into the repo.

**Comment by ramsey** [comment]
I think examples specific to providers should remain in the individual provider repos. However, I do want to get a generic default provider in the base repo and have examples using that.
