### ISSUE TITLE
Update Guzzle to ~5.0?

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#286]
I just installed the client with composer and saw this:

> guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

Any reason not to patch to the new version?

**Comment by stevenmaguire** [comment]
To quote @ramsey from #214 

> The 1.0 branch is already running Guzzle 5. :-)

**Comment by rtheunissen** [comment]
Aw sweet! Didn't realise there was a 1.0. Thanks. :+1:

**Comment by benjy** [comment]
The 1.0 branch is still in development though right? Is 1.0 going to be compatible with the minor versions leading up to 1?

**Comment by shadowhand** [comment]
@benjy 1.0 is a major version bump and does include API changes. The majority of these are internal, (most) of the external API remains the same.

**Comment by benjy** [comment]
Do you have an ETA for the first tagged 1.0.x release?

**Comment by shadowhand** [comment]
Hopefully very soon. Definitely within the next month.

**Comment by benjy** [comment]
OK great, thanks for the info.
