### ISSUE TITLE
[1.0] Request parameters not passed correctly to the HTTP client

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#287]
I noticed something strange on the 1.0 branch: take a look at the arguments passed to the client in [AbstractProvider/getAccessToken](https://github.com/thephpleague/oauth2-client/blob/1.0/src/Provider/AbstractProvider.php#L275) and compare them to the function definition in [AbstractHttpAdapterTemplate](https://github.com/egeloen/ivory-http-adapter/blob/0.6.0/src/AbstractHttpAdapterTemplate.php#L50).

    $httpResponse = $client->post($this->urlAccessToken(), [
        'headers' => $this->getHeaders(),
        'body' => $requestParams,
    ]);

When I changed it locally to match the method header, everything worked as expected.

    $httpResponse = $client->post($this->urlAccessToken(), $this->getHeaders(), $requestParams);

**Comment by shadowhand** [comment]
@rtheunissen hmm, I wonder if something changed upstream, or if we just did it oddly the first time around. I'll look into it.

**Comment by rtheunissen** [comment]
I noticed that Guzzle 5 expects headers and body as $options, but the Ivory Http Adapter doesn't?

**Comment by ramsey** [comment]
This was my fault. I did this as part of conflict resolution when I merged master into 1.0. I ended up following the Guzzle 5 interface, rather than the Ivory interface. I won't make that mistake again. :-)

**Comment by rtheunissen** [comment]
:+1:
