### ISSUE TITLE
[1.0] Reddit complained that it received an invalid grant type

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#288]
On 1.0, I was receiving 401's from Reddit stating that I was using in invalid grant type. I'm not sure where in the pipeline it was failing, but the *object* grant in [AbstractProvider/getAccessToken]() doesn't seem to ever be requested its __toString(). As soon as I changed $grant to "$grant" the problem disappeared.

Tried to have a look through egeloen/ivory-http-adapter but didn't spend too much time trying to figure out where the translation actually happens.

**Comment by shadowhand** [comment]
@rtheunissen thanks, I'll look into it. Are you developing your own oauth2-reddit client?

**Comment by rtheunissen** [comment]
Yup, it's currently at [https://github.com/rtheunissen/oauth2-reddit](https://github.com/rtheunissen/oauth2-reddit) but I wrote it this morning so it's still quite new. Once I have it tested and used it for a while I'll bump it up to a 1.0.0.

I'm back on 0.11.0 for now though.

**Comment by rtheunissen** [comment]
v1.0.1 tagged at [rtheunissen/oauth2-reddit](https://github.com/rtheunissen/oauth2-reddit).

I've created a pull request to add it to the readme.

**Comment by rtheunissen** [comment]
Getting back to the issue at hand.. I'll try reproduce it again because the __toString() really should have worked. I'll report back.

**Comment by shadowhand** [comment]
@rtheunissen did you get any different result?

**Comment by rtheunissen** [comment]
I just reproduced it and received "invalid_grant" which was not the case when I explicitly quoted the grant in the parameters. That means that the grant's __toString() wasn't used to be the value of that parameter in the request.

**Comment by rtheunissen** [comment]
With the changes from #291 and quoting the grant, all my tests are passing for both 0.11 and 1.0

**Comment by ramsey** [comment]
@rtheunissen with merging in #291, does that mean this is resolved?

**Comment by rtheunissen** [comment]
:+1:
