### ISSUE TITLE
[1.0] Some providers don't have an AccessToken uid

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#296]
I'm not sure if this is a case where maybe the token itself should be the UID or if something should be generated for it, but Reddit doesn't provide an id-like field other than the token itself. 

- Should all providers set *some* uid, even if it's not from the authenticating source?

This is the method that currently fails if the field isn't supported:
https://github.com/thephpleague/oauth2-client/blob/1.0/src/Provider/AbstractProvider.php#L413

**Comment by ramsey** [comment]
Fixed in #297
