### ISSUE TITLE
[1.0] Add option to overwrite HTTP client timeout

### ISSUE THREAD

**Issue by SammyK** [thephpleague/oauth2-client#303]
The default timeout for the curl adapter is 10 seconds which isn't enough time for low Starbucks connections. :)

I don't have time to add this myself, but it should be low-hanging fruit to anyone who wants to take it on. The constructor of the `AbstractProvider` needs something like this:

```php
        if (empty($collaborators['httpClient'])) {
            $client = new CurlHttpAdapter();
            $config = $client->getConfiguration();
            $config->setTimeOut(60); // This should be configurable with an option
            $collaborators['httpClient'] = $client;
        }
```

Then we can have a `timeout` option to overwrite the default when we're on slower connections:

```php
$provider = FooProvider([
    // . . . 
    'timeout' => 60,
]);
```

This is really needed when using the authenticated client to upload videos. :)

**Comment by shadowhand** [comment]
Makes sense, though I worry that this will grow hair with time... once we start to allow configuration of the HTTP client through the provider options (vs injecting a configured client), where do we draw the line? Should we allow every client config option to be passed through? (Probably not.) Should we allow _some_ options to be passed through? (Which ones?)

For this specific option, I think it makes sense.

**Comment by SammyK** [comment]
> though I worry that this will grow hair with time

In my experience, any project that has an HTTP client in it grows so much hair over time it ends up looking like Big Foot. Hehe.
