### ISSUE TITLE
Switch to Guzzle 6

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-client#314]
@ramsey do we want to switch to [Guzzle 6](http://docs.guzzlephp.org/en/latest/psr7.html)? It looks like the Ivory adapter is still using an outdated PSR-7 interface. I've experimented with integrating Guzzle 6 and the code is actually smaller than using Ivory and the behavior feels more consistent.

**Comment by rtheunissen** [comment]
@shadowhand Could you branch your experimental integration? Even if it's incomplete or broken, just to see what the behaviour is like. If I understand correctly, the provider would return a Request object rather than make the request and return a response?

**Comment by eliecharra** [comment]
:+1: To integrate PSR7 through Guzzle 6

**Comment by ramsey** [comment]
Agreed. Let's do it. Thanks, @shadowhand!

**Comment by rtheunissen** [comment]
Ready to close with #315 merged?

**Comment by ramsey** [comment]
Yep. Thanks for the reminder.
