### ISSUE TITLE
Short-lived vs long-lived access tokens

### ISSUE THREAD

**Issue by SammyK** [thephpleague/oauth2-client#320]
Do other providers need to deal with exchanging short-lived access tokens with long-lived ones? I want to make sure that functionality is unique to Facebook before adding that feature to the Facebook provider. :)

Ping: @stevenmaguire @shadowhand @howlowck @tpavlek (sorry for the spam)

Thanks to @farmnick for [brining up the issue](https://github.com/thephpleague/oauth2-facebook/issues/3).

**Comment by tpavlek** [comment]
Not on Twitch or Battle.net.

**Comment by shadowhand** [comment]
Not on Google or Square or ZenPayroll or Vend or Clover.

**Comment by rtheunissen** [comment]
Reddit provides either a temporary or permanent token, where the only difference is that a temporary token doesn't come with a refresh token and lasts only one hour.

**Comment by SammyK** [comment]
@rtheunissen Did you add the short-lived-to-permanent-token functionality to the reddit provider? I'm curious if there should at least be an interface for it in the main client repo.

**Comment by rtheunissen** [comment]
@SammyK Yeah I did but it's not pretty, decided to revisit when I merge 1.0. See here:
https://github.com/rtheunissen/oauth2-reddit/blob/master/src/Provider/Reddit.php#L131

**Comment by SammyK** [comment]
Cool - looks like the process of getting a permanent access token in Reddit is quite different than getting a long-term access token in Facebook. So maybe an interface would be quite pointless.

**Comment by rtheunissen** [comment]
How does Facebook do it? With the Reddit provider it was easy to override the default behaviour but still query that as the base URL to append to. Didn't feel it was worth creating a separate method or consider an interface.

**Comment by SammyK** [comment]
With Facebook you always get a short-term user access token by default. Then you can send the short-lived token back to the access token endpoint with the `grant_type=fb_exchange_token` param and it'll return a long-term access token. But in Facebook there's a thing call "app access tokens" which are pretty unique to Facebook and are also a dependency in the whole process.

But with Reddit it looks like you can get a permanent access token right off the bat with the authorization URL?

**Comment by rtheunissen** [comment]
Yes you can but it still expires after an hour. The only difference is that you get a refresh token so that you have the option to refresh it after it expires. Temporary tokens don't have a refresh token so after an hour you have to request a new one.

**Comment by SammyK** [comment]
Ah gotcha. Facebook doesn't support refreshing tokens. :/

**Comment by SammyK** [comment]
This feature [has been added to the Facebook provider](https://github.com/thephpleague/oauth2-facebook#long-lived-access-tokens).

**Comment by farmnick** [comment]
Thanks for the update and I'm sorry to bug you again. But, I'm using the
Facebook library without composer. And I can't seem to figure out how to
include the Oauth 2.0 Client library along with my other code. Is there any
way include it without Composer?

**Comment by rtheunissen** [comment]
I remember myself asking the same type of questions a few years ago, then I tried Composer and never went back again. Do you have a specific reason for not using Composer?

**Comment by farmnick** [comment]
No not really. Is it as simple as it seems to use it?

**Comment by rtheunissen** [comment]
It's effortless. Install it globally, then just `composer init` and set your dependencies, then `composer install`. There are many proper tutorials out there. Wouldn't take 15 minutes to get the hang of the basics. :)

**Comment by farmnick** [comment]
Thanks for the help.
