### ISSUE TITLE
[1.0] Can't rely on BadRequestException

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#338]
Guzzle 6 has an *optional* `http_errors` middleware, which means that it is not guaranteed that exceptions will be thrown for bad requests. 

I have two ideas that could help fix this:

1. 
 - Keep the `catch` for `BadRequestException` in order to use `$e->getReponse()`.
 - Check response status code and throw either a `ClientErrorException` or `ServerErrorException`, creating with the `Response`.
 - Could create protected `onError(request,response)` and `onSuccess(request, response)` style methods that by default throw those two exceptions.

2. Pass the `Response` to `checkResponse` *as well as* the parsed result. This would allow providers to determine errors based on status code and/or the parsed result.

---

Happy to PR this if it sounds reasonable to everyone.

**Comment by shadowhand** [comment]
This seems to very unlikely to be an issue, because if the user is passing in a custom Guzzle client that is throwing custom exceptions, it would be caught by the user and is not the responsibility of OAuth client to do so.

**Comment by rtheunissen** [comment]
:+1:

What about passing the response object to `checkResponse` alongside the parsed result?

**Comment by shadowhand** [comment]
That's probably useful. The provider can decide to use it or not, it doesn't hurt anything.
