### ISSUE TITLE
Best guess for 1.0 release?

### ISSUE THREAD

**Issue by stevenmaguire** [thephpleague/oauth2-client#349]
Are there any current feelings around an approximate timeline for a 1.0 release? #notanestimate

**Comment by ramsey** [comment]
"Soon." :-)

I'd like to get a 1.0.0-alpha1 release out pretty quickly, actually. There are just a few things that need to be finished up first.

**Comment by rtheunissen** [comment]
It might be worth laying out a checkbox list issue detailing what those things are? That way we can all contribute to get things done, as well as be aware of where we're at.

- [ ] I think this is a good idea

**Comment by ramsey** [comment]
Do you have items for that list? I recall you saying that you have a number of pull requests to get in before a 1.0.0 release. Are those all done now?

**Comment by ramsey** [comment]
As for right now, my list of things I want to close out before a 1.0 release:

* #179
* #351
* #352 

The README needs to be polished up and checked for deviations from the 1.0 way of doing things.

After these are taken care of, I'm ready to tag a `1.0.0-alpha1` release so we can lock in the API and get the providers to start updating and finding any issues.

@shadowhand and @rtheunissen, is there anything else you're planning to submit for 1.0.0?

**Comment by ramsey** [comment]
I should also add: I need to create the changelog for 1.0.0-alpha1, as well. I'll start working on this today.

**Comment by rtheunissen** [comment]
@ramsey All the things I wanted to change / PR are done now, other than 100% coverage and complete documentation. I'll take a look at those open issues today, see if I can help out.

**Comment by shadowhand** [comment]
@ramsey thanks for that... I'll get a PR up for #179 within the next 36 hours, now that the method name cleanup is finished.

**Comment by stevenmaguire** [comment]
A checklist would be helpful! 

I had to spend some time refactoring one of the now separated providers to support the changes in 1.0. I'd like to be able to have a rough plan for ensuring all packages I maintain are updated accordingly within a reasonable amount of time after the release. Furthermore, I want to get close to ensuring the interface (public and abstract method signature) of the root package is "pretty stable" for the release. The conversation in this issue is helping with those things; thanks!

**Comment by ramsey** [comment]
@stevenmaguire A checklist of things that have changed or a checklist of things left to complete before we can have a 1.0.0 release? If it's the latter, then IMO, it's just the 3 issues I linked to above. If it's the former, then I'm working on it. :-)

**Comment by stevenmaguire** [comment]
@ramsey Both lists are helpful. The remaining three issues are great and don't pose much of an issue in the separate package maintenance. The documentation about what has changed would be helpful to ensure complete coverage, and I think I have a pretty good grasp on what has changed in getting the microsoft package upgraded with passing tests.

**Comment by ramsey** [comment]
I've added a page to the wiki for this. Closing out this issue.

https://github.com/thephpleague/oauth2-client/wiki/v1.0.0-Release-Time-Table
