### ISSUE TITLE
Ensure we "docblock all the things"

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-client#351]
Item # 5 on the League's [definition of quality](http://thephpleague.com/#quality) is: "DocBlock all the things." Let's make sure at least all public (and protected, since they're technically part of the API) methods/properties are documented and have good descriptions.

Additionally, we should apply the following file header to each file:

```
/**
 * This file is part of the league/oauth2-client library
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @copyright Copyright (c) Alex Bilbie <hello@alexbilbie.com>
 * @license http://opensource.org/licenses/MIT MIT
 * @link http://thephpleague.com/oauth2-client/ Documentation
 * @link https://packagist.org/packages/league/oauth2-client Packagist
 * @link https://github.com/thephpleague/oauth2-client GitHub
 */
```

**Comment by rtheunissen** [comment]
Quoted from Gitter:

@ramsey @shadowhand Could we maybe discuss and decide on a docblock style? I would like to propose either of these:

```php
/**
 * Short description.
 *
 * Optional, longer description.
 * 
 * @param type $name Optional but recommended description.
 * @param type $name Optional but recommended description.
 * @return type Optional but recommended description.
 * @throws ExceptionClass optional reason or cause.
 */
```
```php
/**
 * Short description.
 *
 * Optional, longer description.
 * 
 * @param type $name Optional but recommended description.
 * @param type $name Optional but recommended description.
 *
 * @return type Optional but recommended description.
 *
 * @throws ExceptionClass optional reason or cause.
 */
```

Some details to clear up are:

1. Spaces between different tags?
2. Tag order (ie. param, return, throw)?
3. Should we try to line types and names up vertically?
4. Fullstops at the end of descriptions?
5. Tense: ie, “Returns, accepts, sets” vs “Return, accept, set"

**Comment by shadowhand** [comment]
@rtheunissen I greatly prefer the first style because the description is really the only part that matters for humans. The other `@` elements are primarily machine documentation (IDE and generators). Specifically:

1. No extra newlines between `@` tags.
2. `@param` `@return` `@throws`
3. I usually try to align `@param` and `@return`. I don't feel strongly about this and I think it works better if the descriptions are omitted.
4. Yes, I prefer full stop on descriptions.
5. Not entirely sure what the context is but usually form reads better.

**Comment by shadowhand** [comment]
Oh and one other thing... we absolutely should avoid using `@inheritdoc` incorrectly. Before using it, be sure to read the [inheritance docs](http://www.phpdoc.org/docs/latest/guides/inheritance.html).

**Comment by rtheunissen** [comment]
> Not entirely sure what the context is but usually form reads better.

Could you please clarify what you mean by 'form'?

**Comment by shadowhand** [comment]
@rtheunissen oops bad edit... fixed now.

**Comment by rtheunissen** [comment]
:+1: I'll take care of the documentation side of things.

**Comment by ramsey** [comment]
Thanks!

**Comment by rtheunissen** [comment]
I'm still keen to take charge of completing the documentation, I'm just waiting for the API to settle a bit. :watch:

**Comment by shadowhand** [comment]
Honestly, I don't really see value in having a docblock header in every single file. 99.9% of the time, people will be using Git and have a full copy of LICENSE with the source code. Headers tend to get out of date and create commit noise when updated.

**Comment by ramsey** [comment]
I left the year out on purpose for that reason. :-)

**Comment by ramsey** [comment]
Done!
