### ISSUE TITLE
The token google change when I was login for again

### ISSUE THREAD

**Issue by duythien** [thephpleague/oauth2-client#357]
Hi all

When the first time everything, this mean I have  save to data a some filed token_google, username, email... in to table users

But When I login again with the email  that,  then I use query sql such as the sql below to authencation as again 

```
SELECT * from users where token_google = 'my_tonken_the_first'
```
It will not working, because  of  token_google change but in the past it working

How we can reuse it when a user comes to our site after 10 days(Lets say he cleared the browser cookies) and click on "Google Login" button again.

Thanks

**Comment by shadowhand** [comment]
This is not a flaw in the library. Every time you login with a OAuth provider, the token should change. The proper way to identify a user is by using a UID that the provider sends, or another unique value like the email address.

**Comment by duythien** [comment]
Yes. I know that but When I use the library for an example github to authentication it not change every time.

So I am search that it  then I see the tokens github don't have to expire this is expected to google. Maybe I will set time life expire of token google, but the documents I do not see, how to config it ?

Thanks

**Comment by shadowhand** [comment]
You do not get to configure the expiration of access tokens, the provider decides the value. You can use `AccessToken::getExpires()` to determine the timestamp that the token will expire at (or `AccessToken::$expires` in 0.x versions.

**Comment by duythien** [comment]
Ok, thank you help replies some questions
