### ISSUE TITLE
1.0.0-alpha2 release for 4 July 2015

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-client#362]
If you have any API changes you want to make to the library, please get them in by the end of this week. I'll be releasing 1.0.0-alpha2 on Saturday.

I'm planning on finishing the upgrade guide for this release.

The next release after alpha2 will be beta1. I'd like to freeze all API changes in beta1, so that providers can make necessary updates in preparation for the GA release.

Thanks!

**Comment by ramsey** [comment]
Ping @shadowhand, @rtheunissen, @SammyK, and @stevenmaguire.

Following the alpha2 release, I'll try to contact each of the third-party maintainers directly to let them know about the upgrade guide, as well as plans for beta1 and GA.

**Comment by rtheunissen** [comment]
Thanks @ramsey, this is awesome. I'll do a thorough documentation once-over when the API is stable (so, beta1?). What are the plans re: gh-pages branch?

**Comment by SammyK** [comment]
:+1:

**Comment by ramsey** [comment]
1.0.0-alpha2 is tagged. Closing this issue.

I've added a page to the wiki for tracking the release plan. Right now, Beta 1 is scheduled for 15 July.

https://github.com/thephpleague/oauth2-client/wiki/v1.0.0-Release-Time-Table
