### ISSUE TITLE
Sentence within readme is confusing

### ISSUE THREAD

**Issue by chrissound** [thephpleague/oauth2-client#369]
On the readme: "Once and as long as your application is authorized, you then only need to refresh an expired access token."

I have trouble understanding this sentence.

**Comment by rtheunissen** [comment]
An improvement could be "Once your application is authorized, you can refresh an expired token using a *refresh token* rather than going through the entire process of obtaining a brand new token".

Does that make more sense? How would you phrase it yourself?

**Comment by chrissound** [comment]
That indeed sounds better.
