### ISSUE TITLE
Why is the refresh token null?

### ISSUE THREAD

**Issue by chrissound** [thephpleague/oauth2-client#370]
Hi there,

Any reason why a refresh token would be null? The access token is present and getUserDetails() seems to be returning an appropriate result.

```
$provider = new \League\OAuth2\Client\Provider\Google([
                'clientId'      => '',
                'clientSecret'  => '',
                'redirectUri'   => '',
                'scopes'        => ['email'],
            ]);

                $token = $provider->getAccessToken('authorization_code', [
                    'code' => $_GET['code']
                ]);

                error_log(var_export($provider->getUserDetails($token),true));
                error_log(var_export($token->accessToken, true));
                error_log(var_export($token->refreshToken, true));
```

**Comment by rtheunissen** [comment]
Might be better to ask @shadowhand on [Gitter](https://gitter.im/thephpleague/oauth2-client) or an issue on [thephpleague/oauth2-google](https://github.com/thephpleague/oauth2-google)

**Comment by ramsey** [comment]
What version of oauth2-client are you using?

**Comment by tplaner** [comment]
Google OAuth only provides refresh tokens when you [request offline access](https://developers.google.com/identity/protocols/OAuth2WebServer#offline):

```
$provider = new \League\OAuth2\Client\Provider\Google([
                'clientId'      => '',
                'clientSecret'  => '',
                'redirectUri'   => '',
                'scopes'        => ['email'],
            ]);

$provider->setAccessType('offline');
```

Google only provides the refresh token on the initial authorization request, after that it will be `null`. If you need to request a new one you must force an `approval_prompt`. To do this you must pass an additional option when requesting the Authorization URL. Something like this:

```
$provider->getAuthorizationUrl(['approval_prompt' => 'force']);
```

Hope this provides some insight.

**Comment by chrissound** [comment]
Thanks @tplaner!

**Comment by ramsey** [comment]
Thanks, @tplaner!

@chrissound, does that resolve this for you?

**Comment by tplaner** [comment]
FYI, with the release of the new client, in order to get a refresh token you have to specify offline access as follows:
```php
$provider = new \League\OAuth2\Client\Provider\Google([
                'clientId'      => '',
                'clientSecret'  => '',
                'redirectUri'   => '',
                'scopes'        => ['email'],
                'accessType'    => 'offline',
            ]);
```
Hope this saves someone time when upgrading.

**Comment by stevenmaguire** [comment]
Thanks @tplaner! If that fact is not obvious in the README for the Google provider project, please submit a PR over there to make that update. That is great information!

**Comment by miah5674** [comment]
> Google OAuth only provides refresh tokens when you [request offline access](https://developers.google.com/identity/protocols/OAuth2WebServer#offline):
> 
> ```
> $provider = new \League\OAuth2\Client\Provider\Google([
>                 'clientId'      => '',
>                 'clientSecret'  => '',
>                 'redirectUri'   => '',
>                 'scopes'        => ['email'],
>             ]);
> 
> $provider->setAccessType('offline');
> ```
> 
> Google only provides the refresh token on the initial authorization request, after that it will be `null`. If you need to request a new one you must force an `approval_prompt`. To do this you must pass an additional option when requesting the Authorization URL. Something like this:
> 
> ```
> $provider->getAuthorizationUrl(['approval_prompt' => 'force']);
> ```
> 
> Hope this provides some insight.

Thank you so much. It's works for me

**Comment by ShreyanshRaj22** [comment]
Is refresh token NULL when i m in testing mode and not published?
