### ISSUE TITLE
accessToken VS access_token

### ISSUE THREAD

**Issue by koxon** [thephpleague/oauth2-client#373]
Hi,

The AccessToken.php file changes the tokens key names.
From "access_token" to "accessToken" for example.

As Google expects me to use access_token, it fails if I used my token array without changing the keys first.

Is it wanted for some reasons?

**Comment by rtheunissen** [comment]
> it fails if I used my token array

How are you using this? Could you explain a bit more, or paste some code maybe?

**Comment by ramsey** [comment]
We don't change `access_token` to `accessToken` anywhere. Are you referring to the `$accessToken` property on the `AccessToken` class?

**Comment by koxon** [comment]
Hi,

When calling getAccessToken located in the AbstractProvider.php file. It
returns the AccessToken object.

This object is fine but I can't just json_encode it and pass it back to
Google as follow:
$client = new Google_Client();
$client->setAccessToken(json_encode($accessToken));

It would be nice to keep the original token array somewhere, with its
original keys or create a method to generate it from the object.

This way I could just do $accessToken->getOriginals() or access the
original array like this $accessToken->originals;

As of today I have to do this in order to use the $client->setAccessToken()
method:

        $accessToken['access_token'] = $accessToken['accessToken'];
        $accessToken['refresh_token'] = $accessToken['refreshToken'];
        unset($accessToken['accessToken']);
        unset($accessToken['refreshToken']);
        $client->setAccessToken(json_encode($accessToken));

Maybe I am missing something because it doesn't feel right. I'm sorry if
it's the case.
Any help would be appreciated.

Thanks
nicolas

On Sat, Jul 4, 2015 at 1:57 AM, Ben Ramsey <notifications@github.com> wrote:

> We don't change access_token to accessToken anywhere. Are you referring
> to the $accessToken property on the AccessToken class?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-client/issues/373#issuecomment-118466679>
> .
>



-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by ramsey** [comment]
@koxon, take a look at pull request #375 and let me know if something like this will solve this?

**Comment by koxon** [comment]
Hey Ben,

Yes definitely! That's what I'm looking for :)

thanks
nicolas

On Sat, Jul 4, 2015 at 5:01 PM, Ben Ramsey <notifications@github.com> wrote:

> @koxon <https://github.com/koxon>, take a look at pull request #375
> <https://github.com/thephpleague/oauth2-client/pull/375> and let me know
> if something like this will solve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-client/issues/373#issuecomment-118555237>
> .
>



-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
