### ISSUE TITLE
installation request failes on ubuntu

### ISSUE THREAD

**Issue by x-merlin-x** [thephpleague/oauth2-client#374]
I am getting an error while trying to install on ubuntu with newest curl and openssl libraries combined with newest php release:

$ composer require league/oauth2-client
Using version ^0.12.1 for league/oauth2-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/oauth2-client 1.0.x-dev -> satisfiable by league/oauth2-client[1.0.x-dev].
    - Can only install one of: league/oauth2-client[0.12.1, 1.0.x-dev].
    - Installation request for league/oauth2-client ^0.12.1 -> satisfiable by league/oauth2-client[0.12.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by ramsey** [comment]
Do you have any other packages installed that require a version of oauth2-client?

It sounds like Composer is failing to install 0.12.1 due to a version conflict, which would indicate another package you're using might require 1.0.x-dev.

**Comment by x-merlin-x** [comment]
Thank you for your quick repsonse!

No, I just made a fresh install:


§git clone https://github.com/thephpleague/oauth2-client.git

$ cd oauth2-client

$ composer require league/oauth2-client



Same error






From:  Ben Ramsey
Reply-To:  thephpleague/oauth2-client
Date:  Saturday 4 July 2015 09:33
To:  thephpleague/oauth2-client
Cc:  Andreas Pucko
Subject:  Re: [oauth2-client] installation request failes on ubuntu (#374)


Do you have any other packages installed that require a version of oauth2-client?

It sounds like Composer is failing to install 0.12.1 due to a version conflict, which would indicate another package you're using might require 1.0.x-dev.

**Comment by shadowhand** [comment]
@x-merlin-x the commands you listed don't make sense... you're trying to require oauth2-client from inside of oauth2-client?

**Comment by ramsey** [comment]
@x-merlin-x, if you're installing the package using Composer, you don't need to also clone the package with Git. That's where you're running into problems.

Composer helps you manage the dependencies of _**your project**_. So, if you have a project that you are working on, you can use Composer to install this package into that project. The standard set-up with Composer might look something like this:

1. Be sure you have installed Composer. See here: <https://getcomposer.org/doc/00-intro.md>.
2. Go to _your project's_ directory: i.e. `cd my-project/`.
3. Now, tell Composer to require oauth2-client for your project: `composer require league/oauth2-client`.
  - If your project doesn't already have a `composer.json` file, this will create one for you.
  - This will also create a `composer.lock` file and create a `vendor/` directory in your project root. All files from oauth2-client will be installed into this `vendor/` directory, along with some Composer auto-generated files and an autoloader you may use in your project.
4. If you've never used Composer in your project, then you're going to need to require Composer's autoloader in your scripts (or in your bootstrap script). That often looks something like this:

    ```php
    require 'vendor/autoload.php';
    ```

5. Now, from your code, you'll be able to use classes from the `League\OAuth2\Client` namespace.

Of course, this is a very quick, overly-simplified way of using Composer. I recommend you [watch this video](http://www.youtube.com/watch?v=OmW9kBOQKME) from @rdohms, which can help you understand Composer in greater detail.

We can't support issues you're having with Composer, so I recommend you [take a look at their mailing list and IRC channels](https://getcomposer.org/doc/07-community.md), where you can find help using Composer.
