### ISSUE TITLE
AccessToken is hard to extend

### ISSUE THREAD

**Issue by xjchengo** [thephpleague/oauth2-client#377]
```php
public function createAccessToken(array $response)
{
    return new AccessToken($response);
}
```

This hard-coding dependency make AccessToken class hard to extend.

**Comment by shadowhand** [comment]
Because of the `GrantFactory`, it is actually quite easy. First, you will need an extended access token:

```php
namespace Acme\Grant;

use League\OAuth2\Client\Grant\AuthorizationCode as Grant;

class AuthorizationCode extends Grant
{
    public function createAccessToken(array $response)
    {
        return new \Acme\AccessToken($response); // or whatever your extended token type is
    }
}
```

And then register it with the grant factory when creating your provider:

```php
$grant = new \Acme\Grant\AuthorizationCode;
$factory = new \League\OAuth2\Client\Grant\GrantFactory();
$factory->setGrant('authorization_code', $grant);

$provider = new FooProvider($options, [
    'grantFactory' => $factory,
]);
```

**Comment by xjchengo** [comment]
I just want to add a property to `AccessToken`. The `AccessToken` will be uesd by `AuthorizationCode` and `RefreshToken`. I have to do the following:

1. extend `League\OAuth2\Client\Token\AccessToken` , add a property and overload constructor
2. extend `League\OAuth2\Client\Grant\AuthorizationCode`, overload `createAccessToken`
3. extend `League\OAuth2\Client\Grant\RefreshToken`, overload `createAccessToken`
4. pass a grant factory with new grant registered to `SomeProvider`

It is hard. I think the problem is:

1. `AccessToken` doesn't take into account that there are other useful information other than `accessToken`, `expires`, `refreshToken`, `uid` when getting access token from some provider.
2. Hard-coding dependency in `AbstractGrant`.

The solution is:

1. Add a `getResponse` method to `AccessToken`. `getResponse` method returns raw response from provider.
2. Pass in `AccessToken` from `GrantFactory`. So `GrantFactory` can use this `AccessToken` to register default grant.

**Comment by ramsey** [comment]
Since the response is passed to the `createAccessToken()` method on the Grant in order to create the AccessToken, how would you propose passing an AccessToken to the GrantFactory, since it can't have been created yet?

**Comment by rtheunissen** [comment]
Would it be viable for the provider to create the access token?

**Comment by shadowhand** [comment]
FWIW, the resource owner (user) entity is created by the provider and I don't see a particularly strong reason why the provider shouldn't also create the access token. If the grant needs to be involved, it could be done as:

```php
abstract class AbstractProvider
{
    ...
    protected function createAccessToken(array $response, AbstractGrant $grant)
    {
        ...
    }
}
```

This allows the access token to read additional information from the grant if necessary.

**Comment by rtheunissen** [comment]
@shadowhand Yup, that's what I was thinking too. :+1:

**Comment by ramsey** [comment]
Looks good to me, too.

**Comment by xjchengo** [comment]
Yes, putting `createAccessToken` in `AbstractProvider` solves the problem.

**Comment by achese15** [comment]
Please I'm Getting This Error
**Fatal error: Uncaught exception 'League\OAuth2\Client\Grant\Exception\InvalidGrantException' with message 'Grant "League\OAuth2\Client\Grant\AuthorizationCode" must extend AbstractGrant'**
Please does anyone know how to handle this

**Comment by shadowhand** [comment]
@achese15 that's not enough information to diagnose the problem. Are you trying to extend the grant factory as described above?
