### ISSUE TITLE
how to use it to build api

### ISSUE THREAD

**Issue by surjit** [thephpleague/oauth2-client#386]
I have web application and i building android app + allowing users to access it by api in simple way no need for scopes, etc
simple way as done here https://developers.envoy.co/#authentication

So, developers can access it by just client_id and client_secret and then other stuff REST API will do

is there available source or tutorial to use oauth with rest api in simple way ?

**Comment by surjit** [comment]
two legged oauth

**Comment by ramsey** [comment]
@surjit, I believe our [ClientCredentials](https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/ClientCredentials.php) grant is what you're looking for.

Perhaps something like this? (I haven't tested this; it's for example purposes only.)

```php
// Note: the GenericProvider requires the `urlAuthorize` option, even though
// it's not used in the OAuth 2.0 client credentials grant type.

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'XXXXXX',
    'clientSecret'            => 'XXXXXX',
    'redirectUri'             => 'http://my.example.com/your-redirect-url/',
    'urlAuthorize'            => 'http://service.example.com/authorize',
    'urlAccessToken'          => 'http://service.example.com/token',
    'urlResourceOwnerDetails' => 'http://service.example.com/resource'
]);

$accessToken = $provider->getAccessToken('client_credentials');
```
