### ISSUE TITLE
Question : About getId

### ISSUE THREAD

**Issue by harikt** [thephpleague/oauth2-client#399]
Hi, 

I have a doubt going through the implementation `getId` of google 

https://github.com/thephpleague/oauth2-google/blob/1c6e59c801cbc0ba7942a7cd84f859bdb8ba786e/src/Provider/GoogleResourceOwner.php#L58

github 

https://github.com/thephpleague/oauth2-github/blob/5f48034ee21bb025b4710f9e2e587a9a094bc9ff/src/Provider/GithubResourceOwner.php#L53

and that of the oauth2 client https://github.com/thephpleague/oauth2-client/blob/6f837e21c1777e619234b0382ce8e6ca3d1d72bf/src/Provider/GenericResourceOwner.php#L49

Isn't that should be `$this->resourceOwnerId` than `$this->response[$this->resourceOwnerId];` .

Also it may be good if we can unify the `resourceOwnerId` and `id` of `getId` .

This came across when I was looking at the `toArray` interface https://github.com/thephpleague/oauth2-client/blob/2950326f8701cee971da47affa96c2100037a651/src/Provider/ResourceOwnerInterface.php#L34  . I am also interested to hear if there is some unified key names that will be across the providers ? For one in google have https://github.com/thephpleague/oauth2-google/blob/1c6e59c801cbc0ba7942a7cd84f859bdb8ba786e/src/Provider/GoogleResourceOwner.php#L116 , but the others basically seems sending the response array itself. 

Thank you

**Comment by shadowhand** [comment]
Regarding `GenericResourceOwner` the value of `$this->resourceOwnerId` is [the key, not the value](https://github.com/thephpleague/oauth2-client/blob/6f837e21c1777e619234b0382ce8e6ca3d1d72bf/src/Provider/GenericProvider.php#L220), so the current code is accurate.

The code for the Github owner is actually incorrect. I've opened thephpleague/oauth2-github#1 to address that issue.

In regards to the `toArray` method, there are no assumptions made about what the return value will be, only that it will return all of the details available about the resource owner. That said, the Google provider should probably be modified to do less manipulation of key names.

**Comment by harikt** [comment]
Thank you for making it clear @shadowhand . The use case of `toArray` key was basically for https://github.com/harikt/Aura.Auth/blob/usability/src/Adapter/LeagueOAuth2Adapter.php#L53 , so that it guarantees there will be things like `email`, `name` etc. I know it also depends on the providers. But even if there is nothing provided by provider some sort of functionality will be nice to have.

Thank you.

**Comment by shadowhand** [comment]
> so that it guarantees there will be things like email, name etc.

There are absolutely no guarantees about any information being available from the provider. _Most_ providers will include some kind of identifier, which is what we expose via the `getId` method. Nothing else is assumed to be available with every provider.

**Comment by stevenmaguire** [comment]
All 9 of the providers that I maintain have been updated per these discussions. Thanks for surfacing!
