### ISSUE TITLE
Problems adding DropBox as a provider

### ISSUE THREAD

**Issue by jnbdz** [thephpleague/oauth2-client#40]
I tried to add DropBox as a provider.

Here is my code: https://gist.github.com/jnbdz/7624654

I was actually able to solve the problem quickly, but I think this is something you guys should think about for your next version.

To make DropBox work I had to comment out line 70:

    //'approval_prompt' => 'force' // - google force-recheck

The problem then is if I want to use Google it won't work anymore...

**Comment by ramsey** [comment]
I believe PR #220 has fixed this. If it's still not fixed, please reopen this issue.
