### ISSUE TITLE
Doesn't give the gender field when using the google api

### ISSUE THREAD

**Issue by najela** [thephpleague/oauth2-client#402]

**Comment by ramsey** [comment]
All providers have been split out of this package. Please refer to [league/oauth2-google](https://github.com/thephpleague/oauth2-google).

Thanks!

**Comment by shadowhand** [comment]
@najela the gender field is no longer part of oauth2-google.

**Comment by najela** [comment]
@shadowhand I don't think so. I could get the gender from **https://www.googleapis.com/oauth2/v3/userinfo?access_token=**
