### ISSUE TITLE
Thrown Error after successful response

### ISSUE THREAD

**Issue by sidati** [thephpleague/oauth2-client#409]
Hello There, 
Im using your code as it for testing, of course with changing application (Google App) ID/Secret, i Do get the user info but i get also this error : 
<code>Fatal error:  Uncaught invalid_grant: invalid_grant
  thrown in /var/www/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 209</code>

Im not sure how fix it :)

Best,
Sidati

**Comment by ramsey** [comment]
What grant type are you using? Can you share some of the code?

**Comment by sidati** [comment]
same code you provide in the readme.md file, the only thing i changed is clienID, clientSecret and redirectUri :
<code>

		require __DIR__ . '/vendor/autoload.php';
		$provider = new League\OAuth2\Client\Provider\Google([
			'clientId' => 'xxxxxx',
			'clientSecret' => 'xxxxxxxx',
			'scopes' => ['profile', 'email'],
			'redirectUri' => 'http://xxxxxxxxxx'
		]);

		if (!empty($_GET['error'])) {

			// Got an error, probably user denied access
			exit('Got error: ' . $_GET['error']);

		} elseif (empty($_GET['code'])) {

			// If we don't have an authorization code then get one
			$authUrl = $provider->getAuthorizationUrl();
			$_SESSION['oauth2state'] = $provider->state;
			header('Location: ' . $authUrl);
			exit;

		} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

			// State is invalid, possible CSRF attack in progress
			unset($_SESSION['oauth2state']);
			exit('Invalid state');

		} else {

			// Try to get an access token (using the authorization code grant)
			$token = $provider->getAccessToken('authorization_code', [
				'code' => $_GET['code']
			]);

			// Optional: Now you have a token you can look up a users profile data
			try {

				// We got an access token, let's now get the user's details
				$userDetails = $provider->getUserDetails($token);
				var_dump($userDetails);

				// Use these details to create a new profile
				// printf('Hello %s!', $userDetails->firstName);

			} catch (Exception $e) {

				// Failed to get user details
				exit('Something went wrong: ' . $e->getMessage());

			}

			// Use this to interact with an API on the users behalf
			echo $token->accessToken;
			echo '<hr>';

			$grant = new \League\OAuth2\Client\Grant\RefreshToken();
			$token = $provider->getAccessToken($grant, ['refresh_token' => $refreshToken]);

			// Use this to get a new access token if the old one expires
			echo $token->refreshToken;
			echo '<hr>';

			// Number of seconds until the access token will expire, and need refreshing
			echo $token->expires;
			echo '<hr>';
		}
</code>

**Comment by ramsey** [comment]
What version of oauth2-client are you trying to use?

**Comment by sidati** [comment]
This one :
<code> "league/oauth2-client": "0.12.1</code>

**Comment by ramsey** [comment]
I'm betting it's caused by these lines:

    $grant = new \League\OAuth2\Client\Grant\RefreshToken();
    $token = $provider->getAccessToken($grant, ['refresh_token' => $refreshToken]);

For your purposes, you probably don't need these lines. They're just part of the example.

As for the error, it may be because Google doesn't accept `refresh_token` as a grant type, but @shadowhand will know more about that.

**Comment by shadowhand** [comment]
@ramsey Google does support refresh tokens, but the example doesn't work directly, as you have to copy the refresh token out of the original `$token`.

**Comment by ramsey** [comment]
Ah, right. It should be `$token->refreshToken` instead of `$refreshToken`.

@sidati, let us know if that fixes your issue.

**Comment by sidati** [comment]
Sorry that part is already commented i only wrote it for test reasons :
http://api.sidati.com/?key=&redirect=http%3A%2F%2F127.0.0.1%2Fwordpress%2F&network=google

**Comment by sidati** [comment]
My app just give the user the ability to signin/login google account, so i just need to receive the user info for once, no need to a 2nd call (refresh token)
