### ISSUE TITLE
About GenericProvider.php

### ISSUE THREAD

**Issue by ken8203** [thephpleague/oauth2-client#413]
Hello,

I was confused about the function getResourceOwnerDetailsUrl() of GenericProvider.php.
Shoud it be 
```
return $this->urlResourceOwnerDetails . '?access_token=' . $token->getToken();
```
or the original one?
```
return $this->urlResourceOwnerDetails;
```

When I used the original one, I always got an error.

Thanks!!

**Comment by shadowhand** [comment]
What service are you using with GenericProvider? By default, GenericProvider uses the `Authorization` header to send the access token to the service, rather than a query string.

**Comment by ken8203** [comment]
Okay, i got it!
Btw, I use my own oauth2 server built with oauth2-server-laravel.

Thank you a lot!
