### ISSUE TITLE
Question about custom provider

### ISSUE THREAD

**Issue by garethellis36** [thephpleague/oauth2-client#418]
Hello,

I am new to OAuth2 and am trying to use this library to consume an API. I was hoping I could use the GenericProvider class but having played around in POSTMAN and read the docs for the API, it seems that as well as sending the usual bearer token heading, the API expects me to send an additional token (let's call it `app_token`). This token is provided along with the access and refresh tokens.

I guess this means that I need to extend `AbstractProvider` and have the `getAccessToken` method return an extended version of `AccessToken` which includes `app_token` so that I can save it in MySQL. Is that right, or is there another way of doing it?

**Comment by shadowhand** [comment]
That seems likely, since the provider is doing more than what is defined in the OAuth spec.

**Comment by ramsey** [comment]
Yep. This is precisely the reason this library has the AbstractProvider: to make it easier for others to extend, according to functionality required by providers.
