### ISSUE TITLE
Just installed newest version with Composer but getting 'Invalid state.'

### ISSUE THREAD

**Issue by MrCoding** [thephpleague/oauth2-client#423]
Installed the newest version (04-09-2015) with composer:

Add the following to your composer.json file:

{
    "require": {
        "league/oauth2-facebook": "~1.0"
    }
}

And followed with : composer update

Added this to the 'demo' script : require_once __DIR__ . "/vendor/autoload.php";

Now I am getting the error : Invalid state

Anyone any idea why this is happening ?? Thank you in advance, and enjoy your weekend!

**Comment by MrCoding** [comment]
I took this part off from the code like this :

//    unset($_SESSION['oauth2state']);
//    echo 'Invalid state.';
//    exit;

And now suddenly it is working. Isn't that weird ?

**Comment by shadowhand** [comment]
I'm not sure what "demo" script you are referring to. If there is a bug in [oauth2-facebook](/thephpleague/oauth2-facebook) then you should report it here.

"Invalid state" error usually means one of two things:

1. You did not correctly capture the state before redirecting to authorization.
2. Your server time is significantly off from the provider time.

Commenting out the state check will not solve anything, it exists for a reason.

**Comment by MrCoding** [comment]
Mr. ShadowHand,

Thank you for your answer. I will check both suggestions. What I meant by 'demo' is my own script where I pasted the code which is provided on the page. So that's why I called it a 'demo' script.

**Comment by ramsey** [comment]
@MrCoding Were you able to resolve this?
