### ISSUE TITLE
[Question] New Provider

### ISSUE THREAD

**Issue by adam-paterson** [thephpleague/oauth2-client#425]
I've recently done some work with Nectar. They don't offer a public API, only for authorised parties. I've created a provider for our project using oauth2-client. Is it a waste of time doing a PR for this provider since it's very unlikely it'll be used often?

**Comment by adam-paterson** [comment]
* Edited Title

**Comment by ramsey** [comment]
We aren't adding new providers to the repo in 1.0. If you created a third-party provider repo, you may add a link to our list here:

https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md

**Comment by adam-paterson** [comment]
@ramsey, that was the question. I've already added Rdio and Slack. However I have another one I've created for a closed API provider. Is it worth me doing a pull request or are you guys trying to limit the third party providers to the most used providers?

**Comment by tpavlek** [comment]
I think having the absolute highest number of providers will inflate this
packages ePeen so +1 on adding it from me.

On Mon, Sep 7, 2015 at 8:09 AM, Adam Paterson <notifications@github.com>
wrote:

> @ramsey <https://github.com/ramsey>, that was the question. I've already
> added Rdio and Slack. However I have another one I've created for a closed
> API provider. Is it worth me doing a pull request or are you guys trying to
> limit the third party providers to the most used providers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-client/issues/425#issuecomment-138307385>
> .
>



-- 
Troy Pavlek
Software Developer
http://tpavlek.me

**Comment by ramsey** [comment]
We're not enforcing any limits. Feel free to add!
