### ISSUE TITLE
Is there a Xero add-on/extension?

### ISSUE THREAD

**Issue by judgej** [thephpleague/oauth2-client#432]
Not really a technical question, but I'm looking to interface to [Xero](http://www.xero.com) as a Partner Application. There seem to be many peculiarities with the way the Xero API authenticates, which are not explained, but need to be taken into account to get it to work - it's unclear to me how much of that is standard OAuth and how much has been added by Xero (such as signing certificates and SSL certificates Xero supplies that are needed to get to the Partner API URL).

So is there an extension to support Xero? I can't find one, but there may be one hanging around. If not, are there any working examples I can use to create a Xero extension?

Thanks.

**Comment by shadowhand** [comment]
It seems that [Xero publishes their own](https://github.com/XeroAPI/XeroOAuth-PHP). It is not clear to me if Xero uses OAuth2 or OAuth1, but that library should help you figure it out.

**Comment by shadowhand** [comment]
It looks like Xero uses OAuth 1.0 and is derived from [tmhOAuth](https://github.com/themattharris/tmhOAuth)

**Comment by judgej** [comment]
Ah, thanks. It sometimes needs an experienced eye to spot these things. So this library will not work for Xero, because it is strictly OAuth 2?

**Comment by shadowhand** [comment]
That's correct. And even if Xero was OAuth2, it would not support Xero because it doesn't support 2-legged OAuth.

**Comment by judgej** [comment]
That gives me a bit of a reading list to follow up :-) It looks like 2-legged OAuth 1 is a bit of a hodge-podge of different implementations, all doing things slightly their own way, and that explains why every Xero library has its own OAuth code built-in instead of *simply* using a library.

Thanks again.

**Comment by judgej** [comment]
Just a note for the curious and anyone else trying to do the same thing: the offical Xero API library may get the authentication stuff right, but it's written in an old PHP 5.0 style (no namespaces, no release tags, not on packagist) and leaves the parsing of the resources up to you, which is fairly low-level. I have been using [this rewrite of the library](https://github.com/calcinai/xero-php) so far, which implements data models over the resources that works really well for my purposes. It falls down slightly on the OAuth bits though - it does not appear to be able to renew Partner Application tokens. I've a feeling that was never completed and tested, since there are not that many Partner applications written in PHP out there. Or it could just be me. Anyway, just looking for the right pieces to join together for a complete working solution, and diving into the intricacies of OAuth can be quite a distraction.
