### ISSUE TITLE
Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in ../vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 600

### ISSUE THREAD

**Issue by wasimkham** [thephpleague/oauth2-client#444]
Hi there, 

I've just downloaded this package and followed the instructions on the readme I'm getting the error:

```Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in /vagrant/site/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 600```

Here is my code:

```
$provider = new GenericProvider([
			'clientId'                => CLIENT_ID,    // The client ID assigned to you by the provider
			'clientSecret'            => CLIENT_SECRET,   // The client password assigned to you by the provider
//			'redirectUri'             => 'http://example.com/your-redirect-url/',
			'urlAuthorize'            => API_BASE . '/oauth',
			'urlAccessToken'          => API_BASE . '/oauth/access_token',
			'urlResourceOwnerDetails' => API_BASE . '/oauth'
		]);

		try {

			// Try to get an access token using the resource owner password credentials grant.
			$accessToken = $provider->getAccessToken('password', [
				'username' => 'username',
				'password' => 'password'
			]);

		} catch (IdentityProviderException $e) {

			// Failed to get the access token
			exit($e->getMessage());

		}
```

Appreciate the help.

**Comment by ramsey** [comment]
Did you install the package into a project using Composer?

**Comment by wasimkham** [comment]
Thanks for the quick response. Yes installed with Composer.

**Comment by ramsey** [comment]
Can you paste the output of `composer show -i` here, so that we can see the versions of the packages you have installed in your project?

**Comment by wasimkham** [comment]
```
abraham/twitteroauth               0.5.4   The most popular PHP library for use with the Twitter OAuth REST API.
aweber/aweber                      v1.1.14 The official AWeber API client library.
aws/aws-sdk-php                    2.8.21  AWS SDK for PHP - Use Amazon Web Services in your PHP project
constantcontact/constantcontact    1.3.2   Constant Contact PHP SDK for v2
danielstjules/stringy              1.10.0  A string manipulation library with multibyte support
doctrine/inflector                 v1.0.1  Common String Manipulations with regard to casing and singular/plural rules.
dompdf/dompdf                      v0.6.1  DOMPDF is a CSS 2.1 compliant HTML to PDF converter
facebook/php-sdk-v4                4.0.23  Facebook SDK for PHP
guzzle/guzzle                      v3.9.3  PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle
guzzlehttp/guzzle                  6.1.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.0.2   Guzzle promises library
guzzlehttp/psr7                    1.2.0   PSR-7 message implementation
illuminate/container               v5.1.16 The Illuminate Container package.
illuminate/contracts               v5.1.16 The Illuminate Contracts package.
illuminate/events                  v5.1.16 The Illuminate Events package.
illuminate/filesystem              v5.1.16 The Illuminate Filesystem package.
illuminate/support                 v5.1.16 The Illuminate Support package.
illuminate/view                    v5.1.16 The Illuminate View package.
ins0/google-measurement-php-client v2.0.1  Server-Side PHP Client to communicate to Google Analytics over the Google Measurement Protocol
ircmaxell/random-lib               v1.1.0  A Library For Generating Secure Random Numbers
ircmaxell/security-lib             1.0.0   A Base Security Library
james-heinrich/getid3              v1.9.10 PHP script that extracts useful information from popular multimedia file formats
jasny/audio                        v0.1.1  Process audio files using SoX
league/oauth2-client               1.0.2   OAuth 2.0 Client Library
mailchimp/mailchimp                2.0.6   API client library for the MailChimp bulk email as a service platform
pda/pheanstalk                     v3.1.0  PHP client for beanstalkd queue
phenx/php-font-lib                 0.2.2   A library to read, parse, export and make subsets of different types of font files.
philo/laravel-blade                v3.0    Use the simple and yet powerful Laravel Blade templating engine as a standalone component.
psr/http-message                   1.0     Common interface for HTTP messages
ruudk/twitter-oauth                v1.0.0  PHP 5.3 version of abraham/twitteroauth
smarty/smarty                      v3.1.27 Smarty - the compiling PHP template engine
stripe/stripe-php                  v2.3.0  Stripe PHP Library
symfony/event-dispatcher           v2.7.4  Symfony EventDispatcher Component
symfony/finder                     v2.7.4  Symfony Finder Component
symfony/var-dumper                 v2.7.4  Symfony mechanism for exploring and dumping PHP variables
```

**Comment by ramsey** [comment]
Here's what I was able to dig up. It seems as if you have a Guzzle conflict somewhere. @shadowhand, thoughts?

[In Guzzle 5.x](https://github.com/guzzle/guzzle/blob/5.3.0/src/ClientInterface.php#L118) and 4.x, `GuzzleHttp\ClientInterface::send()` requires a request object of type `GuzzleHttp\Message\RequestInterface`.

[In Guzzle 6.x](https://github.com/guzzle/guzzle/blob/6.1.0/src/ClientInterface.php#L27), `GuzzleHttp\ClientInterface::send()` requires a request object of type `Psr\Http\Message\RequestInterface`.

The oauth2-client library requires Guzzle ~6.0, so we're passing a `GuzzleHttp\Psr7\Request` object, which implements `Psr\Http\Message\RequestInterface` (see https://github.com/guzzle/psr7/blob/master/src/Request.php#L12).

If you're using Guzzle 6.1.0, which your `composer show -i` indicates you are, then I don't see how there is a `GuzzleHttp\Message\RequestInterface` object being used at all, since this interface no longer exists in Guzzle 6.x.

I see in your list that there is a package requiring Guzzle 3.x, but that shouldn't be a conflict, and it also doesn't include `GuzzleHttp\Message\RequestInterface`. The only versions of Guzzle that appear to use `GuzzleHttp\Message\RequestInterface` are 4.x and 5.x, neither of which are showing up in the list here. 

My best guess is that you've got Guzzle 4.x or 5.x installed in your path somewhere, and that's causing a conflict, but that's just a wild guess.

**Comment by ramsey** [comment]
Were you able to resolve this issue?

**Comment by wasimkham** [comment]
@ramsey really sorry for the non-response. It was an issue as I am running 2 versions of Guzzle, I have 2 projects that are interlinking and they require different versions of Guzzle. Annoying I know - haven't worked on this part of the project since so I have no solution - probably not worth sharing as it won't be a common issue. Appreciate the help and apologies for the late response.

**Comment by bmanza** [comment]
Would you mind sharing @ramsey , I am having the exact same issue.

**Comment by wasimkham** [comment]
@bmanza I have 2 different frameworks that work together, and they both have their own composer file. They both have different versions of Guzzle required.

**Comment by shadowhand** [comment]
We can't support older versions of Guzzle.

**Comment by svicino** [comment]
I am having this issue now; is there anyway to get around it?

**Comment by shadowhand** [comment]
@svicino looks like you are trying to use an old version of Guzzle which is not supported.
