### ISSUE TITLE
Question: handling expired refresh token

### ISSUE THREAD

**Issue by garethellis36** [thephpleague/oauth2-client#445]
Hello,

I have created my own Provider class which extends AbstractProvider for integrating with a particular service.

I have also created a client lib based on the workflow outlined in the base package readme. 

This provider's refresh token expires after 48 hours but there is no exact time given for the expiration in the response when you get an access token in the first place.

My solution to this is to have the following code in the Provider class' checkResponse method:

```php
        //check HTTP status code and throw exception if necessary
        if ($response->getStatusCode() >= 400) {

            //refresh token only lasts 48 hours, so we throw an exception here that can be caught in client lib to get new access token afresh
            if (isset($data["error_description"]) && stripos($data["error_description"], "Invalid refresh token") !== false) {
                throw new InvalidRefreshTokenException();
            }

            throw new IdentityProviderException(
                $response->getReasonPhrase() . (isset($data["error_description"]) ? " - " . $data["error_description"] : ""),
                $response->getStatusCode(),
                $response
            );
        }
```

Then in the client lib it's a case of checking the expiry time of the existing access token with `isExpired()`, using the existing refresh_token to get a new access token and catching the 'InvalidRefreshTokenException', at which point the lib knows to start over and get a brand new access token.

To be honest, I did not know that refresh tokens could expire so I had to think on my feet to implement this (am still limited in my experience of developing in general and have not used OAuth2 before this). Is this an appropriate solution or is there a more optimal/standard way of dealing with this?

Thanks in advance.

**Comment by shadowhand** [comment]
Normally access tokens expire fairly quickly and refresh tokens do not expire but are invalidated once used. Since the API you are working with is fairly non-standard, I think what you are doing is probably the best possible situation, based on what you have described.

**Comment by garethellis36** [comment]
Thank you.
