### ISSUE TITLE
Website documentation links not working

### ISSUE THREAD

**Issue by AllenJB** [thephpleague/oauth2-client#451]
All the internal links on http://thephpleague.com/oauth2-client/ are returning 404's - it looks like they're missing the /oauth2-client/ directory from the URL (or adding a leading '/' to what should be relative URLs)

**Comment by ramsey** [comment]
The official URL should be http://oauth2-client.thephpleague.com/, so those internal links will work. How did you arrive at http://thephpleague.com/oauth2-client/ ?

**Comment by AllenJB** [comment]
Googled for ['league oauth2 client'](https://www.google.co.uk/search?q=league+oauth2+client)

**Comment by ramsey** [comment]
I see.

I'm not sure how to fix that. @reinink, is there a way to force a redirect to the canonical URL for the documentation site?

**Comment by reinink** [comment]
Yup, and I [fixed this](https://github.com/thephpleague/oauth2-client/commit/dc55e28bb5475f2aab61c78b0e71974d3048a99a) for you.

Basically this fix just checks to see if `site.github.url` is present, which means the site is being compiled on GitHub, not locally. If this the case, it sets the `<base>` attribute.

**Comment by ramsey** [comment]
Thanks!
