### ISSUE TITLE
Google id_token

### ISSUE THREAD

**Issue by koxon** [thephpleague/oauth2-client#455]
Hello,

Google is apparently returning an id_token along with the access_token and refresh_token.
See: https://developers.google.com/identity/protocols/OpenIDConnect?hl=en#exchangecode

I don't see this token as part of the returned value from the library.

Am I missing something?

**Comment by shadowhand** [comment]
I'm not sure what this issue is about, but if it is for the Google provider, you should [report it over there](https://github.com/thephpleague/oauth2-google).

**Comment by koxon** [comment]
ok thanks:) pressed comment too soon :) Will ask there.
