### ISSUE TITLE
Using mobile generated access token for authentication

### ISSUE THREAD

**Issue by Surt** [thephpleague/oauth2-client#462]
I'm triying to use an already generated token to ask data to facebook.
the client sends me a token string (from a mobile app where the app already has the token) and I'm triying to use it to get data from facebook in this way

```php
// $access_token comes from the mobile app
$token = new \League\OAuth2\Client\Token\AccessToken(array('access_token' => $access_token));
$userDetails = $provider->getUserDetails($token);
``` 

but it does not work (maybe due to the lack of expiration time, etc?
Does anybody did this before and can help me? Actually I'm triying only for IOS (swift) but in a near future I will need to get the token from android too)

**Comment by shadowhand** [comment]
@Surt instead of sending an `AccessToken` object, just pass the string:

```php
$userDetails = $provider->getUserDetails($access_token);
```

**Comment by Surt** [comment]
@shadowhand ```Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::getUserDetails() must be an instance of League\OAuth2\Client\Token\AccessToken, string given````

**Comment by ramsey** [comment]
@Surt, were you able to resolve this issue?

**Comment by Surt** [comment]
@ramsey I finally did it creating a new AccessToken object. It seems to work now despite what I wrote on the issue. I don't know if I did a composer update so I can trace why it's working now.

```php
 $token = new \League\OAuth2\Client\Token\AccessToken(array('access_token' => $access_token));
$userDetails = $provider->getUserDetails($token);
```
