### ISSUE TITLE
State code with special characters

### ISSUE THREAD

**Issue by polibou** [thephpleague/oauth2-client#463]
I'm not an advance developer so I might not be understanding everything completely.  However, shouldn't the generated state string passed to the auth server be url_encoded?  I'm seeing instances where the state string contains a "+" symbol and using $_GET after returning from the auth server returns a string with spaces instead of the plus sign.  I assume there might be issues with other special characters.

**Comment by shadowhand** [comment]
The `state` parameter is passed through the library finally ending by being [passed to `http_build_query` in `getAuthorizationQuery`](https://github.com/thephpleague/oauth2-client/blob/b523109adfdab8ec7d45c7fb2ced16ce36138ca9/src/Provider/AbstractProvider.php#L353). This encodes `+` to `%2B` by default.

**Comment by shadowhand** [comment]
http://php.net/http_build_query for more information.

**Comment by polibou** [comment]
Ahh great.  It must be the server I'm testing against that is returning it back un-encoded.  I'm working with an API still in beta.  Thanks for clearing it up.
