### ISSUE TITLE
Scope?

### ISSUE THREAD

**Issue by hypnotisttom** [thephpleague/oauth2-client#464]
How do I specify a scope?  I'm having a tough time traversing the source code to figure this out...

Thanks,

Tom

**Comment by stevenmaguire** [comment]
Which provider are you attempting to use? 

The `getAuthorizationUrl` method accepts some configuration options. This method will apply declared scopes if available, otherwise it will defer to the default scopes in your specific provider. This happens in the [default provider](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L319) and the default behavior is specific to your selected provider.

```php
$options = [
    'scope' => ['scope_1','scope_2']
];

$authorizationUrl = $provider->getAuthorizationUrl($options);
```

**Comment by hypnotisttom** [comment]
I'm trying to do it with the example in the readme. I can't seem to get the
scope array in the right place.

**Comment by stevenmaguire** [comment]
Which provider are you attempting to use?

**Comment by hypnotisttom** [comment]
GenericProvider.

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'xxxxxxxxxxxxxxxxxxx',    // The client ID assigned to you by the provider
    'clientSecret'            => 'xxxxxxxxxxxxxxxxxxxxxx',   // The client password assigned to you by the provider
    'redirectUri'             => 'http://<url>',
    'urlAuthorize'            => 'https://192.168.1.46:9443/oauth2/authorize',
    'urlAccessToken'          => 'https://192.168.1.46:9443/oauth2/token',
    'urlResourceOwnerDetails' => 'https://192.168.1.46:9443/oauth2/resource'
]);

        $accessToken = $provider->getAccessToken('client_credentials');

        // We have an access token, which we may use in authenticated
        // requests against the service provider's API.
        echo $accessToken->getToken() . "\n";
        echo $accessToken->getRefreshToken() . "\n";
        echo $accessToken->getExpires() . "\n";
        echo ($accessToken->hasExpired() ? 'expired' : 'not expired') . "\n";

**Comment by stevenmaguire** [comment]
The GenericProvider should work just fine, provided the service that is available at https://192.168.1.46:9443 is following the oauth2 spec. In which case the code I provided before should work just fine. You need to declare your scopes prior to requesting an authorization code. The code that you've pasted here is after that step in the process. Look in the readme for the text: 

> If we don't have an authorization code then get one

Then within that condition you will see a call to the `getAuthorizationUrl` method. That is where you should pass in your scopes, as per my example above.

**Comment by hypnotisttom** [comment]
Ok I will try that.  I thought I could use the client credentials to authenticate instead of the authorization code.  If that's the case, why would I need to redirect to the authentication URL?

I'm trying to set up an app that will be making API calls using a stored trusted application credential.  The code I pasted does actually get an appropriate bearer.

What am I missing here?  (and maybe the answer is some sleep lol)

**Comment by stevenmaguire** [comment]
I see now. I totally missed your intention of using client credentials. I believe you can provide that same configuration array I provided above as the second parameter to the `getAccessToken` method. 

```php
$options = [
    'scope' => ['scope_1','scope_2']
];

$accessToken = $provider->getAccessToken('client_credentials', $options);
```

Those options will be sent to the [grant's `prepareRequestParameters` method](https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/AbstractGrant.php#L69) and return some parameters to accompany your request.

**Comment by sathyacse67** [comment]
I want to send email using gmail. How and where can I edit the scopes?
Give some example scopes (or) link.
By default, It allows only to view basic information.

**Comment by ramsey** [comment]
@sathyacse67 Please ask your question over on the [league/oauth2-google](https://github.com/thephpleague/oauth2-google) client provider repository. You'll be able to get help there for using OAuth2 scopes with Google. Thanks!

**Comment by ezandonai** [comment]
> I see now. I totally missed your intention of using client credentials. I believe you can provide that same configuration array I provided above as the second parameter to the `getAccessToken` method.
> 
> ```
> $options = [
>     'scope' => ['scope_1','scope_2']
> ];
> 
> $accessToken = $provider->getAccessToken('client_credentials', $options);
> ```
> 
> Those options will be sent to the [grant's `prepareRequestParameters` method](https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/AbstractGrant.php#L69) and return some parameters to accompany your request.

I tryed to do that to use Uber API, but doesn't work because `getAuthorizationUrl` method calls `getAuthorizationParameters` method that do an implode whit the scope to send in the request.
This:
```
if (is_array($options['scope'])) {
     $separator = $this->getScopeSeparator();
     $options['scope'] = implode($separator, $options['scope']);
}
```
And the `getAccessToken` method doesn't do that because don't expect scopes.
I've only been able to do it right by setting the scope to string. 
And then sending together:
```
$options = [
     'scope' => 'scope_1 scope_2 scope_3'
];
$provider->getAccessToken('client_credentials', $options);
```
