### ISSUE TITLE
getAuthenticatedRequest POST options formatting

### ISSUE THREAD

**Issue by polibou** [thephpleague/oauth2-client#465]
Hi, 

This is probably a basic question.  I'm having some trouble setting up a POST request after retrieving an access token.  I'm a bit confused on how to properly set the options parameter for a json data in the body.  A code sample on a POST and response would really be helpful. 

```
// How do I place the data below in the body? 
// Do I decode it into a php array? Wrap it in an array? Both?  
// Am I keying the $options array correctly with "body"?
$jsonData = '{ "action": "read" }';

// This doesn't seem to work
// $options = json_decode( '{ "action": "read" }', TRUE);

// This doesn't seem to work also
// $options["body] = json_decode( '{ "action": "read" }', TRUE);

// This doesn't seem to work also
// $options["body"] = '{ "action": "read" }';

// Another failed attempt
$body["action"] = "read";
$options["body"] = json_encode($body);

$request = $provider->getAuthenticatedRequest(
		'POST',
		'https://api-uri/some/resource',
		$accessToken,
		$options
        );`
			
$httpResponse = $provider->getResponse($request);
```

Also how exactly is the access_token transmitted? If it isn't already sent through the header can I accommodate that by setting $options["headers"] = $accessToken?  Thanks for any insight.

**Comment by shadowhand** [comment]
How the token is transmitted depends on the provider, though most providers use `Authorization: Bearer <token>`. Normally what you would do is pass the *encoded* (not *decoded*) `body`:

```php
$body = ['action' => 'read'];
$body = json_encode($body);
$options['body'] = $body;
$options['headers']['content-type'] = 'application/json';

$request = $this->getAuthenticatedRequest(...);
```

**Comment by polibou** [comment]
Thanks shadow, that was enough info for me to make a successful request.

FYI for anyone else.  I'm not sure if the server I'm connecting with is using a non standard implemenatation, but I needed to add the access token in the header.  It wasn't able to connect when adding it as a parameter to the getAuthenticatedRequest method.

```
$body = ['action' => 'read'];
$options['body'] = json_encode($body);
$options['headers']['Content-Type'] = 'application/json;charset=UTF-8';
$options['headers']['access_token'] = $accessToken->getToken();

$request = $provider->getAuthenticatedRequest(
	'POST',
	'https://api-uri/some/resource',
	'',  // access_token needed in header instead
	$options
);
```

**Comment by shadowhand** [comment]
Then your provider is incorrectly configured, probably not using `BearerAuthorizationTrait`.

**Comment by stevenmaguire** [comment]
Which provider are you using @polibou?

**Comment by polibou** [comment]
I'm using the GenericProvider with StitchLabs' API.  They are still in beta so as shardowhand stated they're probably not configured correctly.

**Comment by stevenmaguire** [comment]
Yep, the `GenericProvider` does use the `BearerAuthorizationTrait`. @shadowhand is right about many things :)
