### ISSUE TITLE
More client options on Abstract provider.

### ISSUE THREAD

**Issue by vassagus** [thephpleague/oauth2-client#467]
Please enable more client options on the AbstractProvider.php line 125. I'd like to disable the verify ssl option for the dev environment, but the only parameter available is timeout :(.

I know I can send an instance of the http client in the $collaborators array. However, should be good to expose more parameters and avoid doing that.

**Comment by ramsey** [comment]
I think the best option is to instantiate your own HttpClient and pass that in the `$collaborators` array, as you've already pointed out. We've provided that flexibility for use cases such as this.

For most use cases, users should not disable the verify SSL option, so we don't want to expose that as a feature.

**Comment by Shkeats** [comment]
+1 this would be helpful for dev environment. You can do it but only for proxies as per https://github.com/thephpleague/oauth2-client/issues/551
