### ISSUE TITLE
Owner url depending on scope

### ISSUE THREAD

**Issue by auburus** [thephpleague/oauth2-client#469]
Hi,

I'm implementing a provider, which has 3 different scopes. For each scope, there is a different `resourceOwnerDetailsUrl`, and I'm not really sure about how should I extend this library to accomplish this
behaviour.

I've thought  to put the `scope1` in the `getDefaultScopes` method, and use the api endpoint relative to this scope in `resourceOwnerDetailsUrl`, but if later a developer doesn't use this scope, this function will crash.

Another option is create a `resourceOwnerDetailsUrl` **property** with a default value, and use a setter to modify it, so the developers will have to set the scope in options and a url in the setter later, or it won't work.

I'd really appreciate any kind of feedback, because I don't really like this solution :blush:

**Comment by shadowhand** [comment]
I would create an `abstract AbstractWeirdProvider extends AbstractProvider` and have 3 separate provider implementations:

```php
class WeirdProviderA extends AbstractWeirdProvider
class WeirdProviderB ...
class WeirdProviderC ...
```

Using the class based approach, you could implement everything except `getResourceOwnerDetailsUrl` in `AbstractWeirdProvider` and the API would remain consistent.

**Comment by tpavlek** [comment]
Second the class based approach. I implemented something similar in the
Battle.net provider https://github.com/tpavlek/oauth2-bnet

**Comment by auburus** [comment]
Hi!

I've finally found some time to work on it. I've implemented the base class approach that both you suggested. You can see it [here](https://github.com/auburus/NetatmoApi#using-resource-owner).

Now I'll have to make all test cases and everything (to reach v1.0), and I will make the pull request to add it to the providers.

Again, many thanks!

**Comment by shadowhand** [comment]
I would suggest following PSR-2 more strictly. Using something like [static-review](https://github.com/sjparkinson/static-review) can help you find mistakes before you commit.
