### ISSUE TITLE
InvalidArgumentException thrown when the verification code is expired

### ISSUE THREAD

**Issue by nesk** [thephpleague/oauth2-client#476]
When the verification code is expired, the response from Github is:

```json
{
    "error": "bad_verification_code",
    "error_description": "The code passed is incorrect or expired.",
    "error_uri": "https://developer.github.com/v3/oauth/#bad-verification-code"
}
```

Then, you try to create a new instance of the `AccessToken` class by providing the above response. Which fails with an `InvalidArgumentException`.

Couldn't we handle this in a more nicer way?

**Comment by shadowhand** [comment]
This should be reported to @thephpleague/oauth2-github

**Comment by nesk** [comment]
I'm not sure about this, my example is about Github but the issue could affect other services.

**Comment by shadowhand** [comment]
Honestly, I don't really see a problem with this. If you try to create an access token with invalid data, it *should* throw an error. What would you suggest be done differently?

**Comment by shadowhand** [comment]
cc @stevenmaguire

**Comment by nesk** [comment]
It should throw an exception dedicated to this case. Currently, I can't access the error message provided by Github.

**Comment by shadowhand** [comment]
In this case, I'm fairly sure that the error should be getting trapped by [`checkResponse`](https://github.com/thephpleague/oauth2-github/blob/67f394f40fdb362174149393daabf5d87d67ade4/src/Provider/Github.php#L87-L96) but isn't for some reason. Hence why I suggested this was a problem with oauth2-github.

**Comment by stevenmaguire** [comment]
I agree with @shadowhand, let's move this conversation to oauth2-github. Please open an issue over there and I will do my best to help. If you are up for the task, you could skip the issue phase and submit a PR with a fix.
