### ISSUE TITLE
[Bug] GenericProvider::createResourceOwner() must be of the type array, string given

### ISSUE THREAD

**Issue by nspyke** [thephpleague/oauth2-client#478]
This is an intermittent issue, relating to #466, but usually happens after a session timeout.
In this case, I left my browser open overnight, reloaded the page in the morning, and then received this exception.
If I reload the page again after the exception, everything works as expected.

I'm using Silex, running on PHP 5.6.15, Ubuntu 14.04, Nginx, PHP-FPM and league/oauth2-client v1.1.0

Stack trace
```
Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\GenericProvider::createResourceOwner() must be of the type array, string given, 
called in /vagrant/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 763 and defined in 
/vagrant/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 223
Call Stack
#	Time	Memory	Function	Location
1	0.0001	235784	{main}( )	.../index.php:0
2	0.0250	705536	Silex\Application->run( )	.../index.php:17
3	0.0266	789264	Silex\Application->handle( )	.../Application.php:477
4	0.0383	1002728	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../Application.php:496
5	0.0383	1003584	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../HttpKernel.php:62
6	0.0508	1212728	call_user_func_array:{/vagrant/vendor/symfony/http-kernel/HttpKernel.php:139} ( )	.../HttpKernel.php:139
7	0.0508	1212928	Workshop\Controller\DefaultController->indexAction( )	.../HttpKernel.php:139
8	0.0508	1213056	Workshop\Controller\DefaultController->render( )	.../DefaultController.php:41
9	0.0548	1227072	Pimple\Container->offsetGet( )	.../DefaultController.php:125
10	0.0548	1227152	Workshop\Application->Workshop\{closure}( )	.../Container.php:113
11	0.0648	1405024	League\OAuth2\Client\Provider\AbstractProvider->getResourceOwner( )	.../Application.php:197
12	1.5436	1678688	League\OAuth2\Client\Provider\GenericProvider->createResourceOwner( )	.../AbstractProvider.php:763
```
Stack trace screenshot: https://www.dropbox.com/s/4hocj5m21tsxuut/Screenshot%202016-01-14%2010.18.32.png?dl=0&preview=Screenshot+2016-01-14+10.18.32.png

I'm thinking if we cast the response to an array, it should fix this exception and will not break BC.
I need to investigate more to confirm.

\League\OAuth2\Client\Provider\AbstractProvider::getResourceOwner:761
```
$response = (array) $this->fetchResourceOwnerDetails($token);
```

**Comment by ramsey** [comment]
I'm afraid that casting to an array might cause your application to be in an undefined state. If the GenericResourceOwner does not receive an array, I don't want the library to assume all is well and create an empty resource owner.

I think the error handling for this should happen in your application. If a second reload of the page works fine, it sounds like the first load doesn't have a populated session before it attempts to create a resource owner. Maybe check the order things are happening to ensure you've got data in your session first.

**Comment by ramsey** [comment]
@nspyke Did you have any luck catching and correcting this issue at the application level?
