### ISSUE TITLE
Revoking Access to Client?

### ISSUE THREAD

**Issue by lonnieezell** [thephpleague/oauth2-client#479]
I'm trying to provide clients the ability to revoke the authorization token for the application so that they would have to go through the login process again. Is there a way to do so with this library? I can't find one. 

For example, with Facebook we'd have to send an HTTP DELETE request to /PROFILE_ID/permissions.

**Comment by shadowhand** [comment]
That's entirely up to the provider you are authorizing against. This library only provides an abstraction of the standard OAuth2 spec, which does not include any standard for revoking tokens outside of normal expiration.

**Comment by lonnieezell** [comment]
Bummer. Thanks for the response. Would be a nice addition to simple have a 'revoke()' method in the AbstractProvider so other providers can implement, though.

**Comment by stevenmaguire** [comment]
You could also use the `getAuthenticatedRequest`.

```php
$request = $provider->getAuthenticatedRequest(
    'DELETE',
    '/PROFILE_ID/permissions',
    $accessToken
);
```

**Comment by ramsey** [comment]
Since it's non-standard, I don't think a `revoke()` method on the AbstractProvider is necessary. However, you might propose that the [league/oauth2-facebook](https://github.com/thephpleague/oauth2-facebook) provider add a `revoke()` method that does exactly what @stevenmaguire suggests. :-)
