### ISSUE TITLE
How to use access_token?

### ISSUE THREAD

**Issue by sahilr2050** [thephpleague/oauth2-client#480]
Hello All,

I am new to using oAuth magical method.

I have made some script which is work like below.

First of all i pass this url in Rest API Client.

http://www.example.com/index.php&response_type=code&client_id=articles&state=xyz

From this url i got following result.

http://www.example.com/index.php?code=ea1c1e0dab5b2aa667210fb33cba6615cf00d5c7&state=xyz

By using the code=ea1c1e0dab5b2aa667210fb33cba6615cf00d5c7 and POST Parameters
$_POST['grant_type'] = 'client_credentials';
$_POST['client_id'] = 'articles';
$_POST['client_secret'] ='articlespass';
$request = OAuth2_Request::createFromGlobals();
$response = new OAuth2_Response();

i got access token in following format.

OAuth2_Response Object
(
    [version] => 1.1
    [statusCode:protected] => 200
    [statusText:protected] => OK
    [parameters:protected] => Array
        (
            [access_token] => 546e1e60f824c753d8df97fd6e89ed45ccfc2492
            [expires_in] => 3600
            [token_type] => bearer
            [scope] => 
        )

    [httpHeaders:protected] => Array
        (
            [Location] => http://www.example.com/index.php?code=ea1c1e0dab5b2aa667210fb33cba6615cf00d5c7&state=xyz
            [Cache-Control] => no-store
            [Pragma] => no-cache
        )
)

So How can i access this [access_token]. I am trying to pass it on each and every request when user click on any URL. 

Please Help Thank you.

**Comment by ramsey** [comment]
From your code example, you are using classes named "OAuth2_Request" and "OAuth2_Response." These are not classes provided by the [league/oauth2-client](https://github.com/thephpleague/oauth2-client) library. Unfortunately, we can't provide help if you're using a different library.

What OAuth2 library are you trying to use?

**Comment by sahilr2050** [comment]
Thank you for reply i am using bshaffer  library


Sent from Outlook Mobile






On Mon, Feb 1, 2016 at 6:54 AM -0800, "Ben Ramsey" <notifications@github.com> wrote:












From your code example, you are using classes named "OAuth2_Request" and "OAuth2_Response." These are not classes provided by the league/oauth2-client library. Unfortunately, we can't provide help if you're using a different library.



What OAuth2 library are you trying to use?

**Comment by ramsey** [comment]
I recommend opening an issue on Brent's library, then. I'm sorry, but we won't be able to help here.

You may go here to open an issue and ask: https://github.com/bshaffer/oauth2-server-php
