### ISSUE TITLE
Why redirectUri, urlAuthorize are required in Password grant

### ISSUE THREAD

**Issue by stephen-talari** [thephpleague/oauth2-client#481]
Why redirectUri, urlAuthorize are required in Resource Owner Password Credentials Grant?
Can we set all these to the same value as in urlAccessToken ?

**Comment by stephen-talari** [comment]
Any help ?

**Comment by ramsey** [comment]
I assume your question is related to the use of the GenericProvider? If not, which provider are you using?

**Comment by ramsey** [comment]
@stephen-talari I am closing this issue due to lack of response. If this is still an issue for you, please let me know.
