### ISSUE TITLE
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Required option not passed: access_token Array

### ISSUE THREAD

**Issue by chsriharirao** [thephpleague/oauth2-client#482]
Hello,

 I am trying to use OAuth2 client it is working well in my localhost up to some level and able to redirect to the API server.

But when I uploaded to the server I am getting the following error, can someone please help he what could be the problem.

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Required option not passed: access_token Array ( [message] => Header is required: Authorization ) ' in /home/beach11/public_html/oauth/vendor/league/oauth2-client/src/Token/AccessToken.php:38 Stack trace: #0 /home/beach11/public_html/oauth/vendor/league/oauth2-client/src/Grant/AuthorizationCode.php(25): League\OAuth2\Client\Token\AccessToken->__construct(Array) #1 /home/beach11/public_html/oauth/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(215): League\OAuth2\Client\Grant\AuthorizationCode->handleResponse(Array) #2 /home/beach11/public_html/oauth/vendor/index1.php(31): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken('authorization_c...', Array) #3 {main} thrown in /home/beach11/public_html/oauth/vendor/league/oauth2-client/src/Token/AccessToken.php on line 38

Thank you

**Comment by shadowhand** [comment]
Looks like you didn't provide a correct authorization header.

**Comment by chsriharirao** [comment]
Hello Bro, 

Thanks for you quick response 

my code look like below where should I add header please help me 


<?php
require "autoload.php";
//require "league/oauth2-client/src/Provider/ProviderInterface.php";
$provider = new Bookingsync\OAuth2\Client\Provider\Bookingsync([
    'clientId'          => 'e94445f4-5041-49d4-bcda-3ae0af3c7dbf',
    'clientSecret'      => '9873bfdf-fe6c-4447-9197-e8a09fa5ae61',
    'redirectUri'       => 'http://localhost/oauth/vendor/index1.php' // https is mandatory for BookingSync
 //   'scopes'            => ['public'] // scopes required by your BookingSync application.
]);

if (!isset($_GET['code'])) {

    // If we don't have an authorization code then get one
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->state;
    header('Location: '.$authUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

    unset($_SESSION['oauth2state']);
    exit('Invalid state');

} else {

    // Try to get an access token (using the authorization code grant)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);

    // Optional: Now you have a token you can look up a users profile data
    try {

        // We got an access token, let's now get the user's details
        $userDetails = $provider->getUserDetails($token);

        // Use these details to create a new profile
        printf('Hello %s!', $userDetails->screenName);

    } catch (Exception $e) {

        // Failed to get user details
        exit('Oh dear...');
    }

    // Use this to interact with an API on the users behalf
    echo $token->accessToken;

    // Use this to get a new access token if the old one expires
    echo $token->refreshToken;

    // Unix timestamp of when the token will expire, and need refreshing
    echo $token->expires;
}

?>

**Comment by shadowhand** [comment]
Read the stack trace. Also you just leaked your provider secrets so you'll want to go get new credentials.

**Comment by chsriharirao** [comment]
Thank you very much, I will check

**Comment by shadowhand** [comment]
This is not a support forum. You can try the Gitter channel or StackOverflow if you need basic help.

**Comment by ramsey** [comment]
Additionally, the [BookingSync provider project](https://github.com/BookingSync/oauth2-bookingsync-php) might be able to provide better support, since it's their provider you're using.

**Comment by chsriharirao** [comment]
Hello, 

Sorry for discussing here, but as you are following the issue from the beginning, I am posting here, kindly help on this.  Actually I am not trying to connect BookingSync, I am trying to connect HomeAway API using the BookingSync example, the home away support says I need to send headers (clientid and secret) using base64, but I think as I am providing the client id and secret, the Oauth library provided by you do that, thing somewhere, please let me know it is not done by default with the provided library. 

if not kindly help me how to add that part in my code. 

https://resources.community.homeaway.com/thread/52618

Thanks

**Comment by shadowhand** [comment]
@chsriharirao in that case you would need to make a custom provider that does something like this:

```php
protected function getAccessTokenOptions(array $params)
{
    $options = parent::getAccessTokenOptions;
    $options['headers']['authorization'] = 'Basic ' . base64_encode(implode(':', [
        $this->clientId,
        $this->clientSecret,
   ]));
   return $options;
}
```

Having to use the `Authorization` header in this way is non-standard and quite unique. I've never seen anything like it.

**Comment by chsriharirao** [comment]
Thank you for your help

**Comment by Blackbaud-JasonRikard** [comment]
@shadowhand Thanks for the advice. Are you referencing the RFC when you say non-standard? I've found that this authorization header is referenced in the RFC directly https://tools.ietf.org/html/rfc6749#section-4.1.3

**Comment by shadowhand** [comment]
@Blackbaud-JasonRikard typically the header value is created as static token when the application is registered with the provider, not an encoding of the client ID and secret. That's what I mean by "non-standard".
