### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by mikaelcom** [thephpleague/oauth2-client#487]
Hi,

My Oauth server requires a basic authentication as header and not any other oauth header.

How do I do that?

Thanks

**Comment by shadowhand** [comment]
You would need to create a custom provider that overloads the `getAccessTokenOptions`, similar to 482#issuecomment-181490614

**Comment by mikaelcom** [comment]
fast and efficient, as soon as I made it work, I'll close this issue,

thx

**Comment by mikaelcom** [comment]
I did not succeed to make it work, my oauth service provider does not seem to respect perfectly the oauth procotol too... thx anyway
