### ISSUE TITLE
Make it possible to obtain resource owner details from JWT

### ISSUE THREAD

**Issue by hajekj** [thephpleague/oauth2-client#488]
It would be great if there was a way to obtain the resource owner details by parsing the JWT instead of making additional HTTP request - of course only with providers who return valid JWT as an `access_token`. This is for example the [case of Azure Active Directory](https://azure.microsoft.com/en-gb/documentation/articles/active-directory-authentication-scenarios/#claims-in-azure-ad-security-tokens). Can you think of any way which wouldn't break compatibility and let this be used?

**Proposed solution:** Adding function `getResourceOwnerFromJwt` as an abstract method allowing everyone to specify their own way. And when calling `getResourceOwner` the script would check whether the function is defined or not and act based on that?

**Comment by shadowhand** [comment]
@hajekj that's certainly an option, but would be specific to providers that implement it. As it's not part of OAuth2 spec, it would need to be implemented in providers that have the feature.

**Comment by hajekj** [comment]
Currently, the `getResourceOwner` doesn't allow any sort of extensibility and it goes straight to proceeding with the HTTP calls. So that's why I am suggesting adding an option to provide a custom way to obtain the resource owner - `getResourceOwnerCustom` maybe?

**Comment by shadowhand** [comment]
Yes, I understand what you are asking for. Since it is specific to providers (such as Azure) that do things this way, it would not be a feature of the base client package, but an additional method in providers that support it.

**Comment by hajekj** [comment]
So could you show me an example of how to implement it correctly in my [client library](https://github.com/TheNetworg/oauth2-azure/)? Because I believe it won't work without modification in oauth2-client.

**Comment by shadowhand** [comment]
```php
public function getResourceOwner(AccessToken $token)
{
    $jwt = (string) $token;
    try {
        $values = JWT::decode($token, ...);
        return $this->createResourceOwner($values, $token);
    }  catch (JWT_Exception $e) {
        // ignore errors?
    }
    return parent::getResourceOwner($token);
}
```

**Comment by hajekj** [comment]
Wonderful, I was thinking I couldn't replace a function in class which extends yours. This does the perfect job. Thank you for the hint.
