### ISSUE TITLE
AbstractProvider::getAuthorizationHeaders() - why not abstract?

### ISSUE THREAD

**Issue by garethellis36** [thephpleague/oauth2-client#492]
Hello,

I just spent ~20 minutes chasing my tail trying to work out why an authenticated request wasn't working, at which point I discovered that I had to implement the `getAuthorizationHeaders()` method in my custom provider. 

If it has to be implemented, is there any reason that [this method](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L790) is not abstract in the first place?

I'm happy to submit a PR but wanted to check that there wasn't some use-case that I hadn't thought about.

**Comment by shadowhand** [comment]
Only one reason:

There is nothing in the specification that _requires_ using headers as the method for passing the authentication token with the request.

Some providers use query strings to pass the token. The ones that do use headers have different formats with `Bearer` being the most common, though [there are exceptions](https://github.com/thephpleague/oauth2-client/issues/482#issuecomment-181490614).

**Comment by garethellis36** [comment]
That makes sense. 

It may be useful to make the documentation clearer on this point - even just updating the line about `AbstractProvider` [here](https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md) would help. Shall I PR this?

**Comment by shadowhand** [comment]
That would be great!
