### ISSUE TITLE
[Proposal] Add method to inject options array after instantiating class

### ISSUE THREAD

**Issue by rob-lowcock** [thephpleague/oauth2-client#507]
I'm adding this is an issue since it's quite specific to my own use case, and I'm not sure whether it's something that necessarily _should_ be addressed. If people are happy with it I'm more than happy to create the pull request myself.

Is it worth adding a method to AbstractProvider to allow setting the options array after the class is instantiated, rather than relying on the parameters in the constructor? There may be circumstances where it is impossible to instantiate the class with the options array already populated.

For example, I'm working on a project where classes are instantiated in a DI container, which injects (already instantiated) dependencies via the constructor. The app config is stored in a yaml file which is accessed via a parameters class that gets injected into any class that needs it. We need to store the provider details in the yaml file, but I'm reluctant to access them when instantiating GenericProvider inside the DI container as it comes perilously close to application logic.

It's worth adding that the $options parameter is already optional, but I can't find any method for modifying it after instantiation.

**Comment by shadowhand** [comment]
In my opinion, this a failure of the DI container, not this package. The scenario you are describing would be best handled by creating a custom `ProviderFactory` or some such "middleware" that creates instances based on whatever configuration you need at runtime.

I've done something similar using [Auryn](https://github.com/rdlowrey/Auryn) in my [oauth2-demos project](https://github.com/shadowhand/oauth2-demos/blob/master/src/ProviderHandler.php).

**Comment by rob-lowcock** [comment]
@shadowhand Oh awesome - thanks! Yeah, I did wonder whether the example I gave is better solved by changes to the DI container, which is something we need to work on anyway. A factory would certainly be one way of handling it, although as far as I can tell that could involve invoking the class within the factory (rather than injecting it) - is this regarded as OK? It seems pretty unavoidable to me. Alternatively, I could inject the whole container as per your example, but is that closer to a service locator?

Either way, I agree that it's not necessarily a failure of the package to not include the method. I guess my question is whether the addition would be an improvement, or would do more harm than good (for example, if the class should be immutable once invoked)?

**Comment by shadowhand** [comment]
@rob-lowcock 

> that could involve invoking the class within the factory (rather than injecting it) - is this regarded as OK?

So long as the factory only creates the object and doesn't actually execute any logic, yes.

> my question is whether the addition would be an improvement, or would do more harm than good

I think it makes the providers less predictable and so I'm not in favor of it.

**Comment by rob-lowcock** [comment]
Ah OK - that makes sense. Thanks for the explanation. I'll close this then.
