### ISSUE TITLE
I created a working provider but ...

### ISSUE THREAD

**Issue by edwardhew** [thephpleague/oauth2-client#510]
I created a provider at edwardhew/oauth2-asana, I used oauth2-github as a base, but it was not a fork. Where can I submit a request to be added to the 3rd party list?

(edited for clarity)

**Comment by shadowhand** [comment]
You can request to add providers to the 3rd party list.

**Comment by edwardhew** [comment]
Is it to fork oauth2-client, edit the providers list md file add mine to the list, then do a pull request?

Thanks for your reply.
