### ISSUE TITLE
How to integrate with codeigniter ?

### ISSUE THREAD

**Issue by technofreaky** [thephpleague/oauth2-client#511]
Hi 

I am trying to integrate this library with codeigniter. but i really cant find how. can any one help me?

i dont use composer..

**Comment by shadowhand** [comment]
You can use composer inside of CodeIgniter. There's really no excuse to not use it these days.

**Comment by technofreaky** [comment]
ok. but i haven't used composer to install CodeIgniter 
is that ok ?

**Comment by shadowhand** [comment]
https://getcomposer.org/doc/00-intro.md

**Comment by technofreaky** [comment]
@shadowhand 
thanks but i am asking how i can integrate this lib with CodeIgniter

**Comment by shadowhand** [comment]
The instructions work the same regardless of what framework you want to use.
