### ISSUE TITLE
Getting Response Headers

### ISSUE THREAD

**Issue by technofreaky** [thephpleague/oauth2-client#512]
Hi,

now i am using the below code to get request body. but how i can get the response header. 
```php
$request = $this->github->getAuthenticatedRequest($method, $url, $token,$data); 
 $data = $this->github->getResponse($request);
```

i am try to use this in a web app i am developing for that i need to read the header for the current request

**Comment by shadowhand** [comment]
Hmm, we don't provide anything like that. Your best bet if/until we do would be to extend and add a method similar to [`sendRequest`](https://github.com/thephpleague/oauth2-client/blob/b3242ca3761e8789d642f385473ebe2dc6b498b4/src/Provider/AbstractProvider.php#L599-L607) (such as `getRawResponse`) that returns the unparsed request.

**Comment by technofreaky** [comment]
@shadowhand ok if i add and incase if i update latest source from this repo and that update done by me will be removed.. how i can ?

**Comment by technofreaky** [comment]
and i can see that not `sendRequest` function parses the response 
`[getResponse](https://github.com/thephpleague/oauth2-client/blob/b3242ca3761e8789d642f385473ebe2dc6b498b4/src/Provider/AbstractProvider.php#L615-L623)` dose it

**Comment by shadowhand** [comment]
Extend the your provider, don't modify the class.

**Comment by technofreaky** [comment]
i am using a Github Provider By This https://github.com/thephpleague/oauth2-github

do i need to extend that github class ???

**Comment by shadowhand** [comment]
Correct. :)

**Comment by technofreaky** [comment]
@shadowhand 
Hi,

After extending i am unable to use OAuth Login for Github

I am getting below error

```php
An uncaught Exception was encountered
Type: InvalidArgumentException
Message: Required option not passed: "access_token"
Filename: C:\xampp\htdocs\gitsync\vendor\league\oauth2-client\src\Token\AccessToken.php
Line Number: 58
```

**Comment by technofreaky** [comment]
The below is my extended class code

```php
class Github_oauth extends League\OAuth2\Client\Provider\Github{
    
   /* public function __construct(array $options = [], array $collaborators = []){
        parent::__construct($options,$collaborators);
    }*/
    
    public function getResponse(Psr\Http\Message\RequestInterface $request){
        $response = $this->sendRequest($request);
        $pagenation = $this->getPagination($response);        
        $parsed = $this->parseResponse($response);
        $this->checkResponse($response, $parsed);
        return array('pagenation' => $pagenation,'data' => $parsed);
    }
    
    public static function getPagination($response) {  
        $header = $response->getheaders();
        $pagination = array();
        if(isset($header['Link'])){
            foreach($header['Link'] as $link){
                $l = explode(',', $link);
                foreach($l as $ll){
                    preg_match('/<(.*)>; rel="(.*)"/i', trim($ll, ','), $match);
                    if (3 === count($match)) { $pagination[$match[2]] = $match[1]; }
                }

            } 
        }
        return $pagination;
    }   
    

    
}
```

**Comment by technofreaky** [comment]
Sorry i fixed it thanks :)
