### ISSUE TITLE
Ability to store the entire access token object

### ISSUE THREAD

**Issue by hajekj** [thephpleague/oauth2-client#513]
Hello, do you think it would be possible to add the ability to store and retrieve the entire body containing the access token, refresh token etc. in the [AccessToken class](https://github.com/thephpleague/oauth2-client/blob/master/src/Token/AccessToken.php)? The reason I need it is that when I make a call to [Azure AD](https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx), it also return an `id_token` and I need to retrieve it later on.

I understand that it is more OpenID related and this is OAuth2 library, so that's why I am inquiring whether it was possible to store it this way, rather than adjusting it for use of `id_token` directly.

I can create a PR to implement both scenarios. Is this something that would be accepted?

**Comment by shadowhand** [comment]
You could create an extension of `AccessToken` and use it in the [`createAccessToken`](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L729-L732) method.

**Comment by hajekj** [comment]
I think that would complicate the fact that whenever something is changed in the official library regarding the AccessToken class, it would require an update (of course the plugin can be locked to the latest known  supported version). I will see how much effort it would take to extend the AccessToken instead of building it in.

**Comment by shadowhand** [comment]
Well no... you'd make the modification in your custom provider, so that upgrades would never effect your changes.

**Comment by hajekj** [comment]
Okay, that makes perfect sense now, thanks for the guidance. I will post here once the modification is done.

**Comment by hajekj** [comment]
This is now resolved in my dev branch so I am closing this issue. Thanks for the guidance.

**Comment by shadowhand** [comment]
Refs #518 not sure why I didn't link it in the commit.

**Comment by hajekj** [comment]
I was adding some additional validation for Azure AD tokens so it is fine, however before the merge of https://github.com/TheNetworg/oauth2-azure/issues/16 to my master, I am going to probably make it to use your implementation of the storage, so it remains efficient and doesn't do things twice.
