### ISSUE TITLE
'Required options not defined: urlAuthorize' when using ClientCredentials grant

### ISSUE THREAD

**Issue by martynbiz** [thephpleague/oauth2-client#514]
I'm using the ClientCredentials grant like so:

```php
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'jt_qa',    // The client ID assigned to you by the provider
    'clientSecret'            => 'qa1234567890',   // The client password assigned to you by the provider
    // 'redirectUri'             => 'http://oauth-client.dev/',
    // 'urlAuthorize'            => 'http://brentertainment.com/oauth2/lockdin/authorize',
    'urlAccessToken'          => 'http://brentertainment.com/oauth2/lockdin/access_token',
    'urlResourceOwnerDetails' => 'http://brentertainment.com/oauth2/lockdin/resource'
]);

try {

    // Try to get an access token using the authorization code grant.
    $accessToken = $provider->getAccessToken('client_credentials');
    .
    .
    .
```

However, I get the following error:

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Required options not defined: urlAuthorize' ...
```

Do I need this URL for this type of grant? Should it be throwing an error? I don't intend on using the authorize grant for this API, yet I have to set it anyway.

**Comment by ramsey** [comment]
For a client credentials grant, you do not need `urlAuthorize`. However, when configuring a generic provider, we don't have any way of knowing what kind of grant you'll use. Our goal is to be generic, so we have to account for all the options that you might need.

You could specify `urlAuthorize` with a dummy value, or you could extend AbstractProvider to create your own provider that doesn't require `urlAuthorize`.
