### ISSUE TITLE
Fatal error: Call to undefined function GuzzleHttp\choose_handler() in GuzzleHttp/HandlerStack.php on line 40

### ISSUE THREAD

**Issue by molavy** [thephpleague/oauth2-client#517]
hi
i give above error on using latest version of GuzzleHttp

**Comment by shadowhand** [comment]
This appears to be a Guzzle error, not an OAuth client error.

**Comment by molavy** [comment]
i found that is because i don't use compozer for adding  GuzzleHttp to project, just download GuzzleHttp and at it to project, that is because of GuzzleHttp dependency problem

**Comment by molavy** [comment]
please update docs with full install and project code with with full example code if possible
best regards

**Comment by shadowhand** [comment]
I'm not interested in providing support for people who don't use Composer.

**Comment by molavy** [comment]
ok, i use composer and problem solved, thanks anyway

**Comment by laraveldev9** [comment]
Please tell us about solution.

**Comment by 2ndGAB** [comment]
@shadowhand strange answer!
It's not always possible to use composer when other modules such as guzzle-command and guzzle-services have been updated to use guzzle6 but don't have composer updated yet.

**Comment by standus** [comment]
Include basic files:
```
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/functions.php';
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Psr7/functions.php';
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Promise/functions.php';
```

**Comment by mr-pack** [comment]
composer is additional pain for PHP world

**Comment by donprecious** [comment]
> Include basic files:
> 
> ```
> include_once dirname(dirname(__DIR__)).'/GuzzleHttp/functions.php';
> include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Psr7/functions.php';
> include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Promise/functions.php';
> ```

am new to laravel and php , please how do u include them

**Comment by Keimille** [comment]
Enter this at the top of your code
require "/vendor/autoload.php";

**Comment by PurHur** [comment]
Good issue for the php dev world. There is something wrong with the composer autoloader or the gruzzle autoload config.

I created a dump with composer dumpautoloader -o and it skipped the functions because its only loading a classmap. If anyone does this because he is going to production with this it will fail.

**Comment by mxdpeep** [comment]
> Good issue for the php dev world. There is something wrong with the composer autoloader or the gruzzle autoload config.
> 
> I created a dump with composer dumpautoloader -o and it skipped the functions because its only loading a classmap. If anyone does this because he is going to production with this it will fail.

this issue is 3 years old, Jesus!!!
