### ISSUE TITLE
http_build_query in AbstractProvider

### ISSUE THREAD

**Issue by Sunix99** [thephpleague/oauth2-client#519]
In AbstractProvider, the arg_separator in all http_build_query should be provided to ensure it respects standard url_encoded separator required by most OAuth2 server. It should be something like: 

http_build_query($params, null, '&');

In php.ini, arg_separator.output can be redefined which may cause problem on some server. Forcing the parameter to & in http_build_query will solve this issue.

I corrected this issue in my own provider, but correcting it in AbstractProvider may avoid some debugging times to others.

**Comment by ramsey** [comment]
I think this is a good idea. @Sunix99, would you like to submit a pull request to include this? If not, I can try to update it sometime in the near future.

**Comment by shadowhand** [comment]
I'm on it!

**Comment by shadowhand** [comment]
@Sunix99 this has been fixed in v1.4.1.

**Comment by Sunix99** [comment]
Thanks a lot.
