### ISSUE TITLE
getAuthenticatedRequest, posting data seems impossible?

### ISSUE THREAD

**Issue by 0plus1** [thephpleague/oauth2-client#526]
I am trying to post some data to Reddit, using the provided method:

`$request = $redditClient->getAuthenticatedRequest(
                'POST',
                'https://oauth.reddit.com/api/submit',
                $accessToken,
                $options
            );`

The problem raises at guzzle level, you seem to accept only 'body' as an options array index, although Guzzle doesn't accept body anymore (https://github.com/guzzle/guzzle/issues/1079).

Is there something I am missing here or I am better off completely ignoring getAuthenticatedRequest?

If so I think it should be phased out of this packet as it's confusing and possibly not fully working.

**Comment by shadowhand** [comment]
@0plus1 the Guzzle issue you linked to says that `body` must be encoded but is still available. You can still pass it into `$options` but it must be a string, probably either a JSON strings or a form string.
