### ISSUE TITLE
why can't options be changed after __construct has been called?

### ISSUE THREAD

**Issue by bazo** [thephpleague/oauth2-client#529]
nowadays many apps use DI to inject services. the configuration is mostly static, so setting usernames, passwords, keys etc is ok.

but providing urls at config time is wrong.
web apps are dynamic, every developer can run it locally on a different domain, app can be deployed on different urls as well.

now when i inject the provider in my controllers i want to set a dynamically generated url i cannot.
so i have to create a factory to create a provider, so that i can code conforming to best practices.

adding 1-2 method(s) setOption(s) wouldn't hurt i think

**Comment by shadowhand** [comment]
Modification of class configuration after instantiation is not reliable. For example, what if some calls are made and then options are changed? The correct way to configure a service is to define all of the configuration options early and modify them as necessary based on **environment** configuration, then instantiate the service.
