### ISSUE TITLE
Help in client side implementation of Oauth2

### ISSUE THREAD

**Issue by bobc82** [thephpleague/oauth2-client#539]
i'm learning about Oauth 2.0 library.
I read something about Oauth 2.0 Server [here] (http://bshaffer.github.io/oauth2-server-php-docs/cookbook/)

And after i looked for Oauth 2.0 Server for CodeIgniter [here] (github.com/grasses/codeigniter-oauth2-server) 

That which i need it's to simulate obtaining authorization for access in a server that contains some api. Fistly i simulate this in command line:

```
    curl -u testclient:testpass http://localhost/token.php -d 'grant_type=client_credentials'
```

After i got the token, I ran this command to get access for resources:

```
    curl http://localhost/resource.php -d 'access_token=MY_TOKEN'
```

The response was ok and i could access on the resource.

I would ask an information. Does anyone know a way to implement an Oauth 2.0 client request integration with [Requests library](https://github.com/rmccue/Requests) making a token request to Oauth 2.0 Server? Any help will be appreciated!

**Comment by shadowhand** [comment]
I would recommend using StackOverflow for questions regarding combining oauth2-client with specific packages.

That said, I'm not sure why you would use Requests over Guzzle.
