### ISSUE TITLE
How to get accessToken..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [thephpleague/oauth2-client#540]
I have try bellow code with my clientID and Secretkey 

provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'demoapp',    // The client ID assigned to you by the provider
    'clientSecret'            => 'demopass',   // The client password assigned to you by the provider
    'redirectUri'             => 'http://example.com/your-redirect-url/',
    'urlAuthorize'            => 'http://brentertainment.com/oauth2/lockdin/authorize',
    'urlAccessToken'          => 'http://brentertainment.com/oauth2/lockdin/token',
    'urlResourceOwnerDetails' => 'http://brentertainment.com/oauth2/lockdin/resource'
]);

 $accessToken = $provider->getAccessToken();
  echo $accessToken;
  exit;
Try to get accessToken but it'll give me error 

Missing argument 1 for League\OAuth2\Client\Provider\AbstractProvider::getAccessToken(), called in D:\wamp\www\open_digy-pay\trunk\application\modules\buy_sell_transaction\controllers\content.php on line 105 and defined

**Comment by shadowhand** [comment]
You need to fetch the access code before getting the token, as per [the docs](http://oauth2-client.thephpleague.com/usage/).

**Comment by Surendaran-Cg** [comment]
$accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

but this line is not working. Throwing invalid client. Please any one help.

**Comment by fvincenti73** [comment]
I've a similar issue. with Facebook Social Auth

TypeError: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::getResourceOwner() must be an instance of League\OAuth2\Client\Token\AccessToken, null given,

**Comment by TomRoskam** [comment]
> $accessToken = $provider->getAccessToken('authorization_code', [
> 'code' => $_GET['code']
> ]);
> 
> but this line is not working. Throwing error invalid client. Please any one help.

Same problem here
