### ISSUE TITLE
AbstractProvider.php adding verify

### ISSUE THREAD

**Issue by jhayiwg** [thephpleague/oauth2-client#551]
Hello I hope you can add verify option and set to true as default. I think this is an easy hack for development that having ssl issue.
    
protected function getAllowedClientOptions(array $options)
    {
        $client_options = ['timeout', 'proxy', **'verify'**];

**Comment by shadowhand** [comment]
We currently only allow using [`verify` with `proxy`](https://github.com/thephpleague/oauth2-client/blob/0b3226498c87a737366211b1a5b745d73a5717e2/src/Provider/AbstractProvider.php#L154-L157).

**Comment by slince** [comment]
Hi, I met a similar problem;  "curl 60",  I need turn off ssl verification.

**Comment by shadowhand** [comment]
Disabling SSL verification is a security risk and we will not make oauth2-client less secure by default. This option can be controlled on a per-use-case basis as necessary.

**Comment by artipixel** [comment]
Hi,
First of all thank you! Your repo is very useful!
We have a major problem with this issue. 
I've change the source code to make verify = false, and I would really appreciate for a method to do it without a proxy, we have a lot of dev environments and can't use this option.
I really don't think editing the source code in all of my project is a good solution, especially when running composer again, we need to make those changes again.
I've saw a lot of people having trouble with this issue, so if you can please provide us with a proper solution we will be grateful! thanks!

**Comment by shadowhand** [comment]
@artipixel that solution looks perfectly acceptable.
