### ISSUE TITLE
AuthorizatonCode must extend AbstractGrant?

### ISSUE THREAD

**Issue by lsascha** [thephpleague/oauth2-client#553]
Hello,

we are trying to use this library to fetch the battlenetid and battlenet-tag.

We where unlucky to use the inofficial provider and since it seems it was not very active we use the pure oauth2-client library.

Unfortunately we always get the following error which makes not much sence to us since the Class AuthorizationCode class does! extend AbstractGrant.

We are using the Flow framework https://flow.neos.io/
and installed it with composer.

> Grant "League\OAuth2\Client\Grant\AuthorizatonCode" must extend AbstractGrant
> League\OAuth2\Client\Grant\Exception\InvalidGrantException thrown in file
> Packages/Libraries/league/oauth2-client/src/Grant/GrantFactory.php in line 98.

We then just for testing purposes removed the Grant check to see if that gives more feedback in what is really wrong which gave this error.
> [Thu Aug 25 23:46:54 2016] [warn] [client 81.173.178.29] mod_fcgid: stderr: PHP Fatal error:  Class 'League\OAuth2\Client\Grant\AuthorizatonCode' not found in /var/www/virtual/wtfsts/bot/Packages/Libraries/league/oauth2-client/src/Grant/GrantFactory.php on line 74

So the class is not found?

Would like to know what we are doing wrong here. ;)

the used code is as following:
```
  $provider = new \League\OAuth2\Client\Provider\GenericProvider([
  'clientId'                => $this->settings['Bnet']['apiKey'],    // The client ID assigned to you by the provider
  'clientSecret'            => $this->settings['Bnet']['apiSecret'],   // The client password assigned to you by the provider
  'redirectUri'             => "https://thedomain/bnetbot/register",
  'urlAuthorize'            => $urlAuthorize,
  'urlAccessToken'          => $urlAccessToken,
  'urlResourceOwnerDetails' => $urlResourceOwnerDetails
  ]);
  $token = $provider->getAccessToken("authorizaton_code", [
    'code' => $code,
    'scope' => [],
    'grant_type' => 'authorization_code'
  ]);
  
  $user = $provider->getResourceOwner($token);
  
  $userArray = $user->toArray();
  
  $userBattleTag = $userArray['battletag'];
  $userBattleNetId = $userArray['id'];
```

**Comment by shadowhand** [comment]
Why not use https://packagist.org/packages/depotwarehouse/oauth2-bnet ?

**Comment by lsascha** [comment]
thanks. i think the issue was that the redirect_uri of the authorization code was not 100% the same as the provided redirect_uri for the access token.
(we send a parameter with the uri when requesting the authorization token to know for which user it is, but left it out when using the access token)

not sure why it would not find a class then, but using another library for it now we noticed that error after a while.

thanks for the reply. I would say this is closed then. ;)
