### ISSUE TITLE
My webhost is unable to solve curl error 77

### ISSUE THREAD

**Issue by raknjak** [thephpleague/oauth2-client#555]
I really don't like asking for answers when I'm reasonably sure I am following the correct scripting procedures but here goes.

cURL error 77: error setting certificate verify locations: CAfile: /etc/ssl/certs/cacert.pem CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

My webhost is using Cloudlinux and complains:

"'cloud linux php curl libs must be compiled', and this can be done only 
with cloudlinux team, we can't play in adventurous compilation on such 
busy prod server"

- it works in php 5.5
- it does not work in php 5.6 (and I understand why)

So I must come here and beg for tips, otherwise I'm going to have to change webhost -again- and I'd like to avoid that. They've been very good up until now. It's just that they don't seem to know how to fix this.

Has anyone encountered this before? It's been days and I'm losing income over this.
Thank you for your time and understanding

**Comment by shadowhand** [comment]
http://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url

Certificates are not properly installed, which leaves you open to MITM attacks. I do not recommend using this host if they are unwilling to help you resolve SSL problems, as it shows a blatant disregard for security.
