### ISSUE TITLE
Move documentation site into master branch?

### ISSUE THREAD

**Issue by stevenmaguire** [thephpleague/oauth2-client#559]
A [recent update by GitHub](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages) allows you to configure project documentation publication to GitHub Pages from a sub-directory instead of the `gh-pages` branch. 

Is this something we are interested in doing with this project? It may reduce the need for two pull requests when adding providers to documentation.

**Comment by ramsey** [comment]
I'm on board with that. Then we add that dir to the `.gitattributes` file for `export-ignore`. Thoughts, @shadowhand?

**Comment by shadowhand** [comment]
I concur with @ramsey.
