### ISSUE TITLE
How to get email

### ISSUE THREAD

**Issue by shinokada** [thephpleague/oauth2-client#561]
print_r($userDetails) outputs the followings. Now I am not sure how to get my email from this object. 

    League\OAuth2\Client\Provider\GoogleUser Object ( [response:protected] => 
    Array ( [emails] => Array ( [0] => Array ( [value] => myemail@gmail.com ) )
    [id] => 112938213383888696390 [displayName] => My Name 
    [name] => Array ( [familyName] => okada [givenName] => shin ) 
    [image] => Array ( [url] => https://lh3.blablant.com/-....Hp8Hg/photo.jpg?sz=50 ) ) )

**Comment by shadowhand** [comment]
```php
$email = $user->getEmail();
```

https://github.com/thephpleague/oauth2-google/blob/961825b563ea01b7bc6ef5feacae9d155ff9d5db/src/Provider/GoogleUser.php#L60-L65
