### ISSUE TITLE
2-legged Oauth2

### ISSUE THREAD

**Issue by dankarpinski** [thephpleague/oauth2-client#563]
The readme mentions only 3 legged Oauth2, is it possible to use the client for 2-legged auth between 2 servers also?
Thanks

**Comment by ramsey** [comment]
Out of the box, the GenericProvider should give you what you need to make a client-credentials grant request, which is the two-legged (server to server) flow. You'll need a client ID and client secret from the other server, and then this is all you should need to make it work:

```php
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId' => 'demoapp',
    'clientSecret' => 'demopass',
    'urlAccessToken' => 'http://example.com/token',
    'urlAuthorize' => null,
    'urlResourceOwnerDetails' => null
]);

$accessToken = $provider->getAccessToken('client_credentials');
```


The GenericProvider requires `urlAccessToken`, `urlAuthorize`, and `urlResourceOwnerDetails`, but you don't need `urlAuthorize` or `urlResourceOwnerDetails` for the "client_credentials" grant, so you may just set them to `null`, if using the GenericProvider.

Let me know if you have any other questions or if this isn't working for you.

**Comment by dankarpinski** [comment]
Thanks @ramsey, it's my first time using 2-legged auth and on closer inspection the access token request and usage is so simple that I chose against adding another dependency to the project (would be a different case if I already had the package installed).
