### ISSUE TITLE
Login with existing id_token

### ISSUE THREAD

**Issue by DonPrus** [thephpleague/oauth2-client#565]
I want to use this package as API for our mobile apps. They already have a token, and I just need to get information from social net with that token.

```php
$token = new AccessToken(['access_token' => $form->accessToken]);
$provider->getResourceOwner($token);
```

All providers works pretty well, with just small hacks.
For example vk:
```php
$this->oauth = new \J4k\OAuth2\Client\Provider\Vkontakte($config);
$response = $this->oauth->usersGet([], $token, ['user_ids' => []]);
```

But I couldn't work with Google + in that way.

https://github.com/thephpleague/oauth2-google/issues/35
I already ask a question, but nobody answered it 😞

**Comment by shadowhand** [comment]
This is specific to Google provider.
