### ISSUE TITLE
Is there something wrong about "AbstractPovider::getAuthenticatedRequest"?

### ISSUE THREAD

**Issue by slince** [thephpleague/oauth2-client#567]
Hi

I have passed"AccessToken" argument  but generated psr7 request body does not contain "access_token" parameter . I captured a http request by charles,there couldn't find any message about "access_token"
so I always got wrong tips "[API] Invalid API key or access token (unrecognized login or wrong password)".  Is this a bug? 

![image](https://cloud.githubusercontent.com/assets/3785826/18901548/89e636ae-857e-11e6-87e1-cce84c43d603.png)

second.  I’m setting up a post request. like this?
```
       $request = $this->getProvider()->getAuthenticatedRequest('POST', 'http://xxx.com/resource', $token, [
            'body' => http_build_query($parameters)
        ]);
```

**Comment by shadowhand** [comment]
`AbstractProvider` doesn't define a way to authenticate requests by itself. `GenericProvider`, and many of the 3rd party providers, use the `BearerAuthorizationTrait` to attach `Bearer` tokens to authenticated requests.

If the API you are connecting to uses `Bearer` tokens, you can use the trait to overload `getAuthorizationHeaders` and generate the appropriate header for you.
