### ISSUE TITLE
"Wrong parameters for Exception" fatal error when trying to get response with bad access token.

### ISSUE THREAD

**Issue by sm0nster** [thephpleague/oauth2-client#568]
I'm getting 
`Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /vagrant/www/vendor/league/oauth2-client/src/Provider/Exception/IdentityProviderException.php on line 36`
when I'm trying to get response from Google Api with bad access token through oauth2.

Call stack:
```
8	League\OAuth2\Client\Provider\AbstractProvider->getResponse( )	.../GoogleFitApiConnector.php:242
9	League\OAuth2\Client\Provider\GenericProvider->checkResponse( )	.../AbstractProvider.php:643
10	League\OAuth2\Client\Provider\Exception\IdentityProviderException->__construct( )	.../GenericProvider.php:216
11	__construct ( )	.../IdentityProviderException.php:36
```
![oauth2](https://cloud.githubusercontent.com/assets/16431843/18958702/ccd45762-8663-11e6-8d35-8c972cdc5804.png)

**Comment by shadowhand** [comment]
This seems like a flaw in the `GoogleFitApiConnector` (I assume it is custom?) `checkResponse()` method. The provider should be parsing the error response and passing the correct parameters to the `IdentityProviderException`.
