### ISSUE TITLE
Support HTTP Basic Auth for client authentication

### ISSUE THREAD

**Issue by jenschude** [thephpleague/oauth2-client#576]
When dealing with an OAuth-Server which is not supporting the authorization with credentials inside the request body the Abstract- or GenericProvider is not directly working.

So you have to implement a new provider which is overriding the getAccessTokenOptions method.

It would be better if the AbstractProvider would stick to the recommended behavior from [RFC 6749](https://tools.ietf.org/html/rfc6749#section-2.3.1) of sending the client credentials using the basic auth (authorization header). As you can see this section also tells that sending credentials inside the body is not recommended and should be limited to clients unable to use basic auth.

The getAccessTokenOptions could look like this:

``` php
    /**
     * Builds request options used for requesting an access token.
     *
     * @param  array $params
     * @return array
     */
    protected function getAccessTokenOptions(array $params)
    {
        $options = [
            'headers' => [
                'content-type' => 'application/x-www-form-urlencoded',
                'authorization' => 'Basic ' . base64_encode($params['client_id'] . ':' . $params['client_secret'])
            ]
        ];
        if ($this->getAccessTokenMethod() === self::METHOD_POST) {
            $options['body'] = $this->getAccessTokenBody($params);
        }

        return $options;
    }
```

As the client_id and client_secret is still inside the params array, they are also still inside the request body, so they could be removed from the params if necessary.

**Comment by ramsey** [comment]
In practice, most of the OAuth 2 servers we've encountered do not support basic authentication. Instead, they support only passing these parameters in the body. As such, our generic base package will support the most common use case. If you encounter a provider that supports basic authentication, our recommendation is to extend the `AbstractProvider` and create a new concrete provider class to support that provider.

Thanks!

**Comment by arekkas** [comment]
@ramsey basic authorization should be supported or this library is not fully spec compliant and does not work with some oauth2 provides, e.g.: https://github.com/ory/hydra

See https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by arekkas** [comment]
I was actually able to find the point in the RFC which specifically talks about not including those in the body:

>    Including the client credentials in the request-body using the two
   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
   to directly utilize the HTTP Basic authentication scheme (or other
   password-based HTTP authentication schemes).  The parameters can only
   be transmitted in the request-body and MUST NOT be included in the
   request URI

[Source](https://tools.ietf.org/html/rfc6749#section-2.3.1)

**Comment by zhenbo** [comment]
@ramsey  Definitely agree @arekkas comment on this. I hope the library can support basic authorization

**Comment by ramsey** [comment]
Please see my previous comment regarding our recommendation on how to use Basic authentication with a provider:

> Our recommendation is to extend the `AbstractProvider` and create a new concrete provider class to support that provider.

**Comment by arekkas** [comment]
While that is sufficient, wouldn't it be nice to have that provider in the standard library, as the other option is officially discouraged in the RFC? After all, this is a library in the area of cyber security, so why not adhere to the recommendations of the people who wrote it? :)

**Comment by ramsey** [comment]
I'm reopening the issue. I misunderstood the request.

If introduced, this will break BC in the `GenericProvider`, since any implementation using or extending the base library to use the `client_credentials` grant type to authorize with a provider that doesn't support Basic authentication will break. I think this is a pretty big BC break, and as noted earlier, when we released the library, we had found few providers in the wild that used Basic authentication for the `client_credentials` grant.

As an aside, there's an even greater discussion about why this is a result of the "spec" not being a true specification at all but, rather, a framework and it even acknowledges in [section 1.8](https://tools.ietf.org/html/rfc6749#section-1.8) that it is likely to produce a wide range of non-interoperable components…but I digress. :smile:

I'm open to thoughts and ideas on how we can use Basic authentication for the `client_credentials` grant type, without breaking BC.

**Comment by jayS-de** [comment]
The snippet below supports both Basic Auth as well for backwards compability the credentials as part of the body:

```php
    /**
     * Builds request options used for requesting an access token.
     *
     * @param  array $params
     * @return array
     */
    protected function getAccessTokenOptions(array $params)
    {
        $options = [
            'headers' => [
                'content-type' => 'application/x-www-form-urlencoded',
                'authorization' => 'Basic ' . base64_encode($params['client_id'] . ':' . $params['client_secret'])
            ]
        ];
        if ($this->getAccessTokenMethod() === self::METHOD_POST) {
            $options['body'] = $this->getAccessTokenBody($params);
        }

        return $options;
    }
```

**Comment by arekkas** [comment]
Please make sure to urlencode both client_id and client_secret. Not sure what the PHP equivalent is, but roughly:

```
base64_encode(urlencode($params['client_id']) . ':' . urlencode($params['client_secret']))
```

**Comment by jayS-de** [comment]
Adjusted the example with your remark @arekkas

**Comment by jayS-de** [comment]
About the URL encoding of passwort and secret I found this section:

> The client identifier is encoded using the "application/x-www-form-urlencoded" encoding algorithm per Appendix B, and the encoded value is used as the username; the client password is encoded using the same algorithm and used as the password

See [rfc6749 section 2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1)

**Comment by arekkas** [comment]
Yes, the idea behind it is that the id is urlencoded when included as a query parameter as well as in the x-www-form-urlencoded body, so it also should be encoded in the authorization header

**Comment by ramsey** [comment]
Thanks. Would anyone care to open a pull request with tests for this?

**Comment by jayS-de** [comment]
I decided to go with a configuration option for the provider, where the default value is still the auth via form params.

**Comment by ramsey** [comment]
@jenschude #664 is a potential duplicate of #653. That PR achieves Basic Auth by introducing `League\OAuth2\Client\OptionProvider\HttpBasicAuthOptionProvider`. I tend to prefer that approach, but before rejecting #664 and accepting #653, I wanted to get your thoughts to see if you think there's something in #664 that could be included in #653.

**Comment by jenschude** [comment]
I like the OptionProvider by #653 seems to be more flexible.

Maybe a test should be added for the AbstractProvider to show and test the usage of the HttpBasicAuthOptionProvider.

Another thing which could be added instead of directly instantiating the providers to have also the Option as in 664 to use some constants. But this would only be a nice to have.

**Comment by ChrisThompsonTLDR** [comment]
@ramsey Just a heads up, Reddit's API is an example of a fairly major API that requires basic authentication when requesting an access token.

**Comment by Wassasin** [comment]
The [oauth2-client implementation for Reddit](https://github.com/rtheunissen/oauth2-reddit/blob/master/src/Provider/Reddit.php#L129-L144) provides both as well.

**Comment by jenschude** [comment]
Also the implementation doesn't know what the provider accepts, at least on configuring the provider you should know it. So it's sufficient if both options can be configured. It's not necessary to send both at the same time. Btw with #653 it would be easy to implement also an OptionProvider with supports basic auth and post params

**Comment by jenschude** [comment]
Has been resolved with #653

**Comment by SaifurRahmanMohsin** [comment]
@jenschude Umm, how do I apply this with a GenericProvider? Is there documentation that shows how to pass the client_credentials grant with basic auth headers rather than in body? My code is like:
```
        $provider = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId'                => $this->clientId,
            'clientSecret'            => $this->clientSecret,
            'redirectUri'             => '',
            'urlAuthorize'            => 'https://mysite.com/oauth/authorize',
            'urlAccessToken'          => 'https://mysite.com/oauth/token',
            'urlResourceOwnerDetails' => 'https://mysite.com/oauth/resource'
        ]);
$accessToken = $provider->getAccessToken('client_credentials');
```

**Comment by jenschude** [comment]
There is a https://github.com/thephpleague/oauth2-client/blob/master/src/OptionProvider/HttpBasicAuthOptionProvider.php to authenticate using Basic Auth

**Comment by SaifurRahmanMohsin** [comment]
Ok, thanks. I was looking through the [Reddit provider](https://github.com/rtheunissen/oauth2-reddit) for a sample.

**Comment by jenschude** [comment]
And it would be something like:

`GenericProvider($options, new HttpBasicAuthOptionProvider())` when i remember it right

**Comment by jenschude** [comment]
See also https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L137

**Comment by SaifurRahmanMohsin** [comment]
@jenschude Yep, that works too. Thanks.
