### ISSUE TITLE
Issues passing data into Create call 

### ISSUE THREAD

**Issue by jackroscoe** [thephpleague/oauth2-client#579]
Hi!

I've seen other issues related to this but I'm struggling to use the examples in the documentation to successfully create a buffer post via the API. The data doesn't appear to be getting built into the request when using the following code.

Am I misunderstanding the use of the $options array?

```
// Prepare options
$scheduleOptions = json_encode(
	[
    	'profile_ids' => array(1, 2),
    	'text' => 'Test',
    	'shorten' => false,
    	'media' => [
    		'link' => 'http://test.com',
    		'description' => 'Test',
    		'title' => 'Test',
    		'picture' => 'https://example.com/img.jpg'
    	],
    	'scheduled_at' => $scheduleTimestamp->format(DateTime::ATOM)
    ]
);
// Create the request for the new post
$requestCreate = $provider->getAuthenticatedRequest(
    'POST',
    'https://api.bufferapp.com/1/updates/create.json',
    $token,
    array(
    	'body' => $scheduleOptions
    )
);
```

Thanks for any help.

**Comment by shadowhand** [comment]
I think you can pass the `json` parameter instead of the `body` parameter, without encoding `$scheduleOptions`, and it will work. Otherwise you can simply take the `$requestCreate` PSR-7 object and modify it:

```php
$requestCreate = $provider->getAuthenticatedRequest(...);
$requestBody = $requestCreate->getBody();
$requestBody->write(json_encode(...));
```

**Comment by shadowhand** [comment]
http://docs.guzzlephp.org/en/latest/request-options.html#json

Most likely your request is missing the correct `Content-Type` header, which is not automatically generated when using `body` option but is with `json` option.

**Comment by shadowhand** [comment]
Please reopen if you still have issues.

**Comment by jackroscoe** [comment]
@shadowhand Thank you for helping! I've tried your suggestions but I'm still having some trouble.

I've debugged right down into the psr7 Request class and I'm wondering if this is where things get confused: https://github.com/guzzle/psr7/blob/master/src/Request.php#L53

The `$body` var is populated on arrival but when I `var_dump()` the contents of `$this->stream` where I'm presuming I should see the contents of `$body`, nothing is there.

I notice several references to a `metadata` and `customMetaData` key in the `$options` array. Maybe I'm missing something there? I have tried to re-structure my `$scheduleOptions` array with and without the use of `json_encode()` but with no success.

I think maybe I've simply missed something fundamental in the naming or structuring of my options data since I'm only trying to do something fairly standard.

Do you have any ideas?

I really appreciate your help.

**Comment by jackroscoe** [comment]
I'm wondering also if there maybe some outdated code in the Buffer provider I'm using. Currently trying to look further into that.

**Comment by shadowhand** [comment]
@jackroscoe any luck figuring this out?

**Comment by jackroscoe** [comment]
@shadowhand Not yet. I spoke to the guys at Buffer who said to make sure that the data is posted in the form of application/x-www-form-urlencoded.  I haven't had chance to look into this yet but will do this evening.

**Comment by shadowhand** [comment]
Ah, in the case, you should be able to just drop the `json_encode` before sending.
