### ISSUE TITLE
"OAuthException: (#12) bio field is deprecated for versions v2.8 and higher"

### ISSUE THREAD

**Issue by slk500** [thephpleague/oauth2-client#586]
Reading from facebook changelog for the v2.8 (https://developers.facebook.com/docs/apps/changelog):

User Bios - The bio field on the User object is no longer available. If the bio field was set for a person, the value will now be appended to the about field.

**Comment by ramsey** [comment]
Please open this issue on the [league/oauth2-facebook](https://github.com/thephpleague/oauth2-facebook) repo. Thanks! /cc @SammyK

**Comment by SammyK** [comment]
@slk500 Make sure you're using the latest version of the package since this was fixed in [v1.4.4](https://github.com/thephpleague/oauth2-facebook/releases/tag/1.4.4).
