### ISSUE TITLE
The server returned a "406 Not Acceptable"

### ISSUE THREAD

**Issue by imranmunawar** [thephpleague/oauth2-client#592]
Final exception is this
Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in /var/www/html/testlaravel/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 561 and defined

But When I debug the code I found I am getting error in $response. before calling this function prepareAccessTokenResponse

 $response = $this->getResponse($request);

> 
<!DOCTYPE html>\n
<html>\n
    <head>\n
        <meta charset="UTF-8" />\n
        <title>An Error Occurred: Not Acceptable</title>\n
    </head>\n
    <body>\n
        <h1>Oops! An Error Occurred</h1>\n
        <h2>The server returned a "406 Not Acceptable".</h2>\n
\n
        <div>\n
            Something is broken. Please let us know what you were doing when this error occurred.\n
            We will fix it as soon as possible. Sorry for any inconvenience caused.\n
        </div>\n
    </body>\n
</html>\n

> 

Here is my complete code

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId'                => 'XXXXXXXXX',    // The client ID assigned to you by the provider
            'clientSecret'            => 'XXXXXXXX',   // The client password assigned to you by the provider
            'redirectUri'             => 'XXXXXXXX',
            'urlAuthorize'            => 'XXXXXXX/oauth/v2/auth',
            'urlAccessToken'          => 'XXXXXXXXXX/oauth/v2/token',
            'urlResourceOwnerDetails' => ''
        ]);

        if (!isset($_GET['code'])) {

            $authorizationUrl = $provider->getAuthorizationUrl();
            //return Redirect::to($authorizationUrl);
            header('Location: ' . $authorizationUrl);
            exit;

        }else{
            //dd($_GET['code']);
            try {
                  $accessToken = $provider->getAccessToken('authorization_code', [
                      'code' => $_GET['code']
                  ]);
                  echo $accessToken->getToken() . "\n";
            }catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
                  exit($e->getMessage());
            }
        }

**Comment by imranmunawar** [comment]
I am getting code but when try to get access token then it show error
$accessToken = $provider->getAccessToken('authorization_code', [
                  'code' => $_GET['code']
              ]);

**Comment by ramsey** [comment]
It sounds like the authorization server you're using is expecting something that the GenericProvider class doesn't support. You may need to create your own provider class that extends AbstractProvider and follows the rules of the authorization server. It's hard to tell, without knowing more details about what service you are trying to use.

**Comment by shadowhand** [comment]
Closing this, as it seems like something specific to a single provider.
