### ISSUE TITLE
[Discussion / Feature Request]: Access token expiration race condition.

### ISSUE THREAD

**Issue by trip-somers** [thephpleague/oauth2-client#593]
I've googled and read fairly extensively on this issue and come up basically empty. The only example I can find that even remotely addresses having an expired access token is the example in this project's README.md file. (That example is then proliferated through several official and third-party client packages.)

For reference, this example is what I'm talking about:

```
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'demoapp',    // The client ID assigned to you by the provider
    'clientSecret'            => 'demopass',   // The client password assigned to you by the provider
    'redirectUri'             => 'http://example.com/your-redirect-url/',
    'urlAuthorize'            => 'http://brentertainment.com/oauth2/lockdin/authorize',
    'urlAccessToken'          => 'http://brentertainment.com/oauth2/lockdin/token',
    'urlResourceOwnerDetails' => 'http://brentertainment.com/oauth2/lockdin/resource'
]);

$existingAccessToken = getAccessTokenFromYourDataStore();

if ($existingAccessToken->hasExpired()) {
    $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()
    ]);

    // Purge old access token and store new access token to your data store.
}
```

This example is great when your token has expired prior to initializing your provider, but it is useless if it expires after initialization but before the script/request makes its last OAuth2 request.

The situation I'm dealing with is a cron that runs every 5 minutes for several seconds (due to API calls). My access token expires every 3600 seconds, so every 12th execution of the cron runs into a potential race condition in which the token is valid prior to execution but can expire during execution.

The best thoughts I've had on this so far amount to adding the ```$existingAccessToken->hasExpired() >> refresh``` sequence somewhere in the ```getAuthenticatedRequest() >> getResponse() >> sendRequest()``` sequence of the AbstractProvider class.

That would narrow the expiration race condition to an extremely small window, however it leaves open a minor but expensive race condition if 1 of 2+ concurrent scripts refreshes the token. This condition essentially would result in each concurrent script refreshing the token for each request after the first refresh (since each refresh would invalidate previous access tokens).

That race condition can be beaten by also putting the ```getAccessTokenFromYourDataStore()``` call in with the ```hasExpired()``` check. Depending on how the token is stored, this may or may not be an expensive addition.

My current solution is none of the above since I didn't want to start hacking into this package. Instead, I am artificially expiring my token early so that it refreshes ahead of time. (NOTE: This does not solve the concurrency issue described above.)

Does anyone have thoughts about this? I'm interested in what others have to say.

**Comment by AlbinoDrought** [comment]
Libraries I have come across (Google API?) have worked around this issue by giving ~30 seconds of "leeway", as in:

`$expired = ($token['time_expired'] - 30) < time();`

If the above statement is false, you would refresh your token. Otherwise, you have a perfectly nice token that will last for around 30 seconds.

This could be done by overriding `AccessToken`, and changing `hasExpired()` to something like:

    public function hasExpired()
    {
        $expires = $this->getExpires();

        if (empty($expires)) {
            throw new RuntimeException('"expires" is not set on the token');
        }

        return ($expires - 30) < time();
    }

Alternatively, you could manually check if `getExpires() - 30 < time();`.

(Of course, you probably want to use a constant instead of 30 in both cases)

**Comment by trip-somers** [comment]
That's not a terrible idea. The drawback is obviously that it has a limit to it. If this particular script runs for 31 seconds, we get back into that "uh-oh" territory (or 60 vs 61, etc.).

I feel like the ideal solution is to check access token expiration prior to each request as opposed to the instantiation of the client. If you can guarantee that the client won't "live" for longer than a certain period of time, instantiation is okay; and yeah, you could re-instantiate the client during a long-running script; but a native auto-refresh seems, to me at least, to be the most elegant.

**Comment by trip-somers** [comment]
The API I'm using is actually taking a LONG time in production (Adobe Sign, c'mon...), so this is happening like clockwork every hour.

I came up with a fairly simple extension to handle this. I extended getAuthenticatedRequest() to use this basic pattern:

```
    public function getAuthenticatedRequest($method, $url, $token, array $options = [])
    {
        // refresh access token if necessary
        if ( ! $token = $this->fetchTokenFromStorage() )
        {
            $accessToken = $this->getAccessToken('refresh_token', [
                'refresh_token' => cache('adobe_sign_refresh_token')
            ]);

            $this->saveTokenToStorage($accessToken);

            $token = $accessToken->getToken();
        }

        return parent::createRequest($method, $url, $token, $options);
    }
```

The major downside to this is that getAuthenticatedRequest() is already expecting a token to have been retrieved and passed in. If retrieving the stored token is expensive, this is kind of a pain-in-the-ass execution, but it solves both the race condition (by refreshing right before the request) and the concurrency issue (by fetching the latest token from storage right before request).

**Comment by kevindierkx** [comment]
@trip-somers Store the access_token in local storage including it's expiration date and renew it using a second cron? This way retrieval of the token is quick, and renewal is (kinda) non blocking.

The 'I have a 30 second leeway it might fail at 31' is something you certainly should consider. For example you could also try gracefully recovering the failed 'job'. ie use a queue or something.

However I don't think this should be part of a protocol abstraction.

**Comment by trip-somers** [comment]
I implemented this earlier today to great effect so far. The solution I posted this morning might have worked, but I changed the final $token value to come from the local storage while debugging a seconds-vs-minutes expiration calculation issue.

Since I'm using Laravel's cache manager, the fetching is actually fairly inexpensive.

```
    public function getAuthenticatedRequest($method, $url, $token, array $options = [])
    {
        // refresh access token if necessary
        if ( ! $token = $this->fetchAccessTokenFromStorage() ) // returns null if expired
        {
            $accessToken = $this->getAccessToken('refresh_token', [
                'refresh_token' => $this->fetchRefreshTokenFromStorage()
            ]);

            $this->saveTokenToStorage($accessToken);

            $token = $this->fetchAccessTokenFromStorage();
        }

        return parent::createRequest($method, $url, $token, $options);
    }
```

I'm still worried about the concurrency/timing, but the only way to really tackle that, as far as I can tell, would be to use a queue as you suggest.

I've come up with a couple of questions while dealing with this, too.

1. Why does getAuthenticatedRequest() expect a token to be passed in instead of pulling from something like $this->accessToken?

2. Is there a reason that there isn't already some kind of an 'auto-refresh' option in the AbstractProvider class? I'm thinking essentially something like a boolean setting/option that tells the current instance whether or not to refresh the token automatically. It seems like a no-brainer to me, so I'm curious about the reasons for excluding something like that.

**Comment by jamesgraham** [comment]
@trip-somers I came across the exact same problem and implemented similar. Be careful with providers like Google who don't return the refreshToken when you request a new token! I was overwriting refresh_token with null.

I agree with your question 2 and would like to know an answer.

Are you caching fetchAccessTokenFromStorage()? I am storing this in Redis and it works well.

**Comment by trip-somers** [comment]
@jamesgraham I'm not using Redis, but yes. In my case "fromStorage" actually means "from cache". I also got tripped up on the missing refresh token; exact same thing -- expected new refresh token, wasn't sent.

**Comment by lukaszmakuch** [comment]
@trip-somers, Google returns a new refresh token if the "approval_prompt" parameter is set to "force".

When it comes to getting new tokens, the best stategy I found is to let it fail. If I get an error saying the access token has expired, I try to obtain a new one using the refresh token. What's very important is to remember this may fail as well. The refresh token may be expired or invalidated. In such a situation the user should be asked to re-authenticate. However, if I get a new access token, I can simply retry the request.

**Comment by shadowhand** [comment]
Looks like you have found a working solution. If you would like to propose a feature for this, please open a new issue.

**Comment by trip-somers** [comment]
The request is mentioned in 3 of my comments: an auto-refresh option in the AbstractProvider class. I even gave code examples for how it can be implemented.

**Comment by bencresty** [comment]
It's been years since this thread was closed, but it seems like there's still no auto-refresh built into the lib to auto-refresh the token. 

While that's what we're after in basically each project that's having more than a single data-request to an oauth provider.  For each project needing to refresh tokens we are now building the same extended behaviour code on top of the lib in our projects. It's not much code, but it's rewriting the same code every time and new users need to figure this out first.
So it would be nice if this could be build into the lib itself!

So for me a +1 too for having an auto-refresh option in the lib itself.
