### ISSUE TITLE
Refresh Token Error

### ISSUE THREAD

**Issue by Simone86sp** [thephpleague/oauth2-client#594]
Hi,
I'm trying to refresh the token but does not work.

I fetch the token from my db and run this code:

`$accessToken = $token; //the token stored in my db`
`if ( $accessToken -> hasExpired() ) {`
`    $accessToken = $provider -> getAccessToken('refresh_token', [`
`    'refresh_token' => $accessToken -> getRefreshToken()`
`    ]);`
`}`

I get this error:
**Fatal error: Uncaught Error: Call to a member function hasExpired() on string in /var/www/vhosts/site.it/httpdocs/api/app.php:73 Stack trace: #0 {main} thrown in /var/www/vhosts/site.it/httpdocs/api/app.php on line 73**

Any tips?

**Comment by trip-somers** [comment]
It looks like you are probably storing and retrieving the access_token string rather than the object. If you want to run ->hasExpired, you need to run it on the object.

You'll have to persist the object instead of just the token string.

**Comment by foxpcteam** [comment]
@trip-somers
Hi, i have the same problem.
any code example to make this work?

**Comment by trip-somers** [comment]
@foxpcteam I've had the alert from your comment in my inbox for two weeks, and I haven't had time to dig out the code I used. I plan to do it and update this issue, when I get a chance.

**Comment by shadowhand** [comment]
@foxpcteam you can `json_encode` the token, store it, and then load a new one with:

```php
$token = $db->getToken(...); // replace with something to load the token JSON
$token = new AccessToken(json_decode($token));
```

**Comment by fjeddy** [comment]
As a side note, as @shadowhand's answer is just a pure guess on what's wrong. This error occurred for me when no expire_in timestamp was present (It was set to 0).

Double check that you actually have an timestamp.
