### ISSUE TITLE
What would be best way to add a new getAccessToken-like method?

### ISSUE THREAD

**Issue by chx** [thephpleague/oauth2-client#595]
I am writing a PHP client to [Smartsheet](https://smartsheet-platform.github.io/api-docs/#oauth-flow) and potentially I'd like to release it as a provider.

My calls look like this
```
      $access_token = $provider->getAccessToken('authorization_code', [
        'code' => $authorization_code,
        'hash' => hash('sha256', OauthStart::CLIENT_SECRET . '|' . $authorization_code),
      ]);
      $access_token = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $refresh_token,
        'hash' => hash('sha256', OauthStart::CLIENT_SECRET . '|' . $refresh_token),
      ]);
```

So one simple signature would be `$provider->someMethod($grant, $grant_value, $secret, $additional_options)` and then `someMethod` could call `getAccessToken` as necessary. Is this acceptable in an official provider? What a good method name would be? Two methods maybe? `getTokenFromAuthorizationCode($authorization_code, $secret, $additional_options)` and `refreshToken($refresh_token, $secret, $additional_options)`?

**Comment by stevenmaguire** [comment]
What is it exactly that you are trying to accomplish? One method to retrieve the accessToken OR the refreshToken?

**Comment by chx** [comment]
Well, `GenericProvider` does that. I am not sure whether a single method or two methods would be best.

**Comment by chx** [comment]
Well, GenericProvider has a single method which I am calling as above, as described in the `README` -- but I would need a new method to allow for passing in the secret. I am not sure whether a) single method or b) two methods would be best and what method names.

**Comment by ramsey** [comment]
@chx, did you ever figure out an answer to your question? I'm curious what you did to solve this.

**Comment by chx** [comment]
I ... gave up on writing a provider. Might pick it up again but for now, I do not have many calls to oauth and so no provider.

**Comment by ramsey** [comment]
If you decide to give it another go, let us know.
