### ISSUE TITLE
 Nothing to install or update Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by Nerdietony** [thephpleague/oauth2-client#599]
Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by shadowhand** [comment]
Looks like you are using an old version of oauth2-client. Version 1.x+ uses `guzzlehttp/guzzle`.
