### ISSUE TITLE
Following redirects while maintaining authorization.

### ISSUE THREAD

**Issue by stevenmaguire** [thephpleague/oauth2-client#600]
I recently encountered some odd behavior with the Nest API in which the service was returning a response with `307` redirect status and a new url in the `Location` header. 

One user of the `oauth2-nest` client spotted the issue and [began researching on the Nest forums with a thread](https://nestdevelopers.io/t/unauthorized-with-seemingly-valid-access-token/556). That thread surfaced a [similar issue with the `requests` python module](https://github.com/kennethreitz/requests/issues/2949). 

In the end, Nest was sending back a redirect and Guzzle, in its default configuration, was following the redirects without the `Authorization` header and therefore returning an unauthorized response.

I have implemented a solution directly within the `oauth2-nest` client as a trait that seeks to override the `sendRequest` method in the `League\OAuth2\Client\Provider\AbstractProvider`. 

[https://github.com/stevenmaguire/oauth2-nest/blob/master/src/Tool/ProviderRedirectTrait.php](https://github.com/stevenmaguire/oauth2-nest/blob/master/src/Tool/ProviderRedirectTrait.php)

I was on the fence about implementing this solution in the client package because it only seems to cause frustration when using the library to send authenticatedRequests; it does not hinder the obtaining of access tokens, and I do draw a line between the library being an OAuth2 authorization package and not an API wrapper. My instinct was to not implement a solution and help the user understand how they may build a little bit of code themselves to make their own HTTP calls with the AccessToken obtained by the package. I decided to implement the solution in the package because it had a relatively small code footprint and removes a roadblock from the client's "Hello World" demo.

My question for the group here is simple. Do you see value in moving this solution into the core client as an optional tool for other client implementations that _may_ run into this problem?

**Comment by shadowhand** [comment]
I'm in favor of this, as it seems like it will create a more robust solution for providers following strict HTTP semantics.

**Comment by stevenmaguire** [comment]
Ok, thanks for that! If there is the beginnings of "this might be a good idea" I will submit a PR to capture any implementation details conversation. I just didn't want to take the time to submit the PR if even one maintainer was like "that's stupid! no thank you!" 😄
