### ISSUE TITLE
[ISSUE PHP <7] Using random_bytes() ... 

### ISSUE THREAD

**Issue by vincent-guesnard** [thephpleague/oauth2-client#603]
Hello,

random_bytes function is a PHP7 function only. Most of us are still under PHP 5.X. Please, we need a downgrade or something which run under PHP 5.X. (Debian 8 official apt)

I'll downgrade for 1.4.2.

Thank you very much.

**Comment by vincent-guesnard** [comment]
There is this : https://github.com/paragonie/random_compat according to http://php.net/manual/en/function.random-bytes.php for PHP5 backward compatibility

I have not tested it yet, will do it tomorrow.

**Comment by ramsey** [comment]
Version 2.0.0 is already using paragonie/random_compat. Take a look at our `composer.json` [here](https://github.com/thephpleague/oauth2-client/blob/master/composer.json#L11). When you updated or installed from Composer, it should have grabbed paragonie/random_compat and placed it in your `vendor/` folder.

If you're seeing any errors after upgrading to 2.0.0, please post them here. Thanks!

**Comment by ramsey** [comment]
Our 2.0.0 build is passing on PHP 5.6 here, so I know it's using the random_compat library properly: https://travis-ci.org/thephpleague/oauth2-client/builds/191533970

**Comment by vincent-guesnard** [comment]
You are right. I miss it while checking your composer.json.

Thanks you, have a nice day :)
