### ISSUE TITLE
Mcrypt deprecated in PHP 7.1

### ISSUE THREAD

**Issue by krb19xx** [thephpleague/oauth2-client#604]
Hi. The oatih2-client uses Mcrypt, and Mcrypt is deprecated in PHP 7.1.x and will be removed from the PHP core in 7.2. Is there a fix or on the way a work-around for this?

**Comment by shadowhand** [comment]
I believed this has been resolved by version 2.0.0, see #583.

**Comment by ramsey** [comment]
Agreed. This should no longer be an issue in 2.0.0, as the compat library for `random_bytes()` no longer uses mcrypt. Please upgrade to 2.0.0 on PHP 7.1.
