### ISSUE TITLE
Use of random 'state' string in between authentication and authorization requests

### ISSUE THREAD

**Issue by holtkamp** [thephpleague/oauth2-client#611]
When **not** providing an ```$options['state']``` to ```AbstractProvider::authorize($options)``` a random string gets generated automatically to use as ```state``` parameter => great, less responsibility for user-land code: let's use that!

However... since the ```AbstractProvider::authorize()``` [redirects and exists directly](https://github.com/thephpleague/oauth2-client/blob/3859d435d6b82ef02f4b65d9547fd35da95826fd/src/Provider/AbstractProvider.php#L378-L379), there is no way to acquire the generated ```state``` value to store in a session variable...

Since ```AbstractProvider::getRandomState()``` is a protected function, this kind of forces me to either generate the random string with own code:

```php
$options['state'] = 'myCrazyRandomString'; //generate a random state with own implementation
$_SESSION['oauth2state'] = $options['state'];
$provider->authorize($options);
```

or redirect the request with own code:

```php
$redirectUrl = $provider->getAuthorizationUrl();
$_SESSION[`oauth2state'] = $provider->getState(); //By now the provider has generated a random string in the state
header('Location: ' . $redirectUrl);
exit();
```

Is this a correct observation? Might it be an option to make ```AbstractProvider::getRandomState()``` public, so we can use the functionality to create a random string instead of relying on our own 'idea' of random strings?

**Comment by ramsey** [comment]
Either of these is a correct approach. I usually do the latter:

``` php
$authUrl = $provider->getAuthorizationUrl();

// Use $provider->getState() to store the state to session, using my
// framework's session management tools.

// Either use my framework's redirection tools to redirect to $authUrl or
// pass $authUrl as a template variable and ask the user to click a link
// or button to authorization (the target of that link/button being the
// $authUrl.
```

**Comment by ramsey** [comment]
`AbstractProvider::getRandomState()` returns a different random string each time it is called. Exposing it might cause confusion, since devs could think the string it returns is the same one that was attached to the authorization URL, which it's not. :-)

**Comment by holtkamp** [comment]
@ramsey thanks for the swift and clear answer. 

Ok, personally I do not really like 'low level' functions like 

```php
header('Location: ' . $redirectUrl);
exit();
```

but I guess that is a matter of style. I would say the function name ```getRandomState()``` kind of suggest a (new) random string over and over, but hey, again that might just me. 

Thanks again, closing issue!
