### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by alcohol** [thephpleague/oauth2-client#613]
Hey I wrote a provider for the CCP CREST API (https://github.com/alcohol/oauth2-eveonline).

After submitting it for review/feedback on [r/evetech](https://www.reddit.com/r/evetech), a user left the following comment: https://www.reddit.com/r/evetech/comments/5r7gt1/php_70_oauth2_client/dd512op/

Wonder if you have any opinion/feedback to this?

**Comment by shadowhand** [comment]
I don't see a security risk here, we're just generating 2x the amount of random bytes and then truncating it. That said, I think the correct thing to do would be to reduce the amount of bytes generated to match the expected length of output.

Any thoughts @ramsey ?
