### ISSUE TITLE
Using old library version due on `5.5` compability

### ISSUE THREAD

**Issue by hellboy81** [thephpleague/oauth2-client#619]
The most of our customers are using  PHP `5.5` and above.

Is there possible to use in production mode older library version compatible with 

Where can I find last travis build and library version compatible and tested with this php version?

**Comment by shadowhand** [comment]
Version 1.x is compatible with PHP 5.5.

I strongly recommend upgrading to PHP 5.6, as 5.5 is [no longer supported](http://php.net/eol.php).

**Comment by ramsey** [comment]
The 2.x series is when we bumped the PHP requirement to `>= 5.6`. To support customers using PHP 5.5, use the version constraint `~1.4`:

```
composer require league/oauth2-client=~1.4
```

You may find all our releases here: https://github.com/thephpleague/oauth2-client/releases. Our build history is available on Travis here: https://travis-ci.org/thephpleague/oauth2-client.

**Comment by hellboy81** [comment]
>I strongly recommend upgrading to PHP 5.6, as 5.5 is no longer supported.

I should say it to our customers. But not all of them can it.
