### ISSUE TITLE
thephpleague/oauth2-client on openhub

### ISSUE THREAD

**Issue by hellboy81** [thephpleague/oauth2-client#620]
Is there `thephpleague/oauth2-client` page on `openhub`? 

I should provide for our customers estimated cost info for development of oauth2 client with all implemented clients.

Some of them cannot understand if I try develop Facebook Client myself I got problems with Google Client and other  auth services.

I can find only info [on deprecated HA libraray](https://www.openhub.net/p/hybrid_auth/estimated_cost)

**Comment by shadowhand** [comment]
I'm open the idea of having a page on OpenHub. Won't be adding it myself though.

**Comment by peterdd** [comment]
Ah, I remember 0.12.1 php5.4+. 0.3 for php5.3 with this typo filename fix:

> # fix for oauth2-client v0.3 ( the last version that works with php5.3.* )
> mv vendor/league/oauth2-client/src/Grant/AuthorizationCode.php vendor/league/oauth2-client/src/Grant/Authorizationcode.php

**Comment by ramsey** [comment]
@peterdd, did you mean to leave your comment on #661?

**Comment by ramsey** [comment]
I can't move a comment, but no worries. :smile:
