### ISSUE TITLE
Not accepting Self Signed SSL

### ISSUE THREAD

**Issue by lotharthesavior** [thephpleague/oauth2-client#627]
Hi,

I'm not sure if the option verify for the GenericProvider object is working properly. Is there any direction of this implementation with the configuration to accept self-signed ssl certificates?

**Comment by shadowhand** [comment]
The [verify option can only be turned off when using `proxy`](https://github.com/thephpleague/oauth2-client/blob/56f6860e8773a2fc2bb4524f344d04bc28bb1c09/src/Provider/AbstractProvider.php#L142-L145). This is done for security reasons. If you need to bypass this, you can [provide a fully constructed `httpClient`](https://github.com/thephpleague/oauth2-client/blob/56f6860e8773a2fc2bb4524f344d04bc28bb1c09/src/Provider/AbstractProvider.php#L120-L126) option.
