### ISSUE TITLE
Set up client_credentials with passport laravel 5.4 error

### ISSUE THREAD

**Issue by hainv** [thephpleague/oauth2-client#628]
Hi,
Sorry for my English not good. However, when I using client_credntials with passport and I get error:
```
[message] => The resource owner or authorization server denied the request. 
[hint] => Missing "Authorization" header
```
Below is my project file that I've been set up.
My Kernel.php file:
```

protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
           // \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
        ],
        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

```

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        //'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'scopes' => \Laravel\Passport\Http\Middleware\CheckScopes::class,
        'scope' => \Laravel\Passport\Http\Middleware\CheckForAnyScope::class,
        //'client_credentials' => \Laravel\Passport\Http\Middleware\CheckClientCredentials::class,
        'client_credentials' => \App\Http\Middleware\CheckClientCredentials::class,
    ];

My config\auth.php file:
```
`'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
        'admin' => [
            'driver' => 'session',
            'provider' => 'admin',
        ],
    ],`
```

My App\Providers\AuthServiceProvider file:
```
public function boot()
    {
        $this->registerPolicies();
        Passport::routes();
        Passport::tokensExpireIn(Carbon::now()->addDays(15));
        Passport::refreshTokensExpireIn(Carbon::now()->addDays(30));
        //Passport::enableImplicitGrant();
        Passport::tokensCan([
            'users' => 'Action with users',
            'bds' => 'Action with bds',
        ]);
        //
    }
```

My route:
```
Route::middleware('client_credentials')->get('/test', function () {
	return response()->json([ 'status' => 'ok' ], 200);
});
Route::any('/getToken', function(){
	$guzzle = new GuzzleHttp\Client;

	$response = $guzzle->post('http://localhost/oauth/token', [
		'form_params' => [
			'grant_type' => 'client_credentials',
			'client_id' => 'id',
			'client_secret' => 'secret',
			'scope' => 'users bds',
		],
	]);

	$obj = \GuzzleHttp\json_decode($response->getBody());
	$token = $obj->{'access_token'};

	echo $token;

	$guzzle = new GuzzleHttp\Client;
	$response = $guzzle->request('GET', 'http://localhost/test', [
		'headers' => [
			'Accept' => 'application/json',
			'Authorization' => 'Bearer '.$token,
			'Scope' => 'users bds',
		],
	]);
	echo $response->getStatusCode();
	var_dump($response->getHeader('content-type'));
	echo $response->getBody();
});
```

Anyone to help?

**Comment by shadowhand** [comment]
It doesn't look like you are using this library at all, so I don't know how we can help you.
