### ISSUE TITLE
All exceptions are not catched in the method sendRequest of class AbstractProvider

### ISSUE THREAD

**Issue by JuJuDropThor** [thephpleague/oauth2-client#631]
Hi,

You catch only GuzzleHttp\Exception\BadResponseException.

For example, GuzzleHttp\Exception\RequestException are not catched. So if I had that kind of error, I just have a blank page :/

Could you catch all exceptions that could be thrown please ?

**Comment by shadowhand** [comment]
Ultimately, it is up the user to catch exceptions and deal with them accordingly.The reason that we catch `BadResponseException` is because we can get a response with an error code. Catching `RequestException` will not give us a response. If we did catch `RequestException`, what would we do with it?

**Comment by JuJuDropThor** [comment]
OK I understand.

Could you update the phpdoc then ? Because we don't have any mention of what exception could be thrown ? 

We can't catch all exceptions with a single catch(\Exception $exception). That's not a good practice.

**Comment by shadowhand** [comment]
All Guzzle exceptions implement [`GuzzleException`](https://github.com/guzzle/guzzle/blob/6.0.0/src/Exception/GuzzleException.php). You may want to use a narrower scope than that.

**Comment by JuJuDropThor** [comment]
Oh yes I can catch GuzzleException but the real problem is that your phpdoc doesn't mention exceptions thrown by your code. 

We can't check all code in each method to search what exceptions are thrown because your phpdoc is incomplete.

**Comment by shadowhand** [comment]
It's not standard practice to document exceptions that might be thrown in collaborating code. The `sendRequest()` method does not throw any exceptions itself.
