### ISSUE TITLE
change outbound ip

### ISSUE THREAD

**Issue by SomeoneCares11** [thephpleague/oauth2-client#642]
Hi,

in curl we can change the outbound ip but i don't know where i can find that.

example for curl 
https://stackoverflow.com/questions/2425651/select-outgoing-ip-for-curl-request

**Comment by shadowhand** [comment]
🤔 Guzzle [allows overloading](http://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options) so you would need to overload [the `httpClient`](https://github.com/thephpleague/oauth2-client/blob/b83e8d4a4155ed7551aca80940084bb59dfe7a09/src/Provider/AbstractProvider.php#L120-L126) option:

```php
$options['httpClient'] = new Guzzle\Client([
    'curl' => [
        CURLOPT_INTERFACE => 'xxx.xxx.xxx.xxx'
    ]
]);

$provider = new FooProvider($options);
```
