### ISSUE TITLE
Unused Function Arguments - Any reason for them to exist?

### ISSUE THREAD

**Issue by faustbrian** [thephpleague/oauth2-client#643]
Is there any reason for those function arguments to exist since they are not used in any way and have no default values which means it is required to always hand in empty data to just get the function to work.

https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/GenericProvider.php#L163
https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/GenericProvider.php#L171
https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L248
https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L256

**Comment by shadowhand** [comment]
Some providers use those arguments to modify the request URL based on token values.
