### ISSUE TITLE
Can you please update composer version it has outdated code-base

### ISSUE THREAD

**Issue by cparadigm** [thephpleague/oauth2-client#644]
When running composer it brings down version different from what I see in GitHub. Can you please update repository on Packagist (I assume). I can't install them from different sources as Composer auto-loading functionality breaks.

**Comment by ramsey** [comment]
The latest version is 2.2.1. This is up-to-date in Packagist: https://packagist.org/packages/league/oauth2-client#2.2.1

What version is Composer downloading for you, and is it possible you are using a provider package that is locked to an earlier version of league/oauth2-client?

**Comment by cparadigm** [comment]
I don't think that there any locking happening I am pulling a fresh composer repository. Vendor directory didn't exist before. It does not have GenericProvider class.

**Comment by shadowhand** [comment]
@cparadigm what version of PHP are you using? We've required PHP >= 5.6 since version 2.0.0.

**Comment by cparadigm** [comment]
Yep, that was the problem. Server is running 5.4. Thanks for the help!
