### ISSUE TITLE
How to get authenticated login user detail after successfully logged in?

### ISSUE THREAD

**Issue by ekhlascyblance** [thephpleague/oauth2-client#651]
Hi
 I got successfully logged in and got access token in response see screenshot [http://prntscr.com/gcrwli](http://prntscr.com/gcrwli)
but i dont khow how to get logged in user detail.

i used this  **$resourceOwner = $provider->getResourceOwner($accessToken);** method but not success.

please do help to out from this. 
this will do complete my task.  i have been working in Azure since 1 or month.  i am stuck now.

Thanks, 
Ikhlas

**Comment by shadowhand** [comment]
What error do you get?

**Comment by ekhlascyblance** [comment]
400 | Request_InvalidDataContractVersion | The specified api-version is invalid. The value must exactly match a supported version.
-- | -- | --

**Comment by shadowhand** [comment]
That looks like a problem with the Azure provider or with the request you are making.

**Comment by ekhlascyblance** [comment]
Yes your absolutely right.
This is a azure problem
I am able to solved it by my self.
Now I got the  desired results . You can close this issue.
Thanks
Ikhlas
