### ISSUE TITLE
Allow another HTTP client

### ISSUE THREAD

**Issue by ElGigi** [thephpleague/oauth2-client#652]
Hi,

Can you allow to set another HTTP Client to the library ?
You implement already PSR-7, and you just have  #to implement https://github.com/php-http/httplug for example.

Regards.

**Comment by stevenmaguire** [comment]
This topic has been discussed at length. https://github.com/thephpleague/oauth2-client/pull/538

**Comment by Soullivaneuh** [comment]
@ElGigi Please see #685
