### ISSUE TITLE
RedirectUri and redirect_uri

### ISSUE THREAD

**Issue by thibauds** [thephpleague/oauth2-client#656]
Hi,

I was setting the ```redirectUri``` option on the ```Client\Provider``` constructor, everything was fined. Then I changed my logic and set in on the ```getAuthorizationUrl```, I realized that this time it was named ```redirect_uri```. I do not know if there is a reason for that but it might be seen as inconsistent ?

Nevertheless, I am very happy with the library so thank you for your good work ;)

**Comment by ramsey** [comment]
Thanks for pointing this out. I can see how it might seem inconsistent. In general, our standards for array properties and PHP class properties is to use `lowerCamelCase` styling. However, in the case of preparing URLs for OAuth2, the query string parameters must be written as `redirect_uri`.

What you've pointed out here is where one of those differences comes into play. In our constructor, we use `redirectUri` in the array passed in (of "named parameters"), according to the standards of the library. In `getAuthorizationUrl()`, the options array you pass in are added to the query string parameters of the URL that is returned, so if you pass the redirect URI as an option, it must be styled as `redirect_uri`.

Maybe we can do some better explaining of this difference. :smile:

Thanks for using the library!
