### ISSUE TITLE
Error on GrantFactory

### ISSUE THREAD

**Issue by fischmanr** [thephpleague/oauth2-client#657]
Not sure if its the GrantFactory that has the issue or the provider I'm trying to use, but I see the problem with both the networg Azure Oauth client and Steven Maguire's Microsoft client.
Error I see is:
[11-Sep-2017 18:23:40 America/Denver] PHP Parse error:  syntax error, unexpected
 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or
'{' or '$' in /#####/#######/public_html/azuretest/vendor/league/oauth2-client/
src/Grant/GrantFactory.php on line 85

**Comment by ramsey** [comment]
What version of PHP are you using and what version of league/oauth2-client is installed?

Run the following from your command line and let me know the output.

```
php -v
composer licenses | grep "league/oauth2-client"
```

Thanks!

**Comment by MelonCola** [comment]
I'm currently experiencing this same problem.(Yes I know it's been a year)
`
PHP 7.2.13 (cli) (built: Dec  8 2018 12:11:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
`

`league/oauth2-client       2.4.1     MIT`

**Comment by mxdpeep** [comment]
public function isGrant($class)
    {
        return is_subclass_of($class, *AbstractGrant::class*);
    }


which provider do you use with the client?


s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by MelonCola** [comment]
https://github.com/wohali/oauth2-discord-new

**Comment by mxdpeep** [comment]
this is weird as AbstractGrant::class
always translates to AbstractGrant

s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by ramsey** [comment]
A similar problem at the same line was reported in #787. I'm not sure what would cause it, other than using a version of PHP earlier than PHP 5.6. If you're still having this issue, please re-open this ticket.
