### ISSUE TITLE
[Proposal] AccessToken add serialize and deserialize functions

### ISSUE THREAD

**Issue by MircoBabin** [thephpleague/oauth2-client#659]
AccessToken is missing serialize to string and deserialize from string fuctionality.

I have to persistent an AccessToken in a database. Because it will be used later in time and not at the moment of acquiring it. 

At the moment I have to do the serialization myself. It would be better if AccessToken provided functions for this.

```php
    /**
     * Serialize an AccessToken for persistance
     *
     * @return string
     */
    public function serializeAccessToken(Accesstoken $accessToken)
    {
        return $accessToken->getToken();
    }
        
    /**
     * Deserialize a serialized AccessToken
     *
     * @return AccessToken
     */
    public function deserializeAccessToken(string $serializedAccessToken)
    {
        return new AccessToken(['access_token' => $serializedAccessToken]);
    }
```

**Comment by ramsey** [comment]
There are already a few ways to do this without the need for new methods.

Here's one way using PHP's built-in `serialize()` and `unserialize()` functions:

``` php
$token = new League\OAuth2\Client\Token\AccessToken([
    'access_token' => 'foo',
    'expires_in' => 3600,
    'refresh_token' => 'bar',
    'resource_owner_id' => 1234,
    'foobar' => 'some other value',
]);

$tokenSerialized = serialize($token);
// O:38:"League\OAuth2\Client\Token\AccessToken":5:{s:14:"\0*\0accessToken";s:3:"foo";s:10:"\0*\0expires";i:1515821078;s:15:"\0*\0refreshToken";s:3:"bar";s:18:"\0*\0resourceOwnerId";i:1234;s:9:"\0*\0value

$tokenUnserialized = unserialize($tokenSerialized);

echo $tokenUnserialized->getToken();
```

You could store the serialized string in a database and, when you retrieve it, you could `unserialize()` it.

However, an even better approach would be to use a serialized format that isn't specific to a PHP object. You could JSON-encode the object:

``` php
$tokenJson = json_encode($token);
// {"foobar":"some other value","access_token":"foo","refresh_token":"bar","expires":1515821684,"resource_owner_id":1234}

$tokenDecoded = new League\OAuth2\Client\Token\AccessToken(
    json_decode($tokenJson, true)
);

echo $tokenDecoded->getToken();
```

You can store that JSON-encoded value somewhere and then decode it into a PHP array to populate the `AccessToken` object. This is a very portable approach, and it's what I would recommend.

Let us know if you have any other questions.
