### ISSUE TITLE
Missing official providers list

### ISSUE THREAD

**Issue by wesamly** [thephpleague/oauth2-client#670]
If you check [Third-Party Providers](https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md) page, it provides [first party providers](https://github.com/thephpleague/oauth2-client/blob/master/providers/league) page which is leads to Page not found.

I was searching for Google provider, first I thought it was not available until I searched.

Thank you.

**Comment by wesamly** [comment]
For now you can search https://github.com/thephpleague for oauth2- and it will list all repositories starting with oauth2- like [oauth2-google](https://github.com/thephpleague/oauth2-google)

**Comment by stevenmaguire** [comment]
These markdown files are used to generate the documentation site at http://oauth2-client.thephpleague.com

The links in question function appropriately on that site...

**Comment by wesamly** [comment]
@stevenmaguire I see, I checked the website and yes the link works there. Thank you.
