### ISSUE TITLE
IDN Domains support with punycode

### ISSUE THREAD

**Issue by pmaselkowski** [thephpleague/oauth2-client#672]
Hello!

I have issues with facebook and google oauth2 providers with domain containing i18n characters, in my case https://masełkowski.pl/

I've set up facebook and google URLs to puny encoded version: https://xn--masekowski-d0b.pl/

It seems that oauth client is sending not encoded domain name, resulting in errors:

For facebook it throws exception on my server:
> OAuthException: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

For google it fail on their server resulting in message:
> Invalid parameter value for redirect_uri: Uri must consist of printable ASCII characters: https://masełkowski.pl/sso/google/

My setup works fine for ASCII only domains. Also github supports IDN domains out-of-thebox and works fine.

For punycode [Puny code library](/true/php-punycode) can be used to not depend on PHP extension.

Also note that punycode is immutable (good word for it?), so when trying to encode already encoded hostname, like xn--masekowski-d0b.pl it will not break it.

**Comment by ramsey** [comment]
Those errors are coming from the providers themselves. When you encode your `redirect_uri` with puny code, does it work?

Please provide a snippet showing how you're instantiating your provider, obfuscating client IDs, secrets, and URL paths to sensitive info.

**Comment by pmaselkowski** [comment]
Manually encoding `redirect_uri` does indeed solve this issue. 

Extracted encoding part is something like the following:

```php
$uri = League\Url\Url::createFromUrl($returnUrl);

$encoder = new Punycode;
// The whole url with `http://` cannot be properly encoded, need to encode only host
$host = $uri->getHost();
$encoded = $encoder->encode($host);

// setHost does not work for some reason, so just replace.
// setHost should work, however I use proxied version and maybe something is wrong there.
$redirectUrl = str_replace($host, $encoded, $uri);
```

The whole instantiating is using factory pattern reading configs, doing some checks, so I've not included it here.

**Comment by ramsey** [comment]
I’m not sure it should be the responsibility of league/oauth2-client to perform the IDN encoding. If you can successfully do the encoding before passing the URLs to league/oauth2-client, then I think that’s the solution.
