### ISSUE TITLE
 FatalThrowableError Type error: Argument 1 passed to Osa\HotlineBundle\EventListener\RecordListener::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, string given, called in D:\sfProjects\developpement\sf3\osaSf3\var\cache\dev\ContainerYhkfjef\getDoctrine_Dbal_DefaultConnectionService.php on line 30

### ISSUE THREAD

**Issue by laajilyanas** [thephpleague/oauth2-client#675]
the code getDoctrine_Dbal_DefaultConnectionService.php:
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.default_connection' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Doctrine\\Logger\\DbalLogger.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Logging\\LoggerChain.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Configuration.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\EventSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\user-bundle\\Doctrine\\UserListener.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\EventManager.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Doctrine\\ContainerAwareEventManager.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\Connection.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Connection.php';
include_once $this->targetDirs[3].'\\src\\Osa\\HotlineBundle\\EventListener\\RecordListener.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\Tools\\AttachEntityListenersListener.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle\\ConnectionFactory.php';

$a = new \Doctrine\DBAL\Logging\LoggerChain();
$a->addLogger(new \Symfony\Bridge\Doctrine\Logger\DbalLogger(${($_ = isset($this->services['monolog.logger.doctrine']) ? $this->services['monolog.logger.doctrine'] : $this->load(__DIR__.'/getMonolog_Logger_DoctrineService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.stopwatch']) ? $this->services['debug.stopwatch'] : $this->services['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)) && false ?: '_'}));
$a->addLogger(${($_ = isset($this->services['doctrine.dbal.logger.profiling.default']) ? $this->services['doctrine.dbal.logger.profiling.default'] : $this->services['doctrine.dbal.logger.profiling.default'] = new \Doctrine\DBAL\Logging\DebugStack()) && false ?: '_'});

$b = new \Doctrine\DBAL\Configuration();
$b->setSQLLogger($a);

$c = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this);
$c->addEventSubscriber(new \FOS\UserBundle\Doctrine\UserListener(${($_ = isset($this->services['fos_user.util.password_updater']) ? $this->services['fos_user.util.password_updater'] : $this->load(__DIR__.'/getFosUser_Util_PasswordUpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.util.canonical_fields_updater']) ? $this->services['fos_user.util.canonical_fields_updater'] : $this->getFosUser_Util_CanonicalFieldsUpdaterService()) && false ?: '_'}));
$c->addEventListener(array(0 => 'preUpdate', 1 => 'postFlush'), ${($_ = isset($this->services['event.listener']) ? $this->services['event.listener'] : $this->services['event.listener'] = new \Osa\HotlineBundle\EventListener\RecordListener('service_container')) && false ?: '_'});
$c->addEventListener(array(0 => 'loadClassMetadata'), ${($_ = isset($this->services['doctrine.orm.default_listeners.attach_entity_listeners']) ? $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] : $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] = new \Doctrine\ORM\Tools\AttachEntityListenersListener()) && false ?: '_'});

return $this->services['doctrine.dbal.default_connection'] = ${($_ = isset($this->services['doctrine.dbal.connection_factory']) ? $this->services['doctrine.dbal.connection_factory'] : $this->services['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array())) && false ?: '_'}->createConnection(array('driver' => 'pdo_mysql', 'host' => '127.0.0.1', 'port' => NULL, 'dbname' => 'osasf2', 'user' => 'root', 'password' => NULL, 'charset' => 'UTF8', 'driverOptions' => array(), 'defaultTableOptions' => array()), $b, $c, array());

code RecordListener.php:
<?php

namespace Osa\HotlineBundle\EventListener;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PostFlushEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Osa\HotlineBundle\Entity\EventIncident;
use Osa\HotlineBundle\Entity\Incident;
use Symfony\Component\DependencyInjection\ContainerInterface;

class RecordListener
{

    private $container;
    private $fields = ['titre_incident', 'technicien' , 'societe' , 'application' , 'demandeur' , 'affaire' , 'severite' , 'priorite' ,  'description' , 'incidentSolution'];
//    private $fields = ['titre_incident'];

    private $audit = [];

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;

    }

    public function preUpdate(PreUpdateEventArgs   $eventArgs )
    {
        $em = $eventArgs->getEntityManager();
        $user = $this->container->get('security.token_storage')->getToken()->getUser();

        $incident = $eventArgs->getEntity();
        if ($incident instanceof Incident) {

            foreach($this->fields as $field){
                if ($eventArgs->hasChangedField($field)){

                    $event = new EventIncident();
                    $event->setChampsModifie($field);
                    $event->setIncident($incident);
                    $event->setUser($user);
                    $event->setAncienneVal($eventArgs->getOldValue($field));
                    $event->setNouvelleVal($eventArgs->getNewValue($field));
                    $event->setCreatedAt(new \DateTime());
                    $this->audit[] = $event;
                }
            }

        }
    }

    public function postFlush(PostFlushEventArgs $args)
    {
        if (! empty($this->audit)) {
            $em = $args->getEntityManager();

            foreach ($this->audit as $audit) {
                $em->persist($audit);
            }
            $this->audit = [];
            $em->flush();

        }
    }

}

**Comment by ramsey** [comment]
This error does not appear to be related to the league/oauth2-client package.
