### ISSUE TITLE
IPv6 compatibility

### ISSUE THREAD

**Issue by mabuonomo** [thephpleague/oauth2-client#677]
Hi, i have a timeout exception when I use a domain with record AAAA (ipv6).

Is the library compatibility with ipv6?

**Comment by ramsey** [comment]
The league/oauth2-client library itself doesn't try to directly negotiate communication across the network, so there shouldn't be an IPv6 compatibility issue.

By default, the library uses [Guzzle](https://github.com/guzzle/guzzle/) for HTTP requests. Under the hood, Guzzle can use cURL, PHP streams, sockets, etc. So, depending on your environment, whatever Guzzle is choosing to use may not support IPv6.

You also have the option of replacing Guzzle with the HTTP client of your choice, and if you're already doing that, you'll need to check with that HTTP client to see what it's using for network communication.

Hope this helps!
