### ISSUE TITLE
When will PHP 7.2 be supported?

### ISSUE THREAD

**Issue by yombo** [thephpleague/oauth2-client#681]
Searched for this before asking, found nothing. Any status on PHP 7.2 support?  Thanks.

**Comment by ramsey** [comment]
What is missing from the library to support PHP 7.2?

**Comment by ramsey** [comment]
The library supports PHP 7.2. I have confirmed this by adding a line to our Travis CI build matrix to run the tests on 7.2. I've updated the README accordingly.
