### ISSUE TITLE
Error management 

### ISSUE THREAD

**Issue by rkorebrits** [thephpleague/oauth2-client#684]
How does one go about handling errors? 

E.g. FB error looks something like this in URL: "error_code=1349126&error_message=App+Not+Setup", whereas LinkedIn uses different parameters. How do we properly manage errors?

**Comment by gassius** [comment]
With my basic understanding of working with this lib for a week, I would tell you that the idea is that you create/extend the provider to handle the errors in a way that is specific to the service you are trying to use and the requirements of your system. You could fetch the the error response from the server and throw custom Exceptions, for example.
