### ISSUE TITLE
cURL error 3: <url> malformed when using "getResourceOwner"

### ISSUE THREAD

**Issue by MickaelTH** [thephpleague/oauth2-client#686]
Hi,

I followed the doc (https://github.com/thephpleague/oauth2-client) and I am facing issue with this step:

![2018-02-11 002530](https://user-images.githubusercontent.com/26375917/36069900-8a5b1340-0f23-11e8-9d4c-55cc7879c219.png)

The error is :

![2018-02-11 002529](https://user-images.githubusercontent.com/26375917/36069901-930d5f0c-0f23-11e8-8048-1f758b8bcd6b.png)

Not sure if this is a Guzzle or oauth2-client issue, checking here first.

Thanks

**Comment by MickaelTH** [comment]
My bad, I've forgottent the 'urlResourceOwnerDetails' in the provider.

For OneDrive I've added this param in the GenericProvider:

'urlResourceOwnerDetails' => 'https://graph.microsoft.com/v1.0/me/drive',

And worked fine after that.

**Comment by JoshuaFlood** [comment]
@MickaelTH are you able to give more info on the resource owner details please?

I have been following the same guides and can't figure out what data is expected. I can't find any example endpoint in the phpleague documentation so I don't know what I'm asking for when I call that endpoint, or what data I should expect back. TIA!
