### ISSUE TITLE
PHP 7.1 Exception: Deprecated Function mcrypt_module_open()

### ISSUE THREAD

**Issue by afonseca08** [thephpleague/oauth2-client#689]
I am getting the following exception thrown when calling getAuthorizationUrl():

Deprecated: Function mcrypt_module_open() is deprecated in /app/public/custom/hubspot/vendor/ircmaxell/random-lib/lib/RandomLib/AbstractMcryptMixer.php on line 75

**Comment by PatchworkBoy** [comment]
Upgrade to a later version of thephpleague/oauth2-client (They switched away from ircmaxell in ^2.0.0 and began using paragonie instead, which has been updated for PHP7.x)
