### ISSUE TITLE
Dead link on thirdparty.md

### ISSUE THREAD

**Issue by westerjn** [thephpleague/oauth2-client#691]
Low priority, but the link to the First Providers is dead for me (aka 404)

https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md

**Comment by westerjn** [comment]
Found the first providers list at http://oauth2-client.thephpleague.com/providers/league/

Will try to edit page via PR.

**Comment by ramsey** [comment]
Please see #670, #660, #638, #679, #671, and #662. This works as expected. No PR necessary. :smile:
