### ISSUE TITLE
Trait 'League\OAuth2\Client\Tool\ArrayAccessorTrait' not found in ../wp-content/oauth2-client-master/src/Provider/AbstractProvider.php

### ISSUE THREAD

**Issue by Himani3010** [thephpleague/oauth2-client#692]
I am trying to implement Mollie-Oauth2-API into my WordPress E-commerce environment. On inheriting [Oauth2-client](https://github.com/thephpleague/oauth2-client/) and [Oauth2-mollie](https://github.com/mollie/oauth2-mollie-php) I am receiving the error below:

> Trait 'League\OAuth2\Client\Tool\ArrayAccessorTrait' not found in ../wp-content/oauth2-client-master/src/Provider/AbstractProvider.php

Please, can you help me with the same!

Thanks in advance!

**Comment by stevenmaguire** [comment]
Are you using composer to install these dependancies? Are you including the autoloader reference in your project correctly?

**Comment by stevenmaguire** [comment]
Take a look at this article, it seems close to what I believe you’re after. https://www.alainschlesser.com/adding-central-autoloader-wordpress/

**Comment by stevenmaguire** [comment]
Maybe @kkoppenhaver can help out with this?

**Comment by kkoppenhaver** [comment]
@Himani3010 @Ryuuzan Are you trying to include this in a theme or plugin? How are you trying to use this?

Based on that error message, it looks like your code is looking for this plugin just in wp-content, which it probably not where it should be stored.

**Comment by ramsey** [comment]
Closing due to lack of inactivity. If this is still an issue, please re-open or create a new issue. Thanks!
