### ISSUE TITLE
make option "verify" also without parameter proxy available

### ISSUE THREAD

**Issue by N3XT0R** [thephpleague/oauth2-client#704]
Hello guys,
it would be very nice when the verify Option on the Constructor from GenericProvider would also accept verify without giving it a proxy address.

On development with ssl and self signed certificates there are problems to debug the oAuth-Client, because there is everytime the Exception "curl Error 51".

**Comment by slykar** [comment]
It's pain in the ass, because I can't test locally without self-signing a certificate. It should be possible to disable SSL verification without being forced to use proxy.

**Comment by ramsey** [comment]
Closing this, since it's related to the #863 feature request. Thanks!

**Comment by Peddaahh** [comment]
> Closing this, since it's related to the #863 feature request. Thanks! @ramsey 

As I am confused by following the Issue history/Implementation.. is this now possible?

**Comment by N3XT0R** [comment]
nope it isn't: https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L175
