### ISSUE TITLE
Try to get a new accesstoken by refreshtoken

### ISSUE THREAD

**Issue by Silassiai** [thephpleague/oauth2-client#705]
$newAccessToken = $provider->getAccessToken('refresh_token', [
	'refresh_token' => $refresh_token,
]);

Results in: Error!: Could not connect to TeamLeader: Required option not passed: "access_token"

what am i doing wrong?

**Comment by nealoke** [comment]
@Silassiai did you find what went wrong? I have the same issue 😢

**Comment by Silassiai** [comment]
Hi nealoke,

Don't exactly remember what was wrong. 
Think it had something to do with passing the access token not like it expected.

first in your authorization method:

// Try to get an access token using the authorization code grant.
                $accessToken = $this->provider->getAccessToken('authorization_code', [
                    'code' => $request->code
                ]);

 $params = [
                    'token' => $accessToken->getToken(),
                    'refreshtoken' => $accessToken->getRefreshToken(),
                    'expires' => $accessToken->getExpires(),
                ];


later in the refresh method

/**
	 * refreshToken
	 * when the accesstoken is expired, we call this method to refresh the token
	 */
	public function refreshToken() {
		$refresh_token = $this->getStoredAccessToken( 'refreshtoken' );
		// refresh the expired accesstoken
		$newAccessToken = $this->provider->getAccessToken( 'refresh_token', [
			'refresh_token' => $refresh_token,
		] );

		$this->setStoredAccessToken( 'accesstoken', $newAccessToken->getToken() );
		$this->setStoredAccessToken( 'refreshtoken', $newAccessToken->getRefreshToken() );
		$this->setStoredAccessToken( 'expires', $newAccessToken->getExpires() );
	}

**Comment by nealoke** [comment]
@Silassiai Thanks but apparently it has nothing to do with this library for me. I just needed to add the `refreshToken grant` to my `AuthorizationServer` 😄

**Comment by Silassiai** [comment]
@nealoke ahh sorry, can you show me how your refreshToken looks?
