### ISSUE TITLE
How To Proceed after Authentication

### ISSUE THREAD

**Issue by Darthmaul** [thephpleague/oauth2-client#708]
Hey there

I am working on a new Laravel project and I have set this up to work with the nest 3rd-party integration of this library.

That being said, I can get Nest to authenticate. The problem is, I don't know how to do anything afterwards.

Here's my current code:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Stevenmaguire\OAuth2\Client\Provider\Nest as Nest;
class ContentsController extends Controller
{
    //
    
    
    public function home()
    {
        $data = [];
        $data['version'] = '0.1.2';

        return view('api', $data);
    }

    public function apiNestTest() {
        $provider = new Nest([
            'clientId'          => 'myid',
            'clientSecret'      => 'mysecret',
            'redirectUri'       => 'https://homestead.test/api'
        ]);
        // If we don't have an authorization code then get one
        if (!isset($_GET['code'])) {

            // Fetch the authorization URL from the provider; this returns the
            // urlAuthorize option and generates and applies any necessary parameters
            // (e.g. state).
            $authorizationUrl = $provider->getAuthorizationUrl();

            // Get the state generated for you and store it to the session.
            $_SESSION['oauth2state'] = $provider->getState();

            // Redirect the user to the authorization URL.
            header('Location: ' . $authorizationUrl);
            exit;

        // Check given state against previously stored one to mitigate CSRF attack
        } elseif (empty($_GET['state']) || (isset($_SESSION['oauth2state']) && $_GET['state'] !== $_SESSION['oauth2state'])) {

            if (isset($_SESSION['oauth2state'])) {
                unset($_SESSION['oauth2state']);
            }
            
            exit('Invalid state');

        } else {

            try {

                // Try to get an access token using the authorization code grant.
                $accessToken = $provider->getAccessToken('authorization_code', [
                    'code' => $_GET['code']
                ]);

                

                // The provider provides a way to get an authenticated API request for
                // the service, using the access token; it returns an object conforming
                // to Psr\Http\Message\RequestInterface.
                
                $request = $provider->getAuthenticatedRequest(
                    'GET',
                    'https://developer-api.nest.com/',
                    $accessToken
                );
                
                
            } catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {

                // Failed to get the access token or user details.
                exit($e->getMessage());

            }


        }
        return view('api');
    }
}

```

So pretty much I can get this thing to authenticate you as soon as you go to the URL, and dump you back out on this page.

My question is really 2-pronged.

First of all, I have a need to be able to make API calls after users authenticate. How do I set this up so that once a user authenticates the application remembers this and stores that key to make calls on later?

Second, how do I display data from an API request? I've been digging through Guzzle's documentation, as that is what various issues on this repo point to for making API requests. However, I have yet to find an answer to displaying data on the frontend from an API call I make on the backend. I don't care about the '200 ok' codes or any of those responses, I want the actual data to display.

I have to say, once I got it going this is a great library. However, there isn't much out there for documentation on this thing about how to proceed. 

Disclaimer I am fairly new to Laravel so might be completely missing some obvious stuff here.

Thanks! Hope someone can help me!

**Comment by zenichanin** [comment]
Did you ever figure out how to do this? I'm also trying to access an API URL AFTER auth but don't see any way in documentation to do so.

**Comment by Darthmaul** [comment]
Howdy

I just went back and looked at the code, and basically I created a helper to save the Authentication Code to the database for the user making the request. To be honest, I'm not sure if this is the best way to do it. I think if I was going to do it again, I would take a few extra steps in the helper to salt the token for higher security. 

We had some logic to check if the user had an auth code, and then save it if they didn't.  In the initial redirect loop we needed to immediately make an API call, so we worked the loop to grab  that auth code then immediately hit the API.

From there, you just query that auth code in the rest of your application whenever you need to make an API request.

Again, I'm not sure how standard this approach is. The app  we were working on  was a  proof of  concept, and  this solved the issue.
