### ISSUE TITLE
Can this client be used for OIDC auth?

### ISSUE THREAD

**Issue by loganto** [thephpleague/oauth2-client#712]
Hi. Can this client be used for OIDC auth?

I've implemented bshaeffer's oauth2-server-php lib (https://github.com/bshaffer/oauth2-server-php).  
And now a bit confused re: if  can use nay Oauth2 client or does the client also have to support OIDC?

**Comment by pnicolcev-tulipretail** [comment]
You can use this client as a base for OIDC but you'll need to change it to support the provider. 

for example to get an authorization URL, you'll need to add a function for that. 

eg: https://github.com/tulipretail/oauth2-hydra/blob/master/src/Provider/OAuth2.php

**Comment by ramsey** [comment]
Closing this issue, since it's been answered, but also mentioning #778 here, since that's a related feature request.
