### ISSUE TITLE
Support for client_assertion with certificate

### ISSUE THREAD

**Issue by steinmr** [thephpleague/oauth2-client#713]
Hi,

I recently needed to authenticate with Azure AD from PHP, using a client certificate.
It is using the proposed standard described here: https://tools.ietf.org/html/rfc7521
which basically is signing a JWT using the certificate and sending it to the OAuth endpoint.
My certificate is contained in a pfx file.

I could not find any code that supports this scenario, neither in this library or elsewhere.
So I went ahead and wrote the code myself, and it seems to be working.

Is this kind of code something that could be interesting to add to this library? I can do a pull request, but I just wanted to check if this is something you would want.

**Comment by danpoltawski** [comment]
@steinmr I am also looking for this feature - is your code shareable or did you find another option?

**Comment by danpoltawski** [comment]
Just found https://github.com/TheNetworg/oauth2-azure/issues/57 for other followers of this issue

**Comment by steinmr** [comment]
Yeah, it is shareable, its just the conversion into framework code that I have not had the time to do yet, been swamped at work. I'm assuming [TheNetworg/oauth2-azure#57](https://github.com/TheNetworg/oauth2-azure/issues/57) is the correct place to do this. I'm happy to share the code with you, and assist you as best I can if you try to implement this.

**Comment by chadsowald** [comment]
@steinmr Any chance you can post the code you have working regardless of if it's built for this specific library (thephpleague)?  I have the same question and this post of yours is still the closest I've found to a solution.  Otherwise, it looks like I would need to reverse engineering how, say, .NET Core does it ([like this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/Internal/Requests/ClientCredentialHelper.cs)), but it's still unclear to me how to craft the JWT that needs to get signed.

**Comment by steinmr** [comment]
Sure, the code is like this. I'm still planning on doing a PR, but I have very little free time, so it is up for grabs. Please re-use this code if needed:

```php
$setup = [
  'certPath' => 'somefile.pfx', // Full path to certificate .pfx file
  'certPwd' => 'some-password', // Password of .pfx file, must be protected.
  'client_id' => 'some-guid', 
  'tenant' => 'https://login.microsoftonline.com/mytenant.onmicrosoft.com', 
  'service_resource_id' => 'some-other-guid'
];

openssl_pkcs12_read(file_get_contents($setup["certPath"]), $certs, $setup["certPwd"]);
$cert = openssl_x509_read($certs["cert"]);
$x5t = base64urlencode(openssl_x509_fingerprint($cert, 'sha1', true));
$pkey = openssl_pkey_get_private ($certs["pkey"]);
$exp = time() + (60 * 10); // Token is only needed to get the access_token, can expire it right away, but set to 10 minutes to avoid clock drift issues.
$nbf = time() - (60 * 10); // 10 minutes in the past
$client_id = $setup['client_id'];
$subject = $client_id;
$jti = guidv4();
$token_endpoint = $setup['tenant'].'/oauth2/token';

// Optional: It is recommended to use a standard PHP-library to create JWT
$header = '{"alg":"RS256","typ":"JWT","x5t":"' . $x5t .'"}';
$payload = '{
  "aud": "'.$token_endpoint.'",
  "exp": '.$exp.',
  "iss": "'.$client_id.'",
  "jti": "'.$jti.'",
  "nbf": '.$nbf.',  
  "sub": "'.$subject.'"
}';
$unsigned_token = base64_encode($header).".".base64_encode($payload);
openssl_sign($unsigned_token, $signature, $pkey, 'SHA256');
$token = $unsigned_token.".".base64urlencode($signature);

echo "Using certificate: ". openssl_x509_parse( $cert )["name"]."\n"; // Optional: Print/Check expiry of client certificate
echo "AAD token endpoint: " . $token_endpoint."\n";
$post = [
    'resource' => $setup['service_resource_id'],
    'client_id' => $client_id,
    'client_assertion' => $token,
	'client_assertion_type' => 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
	'grant_type' => 'client_credentials',
];
if(substr( $token_endpoint, 0, 8 ) !== "https://") { throw new Exception("https required in token endpoint url"); }
$ch = curl_init($token_endpoint);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_VERBOSE, false);

// Note: Do not do this if you already have an access_token that has not yet expired, you should re-use it.
$response = curl_exec($ch);
$httpcode = curl_getinfo($ch,CURLINFO_HTTP_CODE);
curl_close($ch);
$response_json = json_decode($response);
$expires_on = $response_json->expires_on; // Unix time
$access_token = $response_json->access_token;
echo "Response code: ".$httpcode.". Access token expires at ".date('Y-m-d H:i:s', $expires_on)."\n";

// Todo: Send the request to the service you want, passing the header: "Authorization: Bearer $access_token"

function base64urlencode($value) {
    return rtrim(strtr(base64_encode($value), '+/', '-_'), '=');
}

function guidv4()
{
    if (function_exists('com_create_guid') === true)
        return trim(com_create_guid(), '{}');

    $data = openssl_random_pseudo_bytes(16);
    $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
    $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}
```

**Comment by ramsey** [comment]
[TheNetworg/oauth2-azure](https://github.com/TheNetworg/oauth2-azure) is the correct place to contribute this, yes.

**Comment by bertinnv** [comment]
hi, i am running your code but i have the following error:
AADSTS901002: The 'resource' request parameter is not supported
I will appreciate your support

**Comment by bertinnv** [comment]
Checking the documentation I found that there is a change in the parameters:

$setup = [
  'certPath' => 'certificado.pfx', // Full path to certificate .pfx file
  'certPwd' => 'korumi2020', // Password of .pfx file, must be protected.
  'client_id' => 'clientid', 
  'tenant' => 'https://login.microsoftonline.com/mytenant', 
];

$token_endpoint = $setup['tenant'].'/oauth2/v2.0/token';

$post = [    
    'client_id' => $client_id,
    'client_assertion' => $token,
	'client_assertion_type' => 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
	'grant_type' => 'client_credentials',
    'scope' => 'https://graph.microsoft.com/.default'
];

**Comment by java305** [comment]
Good morning, I wanted to ask for help. Good morning, I wanted to ask for help. I used the code to get the AZURE token, but then I can't download a file with CURL using "Authorization: Bearer $access_token" because I always get error 401 unauthorized. Does anyone have any idea how it can be done?
thanks
