### ISSUE TITLE
oauth2-client guzzle http 404 not found

### ISSUE THREAD

**Issue by inovatedTeam** [thephpleague/oauth2-client#715]
Error Page
Error occurred : Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in /home1/happydemy/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 529 on line 708 in /home1/happydemy/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php

When I sent get token request in getParsedResponse(), I am getting BadResponseException(404 not found).
![image](https://user-images.githubusercontent.com/14047891/40778225-0d0aab86-6503-11e8-9632-f39a8c9c6b45.png)

**Comment by inovatedTeam** [comment]
It was working perfectly. But I moved oauth server hosting.
And then I am getting that error.
Perhaps it is depend server configuration.
Am I right?

**Comment by ramsey** [comment]
It appears this is because some providers will respond with a string or other value, instead of a JSON value that we can parse as an array.
