### ISSUE TITLE
league/oauth2-client 2.3.0 requires paragonie/random_compat ^1|^2

### ISSUE THREAD

**Issue by Jimbolino** [thephpleague/oauth2-client#730]
I see this is fixed in master already.

When will 2.3.1 be released?

**Comment by MKiselev** [comment]
+1

**Comment by MKiselev** [comment]
@ramsey +1

**Comment by nkkromhof** [comment]
@ramsey +1

**Comment by nkkromhof** [comment]
If anyone else comes up against this problem, I worked around it by using `composer why paragonie/random_compat` which indicated that in my case (Laravel): `ramsey/uuid  3.8.0  requires  paragonie/random_compat (^1.0|^2.0|9.99.99)`

So I solved the problem with `composer require paragonie/random_compat "^1.0|^2.0"` which satisfies `ramsey/uuid` requirements and results in a downgrade of `paragonie/random_compat` to 2.0.17.

After that I could successfully install `league/oauth2-client`.

**Comment by ramsey** [comment]
It’s funny that my other library is part of the problem for you. 😂

I apologize for the delay. I’ll try to get a release out for this today.

**Comment by paultofunmi** [comment]
Ran into this issue over the weekend and this solution worked like charm. Thanks @nkkromhof

**Comment by sbol-coolblue** [comment]
Ran into this issue as well. @ramsey any chance of releasing 2.3.1 anytime soon?

**Comment by ramsey** [comment]
Thanks for the nudge on Twitter, @sbol-coolblue. I created a reminder for me to do the release this weekend. Apologies, everyone!

**Comment by ramsey** [comment]
I've just released version 2.3.1, which includes the update that allows paragonie/random_compat 9.99.99. Please try out the release and let me know if it resolves this. Thanks!

**Comment by mxdpeep** [comment]
> I've just released version 2.3.1, which includes the update that allows paragonie/random_compat 9.99.99. Please try out the release and let me know if it resolves this. Thanks!

you may probably close this issue 🥇
