### ISSUE TITLE
Retrieve guild list

### ISSUE THREAD

**Issue by StrangerGithuber** [thephpleague/oauth2-client#732]
Hello
I am a newbie here so therefore I am asking here.
How can I retrieve those guild name, ID and member list where the logged in person is owner?

My plan is that when someone login then the website will show those servers where the logged in person is owner and it will retrieve the guild name and id and probably the members too to check if the specific bot is there or not.

OR this script doesn't support Discord?

**Comment by ramsey** [comment]
Hey, @StrangerGithuber. Thanks for your question. I recommend asking over on the OAuth 2 client library for Discord: https://github.com/wohali/oauth2-discord-new

They'll probably be able to help answer your question better. Cheers!
