### ISSUE TITLE
Refresh token, refresh_token_expires_in, not being captured 

### ISSUE THREAD

**Issue by AntonioCS** [thephpleague/oauth2-client#733]
Hey,

In the linkedin API certain clients will have the [refresh token activated](https://developer.linkedin.com/docs/Refresh-Tokens-with-OAuth-2).
So this means the API will response with the  extra fields `refresh_token` and `refresh_token_expires_in`.
[AccessToken](https://github.com/thephpleague/oauth2-client/blob/master/src/Token/AccessToken.php#L60) does not capture the second fields (`refresh_token_expires_in`).

Can someone add this in?

**Comment by ramsey** [comment]
Closing since this is better handled in the oauth2-linked package repository, and I see you've already opened an issue there. Thanks!
