### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by paultofunmi** [thephpleague/oauth2-client#734]
composer require league/oauth2-client throws the error

`Problem 1
    - Installation request for league/oauth2-client ^2.3 -> satisfiable by league/oauth2-client[2.3.0].
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - league/oauth2-client 2.3.0 requires paragonie/random_compat ^1|^2 -> satisfiable by paragonie/random_compat[1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.0.0, v1.0.1, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.x-dev, v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[1.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.0.9, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[1.1.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.2.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.2.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.2.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.2.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.3.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.3.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.x-dev, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].`

**Comment by danieldevine** [comment]
T oget around this issue, [which you can read about here:](https://github.com/paragonie/random_compat#version-99999)

```
composer require paragonie/random_compat:2.*
composer require league/oauth2-client
```

**Comment by paultofunmi** [comment]
Thanks. resolved now.
