### ISSUE TITLE
POST Request

### ISSUE THREAD

**Issue by paultofunmi** [thephpleague/oauth2-client#736]
Hi, I am trying to make a POST request like so: 

          `$data = [
                    'email' => $email,
                    'campaign' => [
                        'campaignId' => $campId
                    ]
                ];`
            `$request = $this->provider->getAuthenticatedRequest(
                                'POST',
                                'https://api.getresponse.com/v3/contacts',
                                $this->getMyAccessToken(),
                                $data
                    );
            $response = $this->provider->getParsedResponse($request);`

I also tried this 
          `$data = [
                    'email' => $email,
                    'campaign' => [
                        'campaignId' => $campId
                    ]
            ];`

            `$options['body'] = json_encode($data);
            $options['headers']['Content-Type'] = 'application/json';
            $options['headers']['access_token'] = $this->getMyAccessToken();
            $request = $this->provider->getAuthenticatedRequest(
                                'POST',
                                'https://api.getresponse.com/v3/contacts',
                                $options
                    );
            $response = $this->provider->getParsedResponse($request); `
     
However the getParsedResponse function in both approaches returns the following: 

`League \ OAuth2 \ Client \ Provider \ Exception \ IdentityProviderException (400)
Unsupported `ContentType` header.`

**Comment by ramsey** [comment]
Closing due to lack of response. If you're still having this issue, feel free to re-open.

**Comment by karvox** [comment]
> Hi, I am trying to make a POST request like so:
> 
> ```
>       `$data = [
>                 'email' => $email,
>                 'campaign' => [
>                     'campaignId' => $campId
>                 ]
>             ];`
>         `$request = $this->provider->getAuthenticatedRequest(
>                             'POST',
>                             'https://api.getresponse.com/v3/contacts',
>                             $this->getMyAccessToken(),
>                             $data
>                 );
>         $response = $this->provider->getParsedResponse($request);`
> ```
> 
> I also tried this
> `$data = [ 'email' => $email, 'campaign' => [ 'campaignId' => $campId ] ];`
> 
> ```
>         `$options['body'] = json_encode($data);
>         $options['headers']['Content-Type'] = 'application/json';
>         $options['headers']['access_token'] = $this->getMyAccessToken();
>         $request = $this->provider->getAuthenticatedRequest(
>                             'POST',
>                             'https://api.getresponse.com/v3/contacts',
>                             $options
>                 );
>         $response = $this->provider->getParsedResponse($request); `
> ```
> 
> However the getParsedResponse function in both approaches returns the following:
> 
> `League \ OAuth2 \ Client \ Provider \ Exception \ IdentityProviderException (400) Unsupported `ContentType` header.`

Hello @paultofunmi, do you solve this issue?
