### ISSUE TITLE
Problem with secret key that ends in "="

### ISSUE THREAD

**Issue by Juanacv** [thephpleague/oauth2-client#737]
Hello everybody.

I am trying to get the access token from a login into an microsoft azure app, i've got the cliend_id and the client_secret, but the azure keys are strings that end with a "=" character, and it seems that the library doesn't like them, because azure returns an "invalid client" error, that is related with the client_secret key. 

I have tried to get it using a postman-like app, and it works with client_id and client_secret i provide to my laravel application.

Anyone else has experience the same problem?

Best regards.

![image](https://user-images.githubusercontent.com/4825200/46767659-eff22100-cce5-11e8-9849-49e94894cbab.png)

**Comment by ramsey** [comment]
Thanks for the report, @Juanacv.

Is there any feedback you're getting from Azure that indicates to you that the oauth2-client library is doing anything with the `=` character on the end? The library itself isn't doing anything to change the `clientId` value.

**Comment by Juanacv** [comment]
Finally I make it work using the key from the configuration file.  I don't know what I was making wrong, maybe using mixed keys or anything else.

Sorry and thanks for your response.
