### ISSUE TITLE
fatal error on unavailable webservice

### ISSUE THREAD

**Issue by N3XT0R** [thephpleague/oauth2-client#739]
Hello guys,
there seems to be a error in the method AbstractProvider::parseResponse().
Actually only on HTTP-StatusCode 500 will be an exception thrown, but there can occur some other cases like other 500er errors or 400er. In all other cases the body will be returned as string, but that method should give an array back (as defined in the method phpDoc-block), so it can happen that inside of AbstractProvider::getAccessToken() the method 'parseResponse' returns a string, and on line 472 will be given this string to prepareAccessTokenResponse(). But prepareAccessTokenResponse need an array and so there will occur a php fatal error with following output:

`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in xxxx/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 472 and defined in /xxxx/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:632
Stack trace:
`

**Comment by ramsey** [comment]
Thanks for the report, @N3XT0R. Can you provide and example of a provider where you've encountered this happening? Can we reproduce it in the wild?

**Comment by ramsey** [comment]
The same kind of error is being reported here: https://github.com/thephpleague/oauth2-client/issues/715

**Comment by ramsey** [comment]
It appears this is because some providers will respond with a string or other value, instead of a JSON value that we can parse as an array.
