### ISSUE TITLE
it's unable to used again after set $wgGroupPermissions['*']['read'] = false

### ISSUE THREAD

**Issue by xy74695321** [thephpleague/oauth2-client#740]
after set  $wgGroupPermissions['*']['read'] = false in LocalSettings.php file,  tap login button unable to directed right url.

**Comment by xy74695321** [comment]
software : Mediawiki.

**Comment by ramsey** [comment]
Is this issue related to league/oauth2-client?

**Comment by mxdpeep** [comment]
this error should need more debugging information as it looks like not related
