### ISSUE TITLE
New release breaks providers with AccessToken to AccessTokenInterface

### ISSUE THREAD

**Issue by scuben** [thephpleague/oauth2-client#753]
The abstract method `abstract public function getResourceOwnerDetailsUrl(AccessTokenInterface $token);` from `src/Provider/AbstractProvider.php` is now a problem as a provider has still `public function getResourceOwnerDetailsUrl(AccessToken $token)`. This results in a "Declaration of must be compatible with" kind of error.

**Comment by fzieris** [comment]
Same error as in #752

**Comment by scuben** [comment]
closed in favour of https://github.com/thephpleague/oauth2-client/issues/752 (2 minutes earlier :))

**Comment by ramsey** [comment]
Please check release 2.4.1 and confirm that it fixes this issue. Thanks!

**Comment by jesseleite** [comment]
Thank you for this fix!  I fought with this for a bit, but see that you guys just pushed fix 👌
