### ISSUE TITLE
Google Plus

### ISSUE THREAD

**Issue by steveknoblock** [thephpleague/oauth2-client#756]
I'm hoping to use oauth2-client for our website. It takes me through the Google Sign in process successfully, but at the end it asks me to enable the Google+ API for it. I'm concerned that when Google shuts down, the library will stop working. Is this the case? Should I enable G+ and go ahead deploying the client library?

**Comment by aripringle** [comment]
I was curious about this as well, and it looks like the Google+ API usage was dropped in the 3.x release of the oauth2-google lib: https://github.com/thephpleague/oauth2-google/commit/8ce837dfc8d7411fae1a2d977451b828ce8e1281

**Comment by mxdpeep** [comment]
this error is not related to Google+ API
I am not using Google+ on my server and still got stuck in the Sync menu

yes, the 3.x release of `oauth2-client` dropped G+ API completely

**Comment by mxdpeep** [comment]
> I'm hoping to use oauth2-client for our website. It takes me through the Google Sign in process successfully, but at the end it asks me to enable the Google+ API for it. I'm concerned that when Google shuts down, the library will stop working. Is this the case? Should I enable G+ and go ahead deploying the client library?

update to 3.0.1 and disable Google+ in the Developer Console
