### ISSUE TITLE
broken OAuth flow for secondary account on Chrome Android

### ISSUE THREAD

**Issue by mxdpeep** [thephpleague/oauth2-client#759]
When I try to Sign-in via Use another account option on the OAuth screen (so not using the default account), after I select the secondary account a Sync menu of the Android pops up, the OAuth flow is broken

**Comment by mxdpeep** [comment]
"prompt" => "select_account consent" does not solve the problem

**Comment by ramsey** [comment]
This question does not appear related to the league/oauth2-client library for PHP. If I'm wrong, feel free to re-open this and provide more details about your issue, preferably with some sample code of what you're trying to do. Thanks!
