### ISSUE TITLE
Q: Is the Authorization Server's public key being used to validate the access token?

### ISSUE THREAD

**Issue by ac-anthonywoolstrum** [thephpleague/oauth2-client#762]
from: http://oauth2.thephpleague.com/installation/

> The public key should be distributed to any services (for example resource servers) that validate access tokens.

I have built a working custom provider against my own server's implementation of the OAuth2 server library.  It is working machine to machine, and I see it's generating JWT tokens.  I may be completely missing it, but where in the OAuth client library do you pass the authorization server's public key to validate the access token?  Is this not needed because its a JWT self-encoded token?  Or is that functionality I should be building into my custom provider on my own?  Just want to make sure I'm not missing a security step.  Thanks!

**Comment by ramsey** [comment]
The league/oauth2-server package uses a public/private key pair to generate [JWT (JSON Web Tokens)](https://tools.ietf.org/html/rfc7519). Some OAuth 2 servers use JWTs as part of their authorization. If this is the case, please extend `AbstractProvider` from league/oauth2-client to implement the JWT functionality you need.
