### ISSUE TITLE
Broken link "There are a large number of community packages that interface with other systems."

### ISSUE THREAD

**Issue by fmertins** [thephpleague/oauth2-client#770]
Hi there, on https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/league.md there is a broken link (https://github.com/thephpleague/oauth2-client/blob/master/providers/thirdparty)

**Comment by sandacn** [comment]
see pull request https://github.com/thephpleague/oauth2-client/pull/772
but there is another doc site: https://oauth2-client.thephpleague.com/providers/league/

In that page, the link is not broken.

**Comment by shadowhand** [comment]
The `docs/` directory is what powers the website https://oauth2-client.thephpleague.com/ Modifying links to work in the Github file browser will break the website.

**Comment by fmertins** [comment]
Hi folks, I didn't know that other site, I'll have a look, awesome, thanks!
