### ISSUE TITLE
Cannot install on PHP 5.6

### ISSUE THREAD

**Issue by r-bt** [thephpleague/oauth2-client#780]
Hi,

I just tried to install the library onto my server however composer responded with this error:
```bash
Problem 1
    - Installation request for paragonie/random_compat v9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.13) does not satisfy that requirement.
  Problem 2
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.13) does not satisfy that requirement.
    - league/oauth2-client 2.4.1 requires paragonie/random_compat ^1|^2|^9.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - Installation request for league/oauth2-client 2.4.1 -> satisfiable by league/oauth2-client[2.4.1].
```

The dependencies of the library itself require PHP 7 or greater despite the library only needing PHP 5.6.

**Comment by chrisforrence** [comment]
Out of curiousity, what else is in your composer.json file, and what had been the full output?

Also, this issue looks pretty darn similar to what you had seen, perhaps it's of help? https://github.com/laravel/passport/issues/774#issuecomment-407557491

**Comment by tttttony** [comment]
@chrisforrence `League\OAuth2\Client\Provider\AbstractProvider` also uses `random_bytes` which is PHP 7+ so support for 5.6 should be dropped from the package. After all, it's 2020 ;)

I ran into this issue today.

**Comment by SidneyAllen** [comment]
@chrisforrence and @tttttony @richardbeattie 

The README for this project still lists 5.6 under requirements
https://github.com/thephpleague/oauth2-client#requirements

Can I assume that the use of random_bytes makes this PHP 7+ required?

**Comment by ramsey** [comment]
paragonie/random_compat provides a polyfill for `random_bytes()` in versions of PHP earlier than 7, and we are using that in this library, so it *should* install on PHP 5.6. The version constraint listed should allow its installation on PHP 5.6, so I'm not sure why it's giving this error.

**Comment by u4yk** [comment]
I was able to get it working in 5.6 after installing random_compat manually.  You have to specify the version.

> For software that explicitly needs PHP 5 support:
> composer require paragonie/random_compat:\<9.99

Don't know why it won't work with the PHP7-compatible version.

**Comment by SidneyAllen** [comment]
It's working for me now.  Perhaps the problem was my MAMP server was set to use 5.6, but on the command line I was still using version 7.x.

When I updated my laptop settings to use 5.6 from the terminal, cleared out my vendor folder, deleted my composer.lock file and then ran a clean composer install - everything worked fine after that.

🤷‍♂️
