### ISSUE TITLE
Normalize response

### ISSUE THREAD

**Issue by Yamakasi** [thephpleague/oauth2-client#782]
Hi Guys,

I like the decent simplicity of this module but I wonder if it's possible to get a normalized dataset between the providers like

first_name
last_name
etc..

Instead of all different outputs per provider.

Thanks for the effort so far!

**Comment by Yamakasi** [comment]
Do people not care about simplified and normalized output like HybridAuth does ?

**Comment by ramsey** [comment]
[OAuth 2](https://tools.ietf.org/html/rfc6749) doesn't specify any user data returned from the providers at all. It doesn't define an API or user resources. It only defines authorization, and it's only a framework and not a hard specification, at that.

league/oauth2-client focuses only on RFC 6749 and not the data various providers return. We aren't able to do any normalization of data. Sorry.
