### ISSUE TITLE
Is the LinkedIn Provider for OAuth 2.0 Client still maintained?

### ISSUE THREAD

**Issue by picks44** [thephpleague/oauth2-client#784]
Hi there,
It seems like nobody is answering [the recent issues](https://github.com/thephpleague/oauth2-linkedin/issues) with the [LinkedIn Provider for OAuth 2.0 Client](https://github.com/thephpleague/oauth2-linkedin) provided by thephpleague...
Is this repo still maintained? Thanks!

- [Please update library to V2 API version](https://github.com/thephpleague/oauth2-linkedin/issues/28)
- [Unable to retrieve access token](https://github.com/thephpleague/oauth2-linkedin/issues/27)

**Comment by stevenmaguire** [comment]
Yes the package is maintained. Package version [5.0.0](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.0) is now available with exclusive support for LinkedInAPI v2.
