### ISSUE TITLE
Error line 85 in GrantFactory

### ISSUE THREAD

**Issue by keler18** [thephpleague/oauth2-client#787]
Hello,

In a server with PHP version 7.x  (also tried in 7.1) after install mdirector's oauth2 client throught composer, I'm getting a error in the execution of the command: "php mypage.php", this error is the next:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/cesde.com/httpdocs/vendor/league/oauth2-client/src/Grant/GrantFactory.php on line 85

After googled, and spend hours trying any possible solution, I have not obtained a successful solution.

Anyone can help me?

Thanks.

**Comment by ramsey** [comment]
Here's line 85: https://github.com/thephpleague/oauth2-client/blob/badb01e62383430706433191b82506b6df24ad98/src/Grant/GrantFactory.php#L85

I'm scratching my head at what the syntax error could be. The only thing I can guess at is the `::class` special constant, but that was introduced in PHP 5.5, so unless you're using PHP 5.4, that shouldn't be a problem.

I'll close this issue for now, but if it is still an issue, please re-open and let me know, and we can try to debug it with more details.
