### ISSUE TITLE
Client error: GET https://graph.microsoft.com/v1.0/me resulted in a `401 Unauthorized` response - InvalidAuthenticationToken - Access token validation failure

### ISSUE THREAD

**Issue by Sam-digitalife** [thephpleague/oauth2-client#796]
Hi all, 
Since few days I try to use the token received with Oauth2-Client with MSGraph but till now I always get the same issue. 401 unauthorized.
I'm able to get the token and query azure AD to get user details.
but when I give the token to MSGraph I always get 401 Unauthorized :-/
Any idea ?

**Comment by thebatmanreturns** [comment]
I'm facing the same error while calling the calendar API. Even through I've refreshed the token.

**Comment by ramsey** [comment]
Please post these questions at https://github.com/thenetworg/oauth2-azure
