### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by zachary** [thephpleague/oauth2-client#802]
How to debug like guzzle client request
Types

        bool
        fopen() resource

Default

    None
Constant

    GuzzleHttp\RequestOptions::DEBUG

$client->request('GET', '/get', ['debug' => true]);

thanks

**Comment by ramsey** [comment]
You may create your own Guzzle client first and set the debug request option on it. Then, set that client as the HTTP client to use with the provider. Like this:

``` php
$client = new GuzzleHttp\Client([
    'debug' => true,
]);

$provider->setHttpClient($client);
```

Now, all requests made by the provider will use your custom client with it's custom options.
