### ISSUE TITLE
Attempted to load class "GenericProvider" from namespace "League\OAuth2\Client".

### ISSUE THREAD

**Issue by DanielZambranoC** [thephpleague/oauth2-client#817]
I've been able to use this dependency without problems before, but now that I'm trying to implement it in a symfony 2 project I haven't been able to implement it.

What for other instances has been to install the dependency by composing and start using, in this case it returns the following message:

> Attempted to load class "GenericProvider" from namespace "League\OAuth2\Client".
> Did you forget a "use" statement for another namespace?

Is there any additional step I'm missing?

**Comment by ramsey** [comment]
The correct, fully-qualified name for `GenericProvider` is `League\OAuth2\Client\Provider\GenericProvider`. You're missing one level of the namespace. 😃
