### ISSUE TITLE
Link broken to first party providers on Third-Party Providers page

### ISSUE THREAD

**Issue by joho1968** [thephpleague/oauth2-client#821]
On this page:

https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md

The link to "first party providers" in the intro paragraph:

https://github.com/thephpleague/oauth2-client/blob/master/providers/league

is broken, and generates a 404 on Github.

**Comment by ramsey** [comment]
The links are not broken. 😁 

See #638
