### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by sensei84** [thephpleague/oauth2-client#829]
WHEN EXEC getAccessToken i receive this error in a title

 // Try to get an access token using the authorization code grant.
        $accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
 ]);

Can i help me ?

**Comment by Jeckerson** [comment]
Do you use it inside docker?

**Comment by leocavalcante** [comment]
As a workaround, you can inject a custom Guzzle HTTP client with `'verify' => false` option.

```php
$provider = new GenericProvider([
    'clientId'                => 'demoapp',    // The client ID assigned to you by the provider
    'clientSecret'            => 'demopass',   // The client password assigned to you by the provider
    'redirectUri'             => 'http://example.com/your-redirect-url/',
    'urlAuthorize'            => 'http://brentertainment.com/oauth2/lockdin/authorize',
    'urlAccessToken'          => 'http://brentertainment.com/oauth2/lockdin/token',
    'urlResourceOwnerDetails' => 'http://brentertainment.com/oauth2/lockdin/resource'
], [
    'httpClient' => new GuzzleHttp\Client(['verify' => false]),
]);
```

**Comment by ramsey** [comment]
Thanks, @leocavalcante!

Closing this issue for now. If it's still a problem, please re-open.

**Comment by CaffeineLab** [comment]
1 - Grab the updated certs file from here:
https://curl.se/docs/caextract.html

2 - following the example provided by @leocavalcante, change:
`'httpClient' => new GuzzleHttp\Client(['verify' => false]), `

to: 
`'httpClient' => new GuzzleHttp\Client(['verify' => 'path/to/cacert.pem'])`
      
Setting verify to false isn't a very secure solution to this problem and I hope this works for the next person who runs across this issue.
