### ISSUE TITLE
The error is shown after trying to open a link with 'approval_prompt' = auto

### ISSUE THREAD

**Issue by ivaMadDog** [thephpleague/oauth2-client#831]
https://github.com/thephpleague/oauth2-client/blob/0facae9209aef5643bdd780e99996a21b6769c36/src/Provider/AbstractProvider.php#L347

Trying to auth via Google provider.

**Authorization Error**
Invalid parameter value for approval_prompt: 'auto' is not valid

**Comment by hugovk** [comment]
See also https://github.com/thephpleague/oauth2-google/issues/87.

Fix seems to be to remove that parameter or set to null. 

The social_auth_google Drupal module uses thephpleague/oauth2-client, and have a pending fix:

https://www.drupal.org/project/social_auth_google/issues/3129494

But would be good to fix it here too.

**Comment by sasa1007** [comment]
I found solution in

Symfony 5

namespace League\OAuth2\Client\Provider\AbstractProvider;

line 345
$options += [
'response_type' => 'code',
'prompt' => 'consent'
];
But i thing that isnt smart to changing something in vendor files - but I dont know how to override that class out of vendor

**Comment by ramsey** [comment]
Please either extend `AbstractProvider` to create your own provider that removes this, or use the league/oauth2-google package, which properly removes it. https://github.com/thephpleague/oauth2-google
