### ISSUE TITLE
Google V2 endpoint dont support anymore approval_prompt parameter

### ISSUE THREAD

**Issue by dpenezic** [thephpleague/oauth2-client#832]
Hi,
according Google documentation https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters and info I found on 
https://community.boomi.com/s/article/oauth2refreshtokenonlyworksforanhouringoogleintegration
approval_prompt is not support and you need to delete usage of it in  
https://github.com/thephpleague/oauth2-client/blob/0facae9209aef5643bdd780e99996a21b6769c36/src/Provider/AbstractProvider.php#L347

We using SimpleSamlPHP foun that yesterday, but it is look that otehr implementation is efected to check Drupal issue https://www.drupal.org/project/social_auth_google/issues/3129494

**Comment by ramsey** [comment]
Please use the league/oauth2-google package, available here: https://github.com/thephpleague/oauth2-google

The `approval_prompt` is properly unset in the oauth2-google package:

https://github.com/thephpleague/oauth2-google/blob/f70336461a1cd6399d3db014b30a5c8a165e8691/src/Provider/Google.php#L80-L82
