### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by lukasmedia** [thephpleague/oauth2-client#840]
Hi,

I updated laravel 5.6 to Laravel 5.8. First on my local, then test and finally production. Local and test all OK; they can acces oauth / offfice365. But on production:

invalid_client {"exception":"[object] (League\\OAuth2\\Client\\Provider\\Exception\\IdentityProviderException(code: 0): invalid_client at /vendor/league/oauth2-client/src/Provider/GenericProvider.php:222)

Any ideal?

More error messages:

AADSTS7000215: Invalid client secret is provided.
Trace ID: xxxxxxxx-0eee-4ad5-9616-xxxxxxx
Correlation ID: xxxxx-xxxx-xxx-xxxxxx-xxxxxxxxxx

**Comment by lukasmedia** [comment]
This took me a whole night. For ppl. with the same problem; i found this:
https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/issues/19#issuecomment-299530241

So yes, in my "OFFICE365_SECRET_APP_KEY" (.env) there where non a..z and 0..9 chars. I fixed it like this:
Before: OFFICE365_SECRET_APP_KEY=abc#def$ghi!
After: OFFICE365_SECRET_APP_KEY="abc#def$ghi!"

Now all ok.

**Comment by ramsey** [comment]
These are responses from the providers, which makes it difficult for us to test and help resolve.

For the Office365 issue, is this the OAuth2 client package you're using? https://github.com/tuutti/oauth2-office365

For the Salesforce issue, is this the package you're using? https://github.com/stevenmaguire/oauth2-salesforce

If so, please create an issue on the respective repository for the package you're using. They should be able to help debug the `invalid_client` issue better than we can.
