### ISSUE TITLE
Xero API -  Uncaught UnexpectedValueException

### ISSUE THREAD

**Issue by DannyRidgway** [thephpleague/oauth2-client#841]
Hi,

We have come across this PHP Fatal error when integrating with the Xero Accounting API.

From what I can tell the API endpoint should return JSON however in this case it did not which caused this exception. 

Is there anything we can do to stop it causing a fatal error?

Error details are as follows.

`PHP Fatal error:  Uncaught UnexpectedValueException: Invalid response received from Authorization Server. Expected JSON. in 
/composer/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:539
Stack trace:
#0 XeroAPI.php(79): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)`

Regards,
Dan

**Comment by adwconnect** [comment]
Anyone able to help please? I'm also getting similar... When I try to authorize Xero it comes back to my site with error 500.

In log it says: "ERROR - 2020-09-29 18:39:58 --> Severity: error --> Exception: Invalid response received from Authorization Server. Expected JSON. /homepages/.../htdocs/.../.../application/third_party/xero-oauth2/vendor/league/oauth2-client/src/Provider/AbstractProvider.php 539"

**Comment by ramsey** [comment]
Are you using a third-party OAuth2 client provider for Xero? Maybe this one? https://github.com/XeroAPI/xero-php-oauth2

If so, please submit your issue on their tracker. We're unable to help with invalid responses from third-party providers.

**Comment by vijayrana-99** [comment]
Did anyone get the solution? Facing the same issue
