### ISSUE TITLE
How to getAccessToken with resource or get id_token ?

### ISSUE THREAD

**Issue by p0tvin29** [thephpleague/oauth2-client#844]
I've followed this guide (http://www.redbaronofazure.com/?p=7566) to add a few custom claims to azure AD policy and i'm trying to get the onpremisessamaccountname . How can I specify resource when trying to get access token OR how do I get the id_token with the access_token ?

**Comment by ramsey** [comment]
Please open an issue on https://github.com/thenetworg/oauth2-azure. They'll be able to help you much better than we can. Cheers!
