### ISSUE TITLE
Composer not recognizing GenericProvider on Laravel

### ISSUE THREAD

**Issue by Kennibravo** [thephpleague/oauth2-client#851]
`$provider = new \League\OAuth2\Client\Provider\GenericProvider([
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
        'redirectUri' => $redirectUri,
        'scopes' => $scopes,
        'scopeSeparator' => ' ',
        'urlAuthorize' => $OAUTH_URL . 'authorize',
        'urlAccessToken' => $OAUTH_URL . 'token',
        'urlResourceOwnerDetails' => 'https://api.aweber.com/1.0/accounts'
    ]);`

That's my code, I am getting **Class 'League\OAuth2\Client\Provider\GenericProvider' not found**

**Comment by curry684** [comment]
Did you load the autoloader?

**Comment by ramsey** [comment]
Make sure you installed this library using `composer require league/oauth2-client` and that you have the autoloader set up properly. Laravel should handle much of this for you, but double check.

If you're still having issues, and you know you're using the autoloader, try running `composer dump-autoload` to regenerate the autoloader.

**Comment by armstrong-series** [comment]
> Did you load the autoloader?

yes, I have the same error, I have done composer dump-autoload, the package is in my composer.json file but still telling me not found
