### ISSUE TITLE
Is this available as a WordPress plugin?

### ISSUE THREAD

**Issue by haneef95** [thephpleague/oauth2-client#855]
Hi,

Is the OAuth2-Client library available as a WordPress plugin?

Even if it doesn't have a GUI, I could just use WordPress add_action() or add_filter() hook functions.

Thanks,

**Comment by ramsey** [comment]
There is a WordPress OAuth2 client library that may be used to authenticate against a WordPress website with the WP OAuth Server plugin installed: https://github.com/krombox/oauth2-wordpress

As for hooking this into WordPress to use the client library from within WordPress code, you might need to ask around the WordPress community. There have been some projects to use Composer in WordPress, so you might start asking around about those. Good luck!
