### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by JoyceBabu** [thephpleague/oauth2-client#858]
PHP 7.4 is not listed among the supported PHP versions. Is it not supported, or is it a documentation error?

**Comment by Jeckerson** [comment]
Using `oauth2-client` since PHP7.4 was released. All works good. Docs need to be updated.

**Comment by ramsey** [comment]
Updated docs and tests. A new release is forthcoming, supporting PHP 5.6 through 8.0.
