### ISSUE TITLE
How to update using PUT Method

### ISSUE THREAD

**Issue by Sitetools** [thephpleague/oauth2-client#859]
I'm working with the Workflowmax API and I can GET records from Jobs, Costs and PurchasOrders.
I'm having trouble updating records, I'm trying to use PUT but I'm not even getting a response back from the call.
Please see below for a simplified example of what I'm doing.
This is the doc page about the methods: https://www.workflowmax.com/api/v3/job-methods#

```PHP
$accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
]);

$xeroTenantIdArray = $provider->getParsedResponse($connectionsResponse);
$options = [
    'scope' => ['workflowmax workflowmax.job  offline_access']
];
$options['headers']['xero-tenant-id'] = $xeroTenantIdArray[0]['tenantId'];
$options['headers']['Accept'] = 'application/json';        


$putArray = array( 'Cost' => array( 'UUID' => 'afd13b29-dde0-48d5-98fd-15d5558921dd', 'Note' => "a note about the widget" ) );
$CostPutURL = 'https://api.xero.com/workflowmax/3.0/job.api';
$options['body'] = json_encode($putArray);

$request = $this->provider->getAuthenticatedRequest( 'PUT', $CostPutURL, $accessToken, $options );
$response = $this->provider->getParsedResponse( $request );

```

**Comment by ramsey** [comment]
It looks like you're making the `PUT` request to `https://api.xero.com/workflowmax/3.0/job.api`, but that's only the base URL for their API.

You'll need to use a URL like `https://api.xero.com/workflowmax/3.0/job.api/update`, I think.
