### ISSUE TITLE
Invalid response received from Authorization Server. Expected JSON.

### ISSUE THREAD

**Issue by zhukovsergei** [thephpleague/oauth2-client#861]
Hi,
Can you help me?
I just receive JSON answer from a server but I still see this error:

> Invalid response received from Authorization Server. Expected JSON.

And what is the urlResourceOwnerDetails parameter? In my common implementation with Oauth2 server I don't have any urlResourceOwnerDetails.

How to specify the scopes for GenericProvider? It's private property on GenericProvider without  **ScopeSetter**
I tried to copy GenericProvider and change it on public but it was an error "invalid scope"

**Comment by ramsey** [comment]
The `GenericProvider` is intended for very minimal, generic use only. To support other scopes for a specific provider, you'll need to extend `AbstractProvider` and implement the scopes and any other functionality the provider expects.

For example, if you're receiving "Invalid response received from Authorization Server. Expected JSON." from the provider, then that means they're sending back a non-standard response that the `GenericProvider` can't handle. You'll need to implement your own way to parse their response in a custom provider.
