### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by angrybrad** [thephpleague/oauth2-client#862]
PHP 8 will be officially released in 4 days.

As it currently it, this library won't be installable via Composer if you're running PHP 8 because of https://github.com/thephpleague/oauth2-client/blob/master/composer.json#L9

Was going to attempt to run the tests against PHP 8, but looks like 7.4 isn't even part of the test suite: https://github.com/thephpleague/oauth2-client/blob/master/.travis.yml#L4-L9

Are there plans to add support for PHP 8?

**Comment by ramsey** [comment]
@angrybrad I'm going to take a stab at this to see what's need to support 8. Thanks!
