### ISSUE TITLE
After migrating from Auth1 to Auth2.0 we are getting bellow error every day

### ISSUE THREAD

**Issue by rmaulik1991** [thephpleague/oauth2-client#867]
After migrating from Auth1 to Auth2.0 we are getting bellow error every day. 

UnexpectedValueException: Failed to parse JSON response: Syntax error in .../vendor/league/oauth2-client/src/Provider/AbstractProvider.php:650

**Comment by ramsey** [comment]
If you're using the `GenericProvider`, this makes sense. Not all providers respond with values that the `GenericProvider` can parse. You might need to implement your own custom provider, extending the `AbstractProvider` and overriding the necessary methods to parse the response properly.

**Comment by ramsey** [comment]
Closing due to lack of response. If you're still having this problem, please open a new issue.
