### ISSUE TITLE
State provided via constructor is ignored

### ISSUE THREAD

**Issue by mortenscheel** [thephpleague/oauth2-client#869]
The docblock for `AbstractProvider` constructor mentions `state` as one of the properties that can be included in the `$options` array. 

Is there a reason why the `getAuthorizationParameters` doesn't check if `$this->state` already has a value? If so, what is the point of passing a `state` value to the constructor?

**Comment by ramsey** [comment]
The `AbstractProvider` doesn't handle state, but it is provided so that third-party providers may use it.
