### ISSUE TITLE
When 3.x version will be released?

### ISSUE THREAD

**Issue by kromacie** [thephpleague/oauth2-client#877]
https://github.com/thephpleague/oauth2-client/issues/753
https://github.com/thephpleague/oauth2-client/issues/752

As I saw, there seems to be an important issue to solve, but still it has not been fixed even after you've announced it more than year ago. I don't know if there are more issues like this but that one specifically has forced me to redesign my system after such an unexpected reveal.

Do you have any further plans about it? 

Also if there is a possibility to contribute with that kind of improvement, I would like to do so.
Just please, let me know if you even take this into consideration.

**Comment by ramsey** [comment]
It's unclear how the issues you linked to are related to version 3.x. These issues were fixed and released before you opened this issue.

We always welcome contributions. If you'd like to help, feel free to let us know what you'd like to work on, and I'm sure we'll be more than happy to accept a pull request. 😄 

As for now, we have no timeline or estimate for when version 3 will be released.
