### ISSUE TITLE
AbstractProvider - unexpected, undocumented exceptions

### ISSUE THREAD

**Issue by lukaszmakuch** [thephpleague/oauth2-client#880]
Hello! 👋

First of all, thank you for this project. It has saved me tons of time! 👍

I'm opening this issue to discuss the exceptions thrown by the `AbstractProvider` class.

When working with a provider, like the `GenericProvider`, I'd expect to catch some `IdentityProviderException`s. Its nicely documented:
```
* Exception thrown if the provider response contains errors.
```
However, much to my surprise, some methods such as `getAccessToken` or `getResourceOwner` may throw an `UnexpectedValueException` when there's something wrong with the response received from the Identity Provider. Sadly, this is not documented.

To be honest, I expected to catch nothing but `IdentityProviderException`s and my code broke because there was no catch block for `UnexpectedValueException`s.

What are your thoughts on this matter? 🤔 Should the fact that an `UnexpectedValueException` may be thrown be documented? Or maybe we can risk some breaking changes and modify the code to throw `IdentityProviderException`s instead of `UnexpectedValueException`s?

Cheers!

**Comment by cloudcogsio** [comment]
You can probably adjust your code to catch the different exceptions?

```PHP

try {
    $accessToken = $provider->getAccessToken($grant, array $options = [])
} catch (IdentityProviderException $e) {
    // handle IdentityProviderException exceptions here
} catch (UnexpectedValueException $e) {
    // handle UnexpectedValueException  exceptions here
}

```

OR

```PHP

try {
    $accessToken = $provider->getAccessToken($grant, array $options = [])
} catch (IdentityProviderException | UnexpectedValueException $e) {
    // handle IdentityProviderException and UnexpectedValueException exceptions here
} 

```

See: https://www.php.net/manual/en/language.exceptions.php#language.exceptions.catch

**Comment by lukaszmakuch** [comment]
Thank you for your reply.

You’re right and it’s pretty straightforward to catch all the exceptions once you know they may be thrown.

What I’d like to see improved is the clarity of the documentation (or the documented code). I believe it’d be great if developers could write all the necessary catch blocks based solely on the documentation, without the need of debugging their code, analyzing logs etc.

**Comment by ramsey** [comment]
Thanks for the suggestion, @lukaszmakuch. We'll keep this open until we've added appropriate `@throws` tags to all the docblocks. I hope that will help.
