### ISSUE TITLE
[Question] Getter method "getResourceOwnerDetailsUrl" needs access token parameter, but it is not used.

### ISSUE THREAD

**Issue by phprogramer** [thephpleague/oauth2-client#883]
Hello,

First of all, thank you for an amazing work! I have a question, that I was not able to find answer for. I am using `GenericProvider`, and I need to get `urlResourceOwnerDetails`. As i can see there is a public getter method, but it requires `AccessToken $token` parameter, which is not being used in that method. My question is - why there is a required `AccessToken` parameter that is not used, and how should I get `urlResourceOwnerDetails`  when I do not have `AccessToken` instance.

**Comment by mcgrogan91** [comment]
That method is defined in the abstract `AbstractProvider`.  This is probably a better question to ask in `league/oauth2-client` as this is simply an implementation specific to Withings devices.  My best guess is that there are many Oauth2 Clients that would need the access token to get Resource Owner details, so it's an argument of the function.  I'm not sure what your best bet to get around that would be.

**Comment by cloudcogsio** [comment]
You must provide the ResourceOwnerDetailsUrl. The generic provider does not know about your environment unless you tell it.

```PHP

    /**
     * Returns all options that are required.
     *
     * @return array
     */
    protected function getRequiredOptions()
    {
        return [
            'urlAuthorize',
            'urlAccessToken',
            'urlResourceOwnerDetails', // <--- YOU PROVIDE THIS
        ];
    }

```

You must pass in this value when configuring your GenericProvider instance.

```PHP

$provider = new League\OAuth2\Client\Provider\GenericProvider([
    'urlResourceOwnerDetails' => 'https://xxxxxxxxx',
    ...
]);

```

**Comment by ramsey** [comment]
Thanks for helping out, @cloudcogsio !
