### ISSUE TITLE
AbstractProvider contains logging 

### ISSUE THREAD

**Issue by mikkellindblom** [thephpleague/oauth2-client#905]
Hi :)

While setting up an integration I noticed that you are logging the parsed response in AbstractProvider.php line 537, see `Log::info($response);`. In my opinion this could be a security concern, as access tokens can be logged in unsecure log files, without the developer knowing.

VER. 2.6.0

```
 public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
        ];
        $params   = $grant->prepareRequestParameters($params, $options);
        $request  = $this->getAccessTokenRequest($params);
        $response = $this->getParsedResponse($request);
        Log::info($response);
        if (false === is_array($response)) {
            throw new UnexpectedValueException(
                'Invalid response received from Authorization Server. Expected JSON.'
            );
        }
        $prepared = $this->prepareAccessTokenResponse($response);
        $token    = $this->createAccessToken($prepared, $grant);

        return $token;
    }
```

**Comment by ramsey** [comment]
I'm not sure where that `Log::info($response)` line is coming from. It's not in our code. We've never used a static logging library like this.

https://github.com/thephpleague/oauth2-client/blob/2334c249907190c132364f5dae0287ab8666aa19/src/Provider/AbstractProvider.php#L517-L547
