### ISSUE TITLE
Release of milestone v3 features 

### ISSUE THREAD

**Issue by blubberblah** [thephpleague/oauth2-client#908]
Hello :-)
I've seen that this PR https://github.com/thephpleague/oauth2-client/pull/901 is referenced by milestone v3: https://github.com/thephpleague/oauth2-client/milestone/3
Can you give a rough estimate when milestone v3 will be scheduled for release?
Regards

**Comment by ramsey** [comment]
We don't have a rough estimate for version 3, at this time. Sorry.
