### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by elshobokshy** [thephpleague/oauth2-client#913]
Hi. In your documentation `https://oauth2.thephpleague.com/requirements/` you're saying that PHP 7.4 is the maximum supported version, but in your readme you're saying PHP 8 is supported. So, are the docs not up to date?

**Comment by ramsey** [comment]
The docs you've linked to are for the oauth2-server project. Please open an issue on the repo for that project: https://github.com/thephpleague/oauth2-server
