### ISSUE TITLE
error in manual

### ISSUE THREAD

**Issue by ethaniel** [thephpleague/oauth2-client#914]
The part for refreshing the token in (https://github.com/thephpleague/oauth2-client/blob/master/docs/usage.md) has this code:
```
$existingAccessToken = getAccessTokenFromYourDataStore();
if ($existingAccessToken->hasExpired()) {
```

If I have the access token in an simple variable, how do I check it for expiration?
I think the manual needs to clarify this.

Thank you for the amazing library!

**Comment by ramsey** [comment]
Thanks for updating this issue with your solution!
