### ISSUE TITLE
Deprecation notice with PHP 8.1

### ISSUE THREAD

**Issue by frenchcomp** [thephpleague/oauth2-client#926]
Hi
There are a deprecation notice with PHP 8.1 in the AccessTokenInterface :

During inheritance of JsonSerializable: Uncaught Return type of League\OAuth2\Client\Token\AccessTokenInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.

**Comment by MyIgel** [comment]
Should be fixed by https://github.com/thephpleague/oauth2-client/pull/919

**Comment by SelviA** [comment]
Hi,
Thanks for the fix.
When will you create a release with this fixes ?

**Comment by frenchcomp** [comment]
Thanks for the fix.

**Comment by jakubvojacek** [comment]
Any chance to tag a new version please?

**Comment by ramsey** [comment]
This is now fixed in version 2.6.1. Thanks!
