### ISSUE TITLE
Support PHP versions?

### ISSUE THREAD

**Issue by stephanvierkant** [thephpleague/oauth2-client#927]
I see this library still supports PHP 5.6, which is End of LIfe as of December 31, 2018. Even 7.3 is EOL as of today.

What's the policy about PHP support? The only [supported versions](https://www.php.net/supported-versions.php) are 7.4, 8.0 and 8.1

**Comment by ramsey** [comment]
While those are the only officially supported versions of PHP, many still use this library on older versions, so we'll continue to maintain support for older versions until that maintenance overhead becomes a burden.

**Comment by stephanvierkant** [comment]
You are still using PHP 5.6?!

And if so: what's the policy when to drop support?

**Comment by ramsey** [comment]
We don't have an official policy on when to drop support. Currently, the maintenance burden for continuing to support PHP 5.6 is low, so there's no compelling reason to drop support for it.
