### ISSUE TITLE
Suggestion - a very small code change would implement rate limiting

### ISSUE THREAD

**Issue by globalvisionmedia** [thephpleague/oauth2-client#968]
a lot of APIs have rate limiting but...

If you were to add:
        $client_options = ['timeout', 'proxy', 'handler'];

then we could use this: **composer require spatie/guzzle-rate-limiter-middleware** and write apps that include (for example)

**$stack = HandlerStack::create();
$stack->push(RateLimiterMiddleware::perSecond(8));**

$provider = new Provider([
    'clientId'     => MYOB_CLIENT_ID,
    'clientSecret' => MYOB_CLIENT_SECRET,
    'redirectUri'  => CALLBACK_URI,
    'username'     => USERNAME,
    'password'     => PASSWORD,
    'scopes'       => ['CompanyFile'],
    **'handler'      => $stack**
]);

**Comment by ramsey** [comment]
The next major version of this library will support PSR-18 HTTP clients, which should allow for greater control over the HTTP client and all the options you might want to set on it. 🙂
