### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by thomaspalmer** [thephpleague/oauth2-client#977]
Hello!

Thanks for this package! 

I've been successfully implementing an auth flow using pkce, using your library. Just wondering when there might a stable release for it as I'm having to point my composer config to your repository.

Unless I'm missing something of course...

Keep up the good work.

**Comment by shadowhand** [comment]
Is there something we haven't released that is needed?

**Comment by thomaspalmer** [comment]
Hey,

I couldn’t get PKCE support through normal install channels. I’ve ended up writing my own provider for it now as I also needed support for certificate credentials. If you’re interested in a PR for that let me know.

Thanks for replying.

**Comment by ramsey** [comment]
@shadowhand We haven't done a release since merging #901, which is what I think @thomaspalmer is asking for.

**Comment by thomaspalmer** [comment]
Hey,

That's correct @ramsey.

Not such a problem anymore as I've added my own provider, keep up the good work :)

**Comment by stof** [comment]
@ramsey @shadowhand looks like this release is still not done (which is why #982 was reported btw)

**Comment by ramsey** [comment]
PKCE support is now available in version 2.7.0.
